### ISSUE TITLE
似乎Facade不起作用

### ISSUE THREAD

**Issue by hareluya** [overtrue/laravel-wechat#1]
Hi, 我按照手册引入了相关的provider和facade。但是在controller中使用Wechat::时，报找不到相关的类。很迷惑哟~

**Comment by hareluya** [comment]
Dear,
我发现问题在哪里了。。
我这种小菜鸟经常犯地错误-0-，Facade前要加 \ 。。。
记录在这里，让后人可以免得再犯咯。。

class WechatController extends Controller {

    public function serve()
    {
        \Wechat::on('message', function ($message)
        {
            \Log::info("收到来自'{$message['FromUserName']}'的信息：'{$message['Content']}'");

        });

        return \Wechat::serve();
     

    }
}

**Comment by overtrue** [comment]
在文件头部`use`即可:

```php
<?php

namespaec App\Http\Controllers;

use Wechat;
use Log;

class WechatController {
     public function serve() {
        Wechat::on('message', function ($message)
        {
            Log::info("收到来自'{$message['FromUserName']}'的信息：'{$message['Content']}'");

        });

        return Wechat::serve();
     }
}
```
