### ISSUE TITLE
发送模板消息有问题

### ISSUE THREAD

**Issue by mani95lisa** [overtrue/laravel-wechat#10]
感谢作者贡献此库，之前一直node，现在发现PHP库发送模板消息有点问题：

1. url是必填项，node是非必填的
2. \n字符无效，node是有效的

这两个部分对我们现在的应用场景蛮重要的，请问下应该修改库的什么部分来修复这两个问题呢，多谢！

**Comment by overtrue** [comment]
node是啥？

**Comment by overtrue** [comment]
你能说得详细点不，我这里url也没有必填啊？

**Comment by mani95lisa** [comment]
@overtrue 就是这两个区别
![wechat_1432862351](https://cloud.githubusercontent.com/assets/1968989/7874759/9f87b42e-05e6-11e5-81e5-64ad4c3ef776.png)
![wechat_1432862361](https://cloud.githubusercontent.com/assets/1968989/7874760/a0cddc78-05e6-11e5-8c17-a3aed59d2415.png)

**Comment by overtrue** [comment]
@mani95lisa 你的代码我看看。

注意在php里 "\n" 只在双引号内才表示换行，单引号内无效。

**Comment by mani95lisa** [comment]
啊，是引号的问题，难怪呢，PHP还有这个区别呢 :smile: 多谢

**Comment by overtrue** [comment]
@mani95lisa 哈哈

**Comment by mani95lisa** [comment]
@overtrue 发现个新问题，下面这样设置颜色无效呢，不过通过value,color的方式就可以~

`"first"    => array("恭喜你购买成功！", '#555555'),`

**Comment by overtrue** [comment]
@mani95lisa 麻烦去https://github.com/overtrue/wechat/issues 提个bug,并贴上你的逻辑代码，谢谢

**Comment by mani95lisa** [comment]
@overtrue 好的~
