### ISSUE TITLE
微信切换用户后, 再次访问网站, 显示的是旧用户的信息

### ISSUE THREAD

**Issue by Hexor** [overtrue/laravel-wechat#103]
我的网站是在微信公众号里被访问的, 进入公众号后, 点击一个公众号内的链接就会在微信浏览器中跳转到我的网站

网站设置了 wechat oauth 的 middleware ,也就是 `'middleware' => ['wechat.oauth']`, 所以在用户访问网站并且成功授权登录后, 服务器就得到了用户的 Openid 等信息

当微信用户A 访问网站后, 切换微信用户到另外一个微信用户B, 再次进入公众号访问这个网站, 此时服务器得到的还是A 用户的信息比如 openid 等.

我在网页上打印出请求所附带的 sessionid 之后发现, 即使切换了用户 sessionid 也没有发生变化, 两次的 sessionid 是相同的. 

请教问题在什么地方? 是微信自身的问题嘛? 

另 [微信官方说明账号与账号之间的缓存是独立存储的](https://developers.weixin.qq.com/blogdetail?action=get_post_info&lang=zh_CN&token=&docid=f89ad6689bf605d7132b33c6944c673d)

**Comment by overtrue** [comment]
浏览器 sessionid 缓存了。。。

**Comment by Hexor** [comment]
@overtrue 谢谢回答. 那解决方案是不是只能每次进入网页的时候重新获取一次 sessionid? 而且微信官方说是缓存是独立存储的啊, 他们说错了么

**Comment by overtrue** [comment]
@Hexor 缓存是缓存 session 是 session.. session 是浏览器负责的，缓存是微信 app 负责的，缓存指聊天记录，用户资料

**Comment by overtrue** [comment]
@Hexor 你可以修改一下 laravel 中的 `config/session.php` 中的 `expire_on_close` 为 `true` 试试

**Comment by Hexor** [comment]
@overtrue 已经设为 true 了, 但是没有效果  ...

**Comment by overtrue** [comment]
设置为 true 后你得首先清理你服务器上已经存在的 session 缓存，根据你的存储方式清除指定的内容再试

**Comment by Hexor** [comment]
清了 而且我默认就是 true , 没变过

**Comment by overtrue** [comment]
那就按我的中间件改写一个无 session 支持的中间件吧，这样就是每次都授权哦

**Comment by Hexor** [comment]
好的 那我再研究一下 谢谢 😆
