### ISSUE TITLE
接口调用微信 45009 错误, 接口调用超过限制

### ISSUE THREAD

**Issue by Hexor** [overtrue/laravel-wechat#104]
使用 $poi = $this->wechat->poi; 来获取门店列表.

多次调用之后, 微信服务器就会返回 '45009' 错误代码的错误. 也就是 '接口调用超过限制'

我去开发者后台看到 获取access_token 接口的调用次数只有19次, 远远没有到 每日2000次的限制?

请问这可能是什么原因造成的?

**Comment by overtrue** [comment]
这就不晓得了，这得问微信
