### ISSUE TITLE
退款时出现以下错误

### ISSUE THREAD

**Issue by jkgeekJack** [overtrue/laravel-wechat#105]
RequestException in RequestException.php line 52:
Error creating resource: [message] fopen(): Unable to set private key file `/usr/share/nginx/html/leguanzhu/resources/cert/apiclient_cert.pem'
[file] /usr/share/nginx/html/leguanzhu/vendor/guzzlehttp/guzzle/src/Handler/StreamHandler.php
[line] 312
[message] fopen(): Failed to enable crypto
[file] /usr/share/nginx/html/leguanzhu/vendor/guzzlehttp/guzzle/src/Handler/StreamHandler.php
[line] 312
[message] fopen(https://api.mch.weixin.qq.com/mmpaymkttransfers/promotion/transfers): failed to open stream: operation failed
[file] /usr/share/nginx/html/leguanzhu/vendor/guzzlehttp/guzzle/src/Handler/StreamHandler.php
[line] 312

**Comment by overtrue** [comment]
```shell
php -m | grep openssl
```

**Comment by jkgeekJack** [comment]
https://github.com/overtrue/wechat/issues/492，这里说把两个pem合并是什么意思

**Comment by jkgeekJack** [comment]
@overtrue 还是同样的错误

**Comment by overtrue** [comment]
证书问题与你 PHP 环境有关，请自行检查哈

**Comment by callmejea** [comment]
那啥， 我插一句，因为php的问题，php中微信的证书将key.pem的内容直接粘贴到cert.pem后面， 之后就好了
