### ISSUE TITLE
请教一个在lumen+dingo+jwt的环境下的问题

### ISSUE THREAD

**Issue by mentallxm** [overtrue/laravel-wechat#107]
在验证微信服务器的时候，提示：
ERROR: Symfony\Component\Debug\Exception\FatalThrowableError: Call to undefined method Symfony\Component\HttpFoundation\Response::header()
我知道可能是dingo response的问题，我想要不使用dingo的middleware或者是response，但是我是菜鸟，花了很长时间还是没有弄好，
请您看下是怎么回事

**Comment by mingyoung** [comment]
那怎么不去 dingo 问……

**Comment by mentallxm** [comment]
dingo是老外做的吧 没法和他们沟通

**Comment by overtrue** [comment]
sorry, 实在看不明白这个东西问题是什么情况，提问请提供上下文，报方法不存在就是真的调用了不存在的方法咯，如果是第三方组件很有可能就是版本变更删除了该方法，如果是你自己的代码那就是用错了方法。
