### ISSUE TITLE
Call to undefined method EasyWeChat\Server\Guard::setRequest() 错误

### ISSUE THREAD

**Issue by hinet** [overtrue/laravel-wechat#110]
guzzlehttp/guzzle 已移除并更换为https://github.com/guzzle/guzzle，造成：Call to undefined method EasyWeChat\Server\Guard::setRequest() 错误。请官方尽快更新版本

**Comment by deboyblog** [comment]
在群里问了下 临时解决方案 安装的时候不要安装最新版的
```
composer require overtrue/laravel-wechat 3.1.4
```
我的版本信息
```
    "require": {
        "php": ">=5.6.4",
        "guzzlehttp/guzzle": "^6.2",
        "laravel/framework": "5.4.*",
        "laravel/tinker": "~1.0",
        "overtrue/laravel-wechat": "3.1.4"
    }
```
仅供参考 群友说 `3.1.1` 是最稳定的 我从 `3.1.8` 一个个小版本 降级到 `3.1.4` 可以正常使用

**Comment by loktarjugg** [comment]
这个问题是[这个](https://github.com/overtrue/laravel-wechat/commit/cc2c3b805a9e2c4f8d45f4a2485e06beaff5b00c)更新导致的，想要解决，更新下composer吧
`composer require "overtrue/laravel-wechat:~3.1"`

**Comment by baijunyao** [comment]
我降到3.1.4解决了；多谢 @deboyblog

**Comment by overtrue** [comment]
@hinet @deboyblog @loktarjugg @baijunyao 该问题出现的原因是本地缓存有 overtrue/wechat 的低版本，安装时没有更新它，请安装 overtrue/laravel-wechat 最新版 3.1.9 解决该问题。

**Comment by baijunyao** [comment]
3.1.9测试通过；多谢； @overtrue
