### ISSUE TITLE
3.1.9 版不支持 Lumen

### ISSUE THREAD

**Issue by BruceFan-FS71** [overtrue/laravel-wechat#112]
从 3.1.8 升级到 3.1.9 后，Lumen 下提示：Class 'Illuminate\Foundation\Support\Providers\RouteServiceProvider' not found。

这个 RouteServiceProvider 在 Laravel 下面才有，导致整个 Lumen 的应用无法使用。

**Comment by overtrue** [comment]
@mingyoung 改进这块吧，最好不要依赖官方的那个 RouteServiceProvider
