### ISSUE TITLE
关于Token验证失败

### ISSUE THREAD

**Issue by hangdui** [overtrue/laravel-wechat#113]
描述：1、在老项目内无论怎么调试都无法验证 2、在纯净laravel中可以使用，并能正常验证。
问题：经过排查，发现是composer 中 dump-auoload中预加载文件导致的验证失败。。。但是具体为何并不清楚。。。
有没有办法解决啊
       
![image](https://user-images.githubusercontent.com/20531145/27725208-d5826fea-5da7-11e7-89bf-2bd895c19e70.png)

**Comment by overtrue** [comment]
那你就找你这些文件的问题啊，你这些文件是你自己写的，我怎么知道内容是啥啊。

**Comment by hangdui** [comment]
我随便写一个文件，通过自动加载，验证就失败，和文件内容无关啊

**Comment by overtrue** [comment]
sorry，这不在本插件工作范围内。
