### ISSUE TITLE
反馈一个微信小程序方面的问题，解密微信运动数据时报错，解密的数据为null

### ISSUE THREAD

**Issue by zhaoyang017** [overtrue/laravel-wechat#115]
请大神帮忙看一下，解密用户数据时是成功的，解密微信运动数据报下面的错误：
![2017-07-04 10 22 42](https://user-images.githubusercontent.com/18034112/27812641-dbeb649c-60a2-11e7-8298-12639a7f49bf.png)

**Comment by zhaoyang017** [comment]
已解决，微信小程序官方文档上关于`wx.getWeRunData`接口的返回值是（没有`iv`参数）：  
![image](https://user-images.githubusercontent.com/18034112/27813447-92a962a6-60a8-11e7-9781-35019b39d557.png)
  
官方解密示例是`wx.getUserInfo`，而`wx.getUserInfo`接口返回（有`iv`参数）：
![image](https://user-images.githubusercontent.com/18034112/27813539-2add8c78-60a9-11e7-90cf-a1c664682a2f.png)

然后我错误的使用了同一个`iv`参数。。。。我水平不够，微信官方文档还给我挖个坑。。。

**Comment by gyp719** [comment]
请问下， 你获取微信运动步数成功了吗？  我一直是  EasyWeChat \ Kernel \ Exceptions \ DecryptException
The given payload is invalid.

![image](https://user-images.githubusercontent.com/30563368/96209883-44020100-0fa3-11eb-9558-2ec075d4e68b.png)

**Comment by gyp719** [comment]
已解决， iv 参数获取错了
