### ISSUE TITLE
微信公众平台测试号，使用laravel中间件情况下，网页授权一直失败。。。请教下！

### ISSUE THREAD

**Issue by kideny** [overtrue/laravel-wechat#116]
laravel5.2+php5.6+laravel-wechat3.1环境，
使用wechat.oauth中间件的情况下，网页授权一直失败。
router.php打印结果为null，请教下，是不支持测试号吗？
路由写法，'middleware' => ['web','wechat.oauth:snsapi_base']

**Comment by wh469012917** [comment]
你这个问题没办法回答的，没有贴任何报错信息，没有任何与你代码有关的信息。建议你从如下步骤判断：
1. 网页授权是否绑定了域名（测试号可以绑定ip），绑定域名必须备案
2. key和secret是否写错
3. 微信浏览器下是否清空过session

**Comment by kideny** [comment]
@wh469012917 你好，请问wechat.oauth支持snsapi_base吗？

**Comment by wh469012917** [comment]
@kideny 你写代码都不看文档的吗

**Comment by kideny** [comment]
@wh469012917 你会说人话吗？laravel-chat这个库有文档？

**Comment by kideny** [comment]
@wh469012917 我左一个请，又一个请，你哪只眼睛看到laravel-wechat这个库有文档了。连个wiki都没有，你说我不看文档，你能不能别在这里秀你的弱智？EasyWeChat的文档里，有laravel的中间件的任何内容？你是眼睛瞎？

**Comment by overtrue** [comment]
@kideny 

1. README 就是文档，我不晓得你哪里定义的文档一定要是一个网站或者是一个 wiki 才叫文档。
2. 既然微信有两种 scopes，我肯定就是两种都支持啊，不然大家怎么用？
3. 你很没有礼貌。

**Comment by overtrue** [comment]
我已经锁掉了讨论，不希望再看到你们这样交流了，我的3点建议你也不需要反驳了，你认为错了，就在心里骂我就好了，或者新开一个 issue 来骂也行。
