### ISSUE TITLE
Readme叫文档，哈哈。

### ISSUE THREAD

**Issue by kideny** [overtrue/laravel-wechat#118]
奉旨来骂
1，傻逼；
2，傻逼；
3，傻逼 。

**Comment by kideny** [comment]
@overtrue 你不要来骂我了，在心里骂我就好了，或者重新开个issue。

**Comment by overtrue** [comment]
👍

**Comment by rayzhi** [comment]
用别人的开源代码还骂人，你觉得没文档那你倒是贡献出来啊，你以为你是谁？开源社区没义务为你服务
