### ISSUE TITLE
laravel-wechat 在 composer 安装的时候提示没有4.0版本

### ISSUE THREAD

**Issue by z88089** [overtrue/laravel-wechat#127]
如题，在执行 
 `composer require "overtrue/laravel-wechat:~4.0"` 
安装的时候，提示没有4.0版本，
上 packagist 上看了一下，发现laravel-wechat真都没有4.0，大神是不是忘记更新laravel-wechat的包了呢？
想用最新的，因为发现4.0较以前改动较大，希望以后迭代不会麻烦

**Comment by overtrue** [comment]
4.0 没发布啊

**Comment by z88089** [comment]
噢，但是下面的readme已经是4.0了，哈哈，希望快快发布，再次感谢您的分享！
