### ISSUE TITLE
Class 'Overtrue\LaravelWeChat\ServiceProvider' not found

### ISSUE THREAD

**Issue by todayqq** [overtrue/laravel-wechat#128]
`Overtrue\LaravelWeChat\ServiceProvider::class`
 => 
`Overtrue\LaravelWechat\ServiceProvider::class`

一个大小写的 Bug

**Comment by mingyoung** [comment]
4.0 未发布，看这(v3)里：https://github.com/overtrue/laravel-wechat/blob/3.1.10/README.md
