### ISSUE TITLE
为什么oauth2链接里的appid不是config/wechat.php里配置的app-id呢，而是默认的your-app-id

### ISSUE THREAD

**Issue by iyezhou** [overtrue/laravel-wechat#134]
https://open.weixin.qq.com/connect/oauth2/authorize?appid=your-app-id&redirect_uri=http%3A%2F%2Fq.xxx.com%2Fwechat%2Fregister&response_type=code&scope=snsapi_base&state=acfeecf347c9bf9bd4b444ad029ac888&uin=&version=16050f21&connect_redirect=1#wechat_redirect

**Comment by overtrue** [comment]
这是 laravel 的使用问题，谢谢，不在此 SDK 范围内。请自行检查配置问题。
