### ISSUE TITLE
好像对小程序的支付，配置文件的编写不够友好

### ISSUE THREAD

**Issue by simaguo** [overtrue/laravel-wechat#135]
没法$app->mini_program->payment这么调用，只能这么调用$app->payment支付，但小程序和公众号的appid不一样，一个配置文件不好写。

**Comment by overtrue** [comment]
你可以考虑用 4.0

**Comment by yyqqing** [comment]
@overtrue 我使用 composer require "overtrue/laravel-wechat:~4.0" 无法安装 4.0 ，提示 “Your requirements could not be resolved to an installable set of packages.”，请问应该怎么处理？

**Comment by kcersing** [comment]
一样诶，4.0还不能安装

**Comment by overtrue** [comment]
4.0 没发布啊，要用只能 dev-master

**Comment by kcersing** [comment]
谢谢
