### ISSUE TITLE
使用中间件，OAuth返回40125

### ISSUE THREAD

**Issue by iyezhou** [overtrue/laravel-wechat#136]
local.ERROR: Authorize Failed: {"errcode":40125,"errmsg":"invalid appsecret, view more at http:\/\/t.cn\/RAEkdVq, hints: [ req_id: Scg6za0214th22 ]"}

确定appsecret没问题，重置过好几次

**Comment by iyezhou** [comment]
我用微信公众平台接口调试工具调试，appId和appsecret都是正确的，可以返回access_token
我看了下源码：D:\www\CheckIn_Native\vendor\overtrue\socialite\src\Providers\WeChatOpenPlatformProvider.php，第69行
```
public function __construct(Request $request, $clientId, $credentials, $redirectUrl = null)
{
    parent::__construct($request, $clientId, null, $redirectUrl);

    $this->credentials = $credentials;
    if (is_array($credentials)) {
        list($this->componentAppId, $this->componentAccessToken) = $credentials;
    }
}
```

这个parent::__construct($request, $clientId, null, $redirectUrl);第3个参数$clientSecret传入为null

**Comment by mingyoung** [comment]
这是开放平台的，你用的是开放平台么

**Comment by iyezhou** [comment]
code已经获取到了，而且用获取到的code去获取access_token是成功的
https://api.weixin.qq.com/sns/oauth2/access_token?appid=xxxxxx&secret=xxxxxx&code=07105Lie1U0W6u0hZ0me1Cdoie105Lin&grant_type=authorization_code

**Comment by iyezhou** [comment]
@mingyoung 我是配置 official_account 的 OAuth

**Comment by mingyoung** [comment]
那你怎么翻开放平台的源码。。

**Comment by mingyoung** [comment]
把代码贴出来看看呗

**Comment by iyezhou** [comment]
![2017-09-11_22-39-54](https://user-images.githubusercontent.com/26378961/30280375-2b1bcbbc-9742-11e7-8c95-6ffbeaf9fcd2.png)
我也是顺着 这个报错的文件找的：\vendor\overtrue\socialite\src\Providers\AbstractProvider.php

**Comment by iyezhou** [comment]
代码就是打开了一个包含中间件路由的简单页面

**Comment by iyezhou** [comment]
我在\vendor\overtrue\socialite\src\Providers\WeChatProvider.php 第205行进行日志打印：
```
protected function getTokenFields($code)
{
    Log::info('appid: ' . $this->clientId);
    Log::info('secret: ' . $this->clientSecret);
    return array_filter([
        'appid' => $this->clientId,
        'secret' => $this->clientSecret,
        'component_appid' => $this->component ? $this->component->getAppId() : null,
        'component_access_token' => $this->component ? $this->component->getToken() : null,
        'code' => $code,
        'grant_type' => 'authorization_code',
    ]);
}
```

结果是：
```
local.INFO: appid: wx82119d04ea096854
local.INFO: secret: your-app-secret
```

说明appid的配置读进去了，但是secret的配置没读进去

但是我通过：$secret = config('wechat.official_account.secret'); 是正确的

原因出在哪里呢

**Comment by iyezhou** [comment]
解决了，还是配置文件的问题
