### ISSUE TITLE
安装出现问题

### ISSUE THREAD

**Issue by hwtdnet** [overtrue/laravel-wechat#140]
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package overtrue/laravel-wechat ~4.0 exists as overtrue/laravel-wechat[1.0-alpha, 1.0.0, 1.0.1, 1.0.2, 1.0.3, 2.0.0, 2.0.0-alpha, 2.0.1, 2.0.2, 2.0.3, 2.1.0, 2.1.1, 2.1.2, 3.0, 3.0.1, 3.0.2, 3.0.3, 3.0.4, 3.0.5, 3.0.6, 3.1.0, 3.1.1, 3.1.10, 3.1.2, 3.1.3, 3.1.4, 3.1.5, 3.1.6, 3.1.7, 3.1.8, 3.1.9, dev-master] but these are rejected by your constraint.

Installation failed, reverting ./composer.json to its original content.

**Comment by overtrue** [comment]
4.0 没发布
