### ISSUE TITLE
lumen5.5按照你的配置后报错

### ISSUE THREAD

**Issue by liuyi61123** [overtrue/laravel-wechat#141]
lumen.ERROR: Symfony\Component\Debug\Exception\FatalThrowableError: Class 'Overtrue\LaravelWeChat\ServiceProvider' not found in /var/www/api.liuyi61.top/vendor/laravel/lumen-framework/src/Application.php:183

**Comment by overtrue** [comment]
4.0 还没有发布，你装的是 3.0， 3.0 的命名空间是：`Overtrue\LaravelWechat\ServiceProvider`

**Comment by liuyi61123** [comment]
好的谢谢，那4.0大概什么时候发布？

**Comment by kcersing** [comment]
貌似都在关心4.0什么时候发布，哈哈哈。

**Comment by overtrue** [comment]
没有人帮忙测啊，我只能自己慢慢测再发布咯

**Comment by kcersing** [comment]
老大你只要在群里说一声，我们都会赴汤蹈火的~
