### ISSUE TITLE
Overtrue\LaravelWeChat\Facade class not found

### ISSUE THREAD

**Issue by wonghoukit** [overtrue/laravel-wechat#142]
config/app.php里面已经添加了
'EasyWeChat' => Overtrue\LaravelWeChat\Facade::class,

我在一个类的静态方法里面调用
use EasyWeChat;

$officialAccount = EasyWeChat::officialAccount();
$notice = $officialAccount->notice;

![image](https://user-images.githubusercontent.com/2990426/30470342-e72650ca-9a26-11e7-82a1-b2b6c143bc95.png)

**Comment by wonghoukit** [comment]
Laravel版本5.4 Laravel-Wechat版本3.1

**Comment by overtrue** [comment]
3.1 的命名空间：Overtrue\LaravelWechat\Facade::class
