### ISSUE TITLE
在控制器中调用$user = $app->oauth->user();失败

### ISSUE THREAD

**Issue by lxtac** [overtrue/laravel-wechat#144]
情况是这样的，完全按照官方配置，Laravel的控制器中使用session('wechat.oauth_user')可以拿到用户信息，但是如果用$app->oauth->user()则出现missing code的41008错误

**Comment by overtrue** [comment]
$app->oauth->user() 只在回调逻辑里用啊

**Comment by lxtac** [comment]
可是，回调逻辑里这个会返回空啊，但这个诡异的现象只是部分人会遇到90%的用户不会遇到，遇到的人session('wechat.oauth_user')是拿不到用户数据的

**Comment by qiumzh** [comment]
我现在也是这个问题。你是怎么处理的？ @lxtac
