### ISSUE TITLE
UnknownIdentifierException Identifier "openPlatform" is not defined. 

### ISSUE THREAD

**Issue by oknixus** [overtrue/laravel-wechat#149]
尝试了3次，报错：
```
UnknownIdentifierException
Identifier "openPlatform" is not defined.
```
配置时，是按照图中的步骤，一步一步进行配置的。
![image](https://user-images.githubusercontent.com/4592706/30710396-0be0320c-9ecb-11e7-9b5e-bb6e691523f9.png)
![image](https://user-images.githubusercontent.com/4592706/30710413-197781e0-9ecb-11e7-96a1-6ab32e1f47f5.png)
路由使用了图中定义的，
WeChatController.php的代码如下：
```
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Log;
use EasyWeChat;

class WechatController extends Controller
{
    public function serve()
    {
        Log::info('123');
        $openPlatform = EasyWeChat::openPlatform();
    }
}

```
是我哪里做的不对吗？
laravel使用的是laravel 5.4
overtrue/laravel-wechat 用的是        "overtrue/laravel-wechat": "^3.1"

**Comment by hirodeng** [comment]
同样的问题。Laravel 5.4.36, Laravel-wechat 3.1.10

**Comment by mingyoung** [comment]
这个 readme 是 4.0 的，3.1.10 看这里 https://github.com/overtrue/laravel-wechat/tree/3.1.10
