### ISSUE TITLE
版本没看懂。。

### ISSUE THREAD

**Issue by RDCynthia** [overtrue/laravel-wechat#154]
我刚来，看到文档说安装方式，然后给出一句安装命令，然后却说下面的无法安装，那我就装3.x版本，上面又说不兼容3.x。。这下面的文档到底是哪个版本的啊！！！

**Comment by mingyoung** [comment]
当前分支（4.x）版本不兼容 3.x 而已

**Comment by RDCynthia** [comment]
我不加版本号，安装的是3.1的。根据文档php artisan vendor:publish --provider="Overtrue\LaravelWeChat\ServiceProvider"添加配置文件没有反应。网页授权加入中间件后运行，提示找不到这个类。。。

**Comment by mingyoung** [comment]
4.x 的命名空间变了，你安装 3.x 的 README 来配置，链接在上面

**Comment by RDCynthia** [comment]
@mingyoung 十分感谢~~

**Comment by sunzhongwei** [comment]
是不是现在还不支持 Laravel 5.5?

php artisan vendor:publish --provider="Overtrue\LaravelWeChat\ServiceProvider"添加配置文件没有反应

**Comment by oknixus** [comment]
@mingyoung `overtrue/laravel-wechat` 是否不适合开发微信开放平台？ ~3.0 的版本，没有 `openPlatform` 的相关内容

**Comment by mingyoung** [comment]
@oknixus 支持的

**Comment by oknixus** [comment]
`Pimple \ Exception \ UnknownIdentifierException
Identifier "openPlatform" is not defined.`
尝试在浏览器中访问，报了这个错误

**Comment by oknixus** [comment]
postman 通过 post 方式访问，也是一样的错误

[](http://mini.lingshouyi.cn)

**Comment by mingyoung** [comment]
app('wechat')->open_platform

**Comment by oknixus** [comment]
@mingyoung 谢谢！希望这些内容可以写进文档里

**Comment by oknixus** [comment]
@mingyoung [开放平台](https://easywechat.org/zh-cn/docs/open_platform.html#微信服务器推送事件) 这里 Example 中的方法`$server->setMessageHandler()`，找不到，代码需要怎么做调整？今天一整天都在围着这个问题转，大哥帮忙给看看，解决一下吧

**Comment by RDCynthia** [comment]
是不是setMessageHandler里面的闭包不执行啊？

**Comment by oknixus** [comment]
是的，里面的代码没有任何反应

**Comment by oknixus** [comment]
完全照抄的 Example 中的代码
![image](https://user-images.githubusercontent.com/4592706/31376061-40c80416-ad69-11e7-9572-202f16dfad6d.png)

**Comment by mingyoung** [comment]
把你代码弄上来看看😠

**Comment by RDCynthia** [comment]
你在 laravel 中间件 verifyCsrfToken 里面，把路由加上试试，如果不行～～嘿嘿，和我一样～～半个月前就碰到了，还没解决呢。。。

**Comment by RDCynthia** [comment]
@mingyoung  代码就是例子中的代码，然后认证都没有问题，就是setMessageHandler闭包不执行，导致服务器不能返回信息，所以客户端一直提示，此公众号无法提供服务。。。求指教。。。

**Comment by mingyoung** [comment]
@RDCynthia 这个是“开放平台”的 server，和公众号没关系的哇🙄

**Comment by oknixus** [comment]
@RDCynthia 什么情况？你项目停了半个月？

**Comment by RDCynthia** [comment]
公众号的setMessageHandler也不行。。我就是跳过那个问题，然后提出了这个问题。。。sorry

**Comment by mingyoung** [comment]
@RDCynthia 要实现公众号的功能，请查看代授权方实现业务相关文档

```php
$app = $openPlatform->createAuthorizerApplication(...);
return $app->server->setMessageHandler(...)->serve();
```

**Comment by RDCynthia** [comment]
我还在练习阶段～～小白一个。。没有啥项目。。。

**Comment by oknixus** [comment]
是的，我这个是**开放平台**的，今天就一直在围着这个问题转，之前以为是 `$server->serve()` 在执行中，因为接收不到 `http://www.example.com/api/open?auth_code=queryauthcode@@@z5npZapM3GbEcVXdca7Z_U6nB2JTpl6BXrbERS5I8CrWENOEXwk_u8ttSk4XhYU3YVhsFd1skfQpMnMrWZZQpQ&expires_in=3600` 中的参数，导致了错误：[#160](https://github.com/overtrue/laravel-wechat/issues/160)，后来又一步一步查了一遍，发现这个 `setMessageHandler` 里面的代码都没执行

**Comment by mingyoung** [comment]
@oknixus 你 QQ 是什么

**Comment by RDCynthia** [comment]
版本：3.0   
 public function serve()
    {
        Log::info('request arrived.'); 

        $wechat = app('wechat');
        $wechat->server->setMessageHandler(function($message){
            return "欢迎关注 overtrue！";  #这里不执行。。真心不执行。。。
        });

        Log::info('return response.');

        return $wechat->server->serve();
    }

**Comment by oknixus** [comment]
@mingyoung 87909733
