### ISSUE TITLE
关于协作开发的问题

### ISSUE THREAD

**Issue by haosblog** [overtrue/laravel-wechat#16]
最近发现一个问题。由于需要注册 ServiceProvider，导致一个问题。
即：最初引用本插件的开发者在config/app.php中注册了ServiceProvider，将代码提交到版本库后别的开发者更新下来，由于laravel默认是将vendor加入了git的忽略列表，因此其他开发者需要执行一次composer update才可能将插件安装，但是由于config/app.php已经注册了Overtrue\LaravelWechat\ServiceProvider，但此时Overtrue\LaravelWechat\ServiceProvider是不存在的，那么composer update将会报错，导致update无法执行。
对于这个问题，是否有更好的解决方案呢？

**Comment by overtrue** [comment]
应该是用composer install吧？
