### ISSUE TITLE
文档中大小写出现错误

### ISSUE THREAD

**Issue by gw19900524** [overtrue/laravel-wechat#161]
> 创建配置文件：
> php artisan vendor:publish --provider="Overtrue\LaravelWeChat\ServiceProvider"

Overtrue\LaravelWeChat\ServiceProvider应该修改为Overtrue\LaravelWechat\ServiceProvider

**Comment by overtrue** [comment]
master 是没有发布的 4.0 版本，这不是错误就是 4.0 这样改的
