### ISSUE TITLE
token验证失败

### ISSUE THREAD

**Issue by zhfin** [overtrue/laravel-wechat#162]
WechatController.php

`<?php

namespace App\Http\Controllers;

use Log;

class WechatController extends Controller
{

    /**
     * 处理微信的请求消息
     *
     * @return string
     */
    public function serve()
    {
        Log::info('request arrived.'); # 注意：Log 为 Laravel 组件，所以它记的日志去 Laravel 日志看，而不是 EasyWeChat 日志

        $wechat = app('wechat');
        $wechat->server->setMessageHandler(function ($message) {
            return "欢迎关注 overtrue！";
        });

        Log::info('return response.');

        return $wechat->server->serve();
    }
}`

Log

![image](https://user-images.githubusercontent.com/30734994/31581071-ad9c3bd2-b126-11e7-8647-7ab143e1a000.png)

![image](https://user-images.githubusercontent.com/30734994/31581017-580f6a28-b125-11e7-978f-7e989cf492a2.png)

**Comment by zhfin** [comment]
![image](https://user-images.githubusercontent.com/30734994/31581095-82083588-b127-11e7-84e0-f1d16e7a9243.png)

![image](https://user-images.githubusercontent.com/30734994/31581102-aa3936ba-b127-11e7-9b2d-1d69bc6659f9.png)

**Comment by tangj1992** [comment]
我也遇到了这个问题，请问你是怎么解决的呢？

**Comment by tangj1992** [comment]
@zhfin
