### ISSUE TITLE
中间件错误：OAuthAuthenticate does not exist

### ISSUE THREAD

**Issue by shoutleafy** [overtrue/laravel-wechat#163]
您好：遇到一个OAuth的问题，出现中间件不能加载的情况，似乎是autoload没有读到？

环境：
php : 7.0
laravel : 5.1
laravel-wechat : 3.1

部分文件：
//Kernel.php   
` 
protected $routeMiddleware = [           
        'weoauth' => \Overtrue\LaravelWeChat\Middleware\OAuthAuthenticate::class,      
    ];
`

//route.php
`
Route::group(['middleware' => ['weoauth']], function () {
    Route::get('/user', function () {
        $user = session('wechat.oauth_user'); // 拿到授权用户资料

        dd($user);
    });
});
`

主要错误信息：
![errorcode](https://user-images.githubusercontent.com/7369296/31606788-a5e27ac4-b29c-11e7-830a-e34c4d06dc8e.png)

> ReflectionException in Container.php line 741:
> Class Overtrue\LaravelWeChat\Middleware\OAuthAuthenticate does not exist

**Comment by overtrue** [comment]
```diff
-  'weoauth' => \Overtrue\LaravelWeChat\Middleware\OAuthAuthenticate::class,
+ 'weoauth' => \Overtrue\LaravelWechat\Middleware\OAuthAuthenticate::class,
```

**Comment by a331210877** [comment]
所以是什么原因呢。 我的laravel5.5   laravel-wechat : 3.0
