### ISSUE TITLE
lumen  Class 'Overtrue\LaravelWeChat\ServiceProvider' not found

### ISSUE THREAD

**Issue by joinmm** [overtrue/laravel-wechat#168]
lumen  中注册时出现 Class 'Overtrue\LaravelWeChat\ServiceProvider' not found

**Comment by overtrue** [comment]
你用的什么版本？

**Comment by hare2011** [comment]
普通按照文档看这里
https://github.com/overtrue/laravel-wechat/tree/3.1.10
