### ISSUE TITLE
服务器验证问题

### ISSUE THREAD

**Issue by gaofei1974** [overtrue/laravel-wechat#17]
我用laravel 5.1.11的版本，在微信公众平台的服务器配置中，做服务器验证时总提示Token验证失败，验证要怎么操作，大神指教！！！！

**Comment by HivenKay** [comment]
请检查你的CSRF中间件，微信服务器配置是跨域请求，需要关闭你微信接口路由的CSRF
在App\Http\Middleware\VerifyCsrfToken中的$except中加入你配置的路由名称:
    protected $except = [
        'wechat'
    ];

**Comment by gaofei1974** [comment]
搞定，十分感谢！！
