### ISSUE TITLE
Class 'Overtrue\LaravelWeChat\ServiceProvider' not found

### ISSUE THREAD

**Issue by fannan1991** [overtrue/laravel-wechat#171]
你好，我安装的3.1的，出现这个报错

**Comment by fannan1991** [comment]
问题找到了，注册ServiceProvider时，文档里的大小写区分错了
Overtrue\**LaravelWeChat**\ServiceProvider::class,
这是文档里的，正确写法应该如下：
Overtrue\**LaravelWechat**\ServiceProvider::class,

**Comment by fannan1991** [comment]
问题找到了，注册ServiceProvider时，文档里的大小写区分错了
`Overtrue\LaravelWeChat\ServiceProvider::class,`
这是文档里的，正确写法应该如下：
`Overtrue\LaravelWechat\ServiceProvider::class,`

**Comment by dingtwo** [comment]
厉害厉害，这都能看出来，找了半天

**Comment by awei922** [comment]
厉害，搞了好久

**Comment by sgt-dongyz** [comment]
我哩个擦，从上午找到下午

**Comment by ShaoZeMing** [comment]
wo cccccccccaccccccccacccc,找了半天

**Comment by hare2011** [comment]
这是故意的吗？浪费我1小时

**Comment by hare2011** [comment]
普通按照需要看的版本
https://github.com/overtrue/laravel-wechat/tree/3.1.10

**Comment by flyingPigsIsMe** [comment]
使用4.0版本的，我laravel 版本5.5的。 文档说不需要注册门面和服务提供者，但是会报错

**Comment by never615** [comment]
晕...找了好久....我改这个库了,自己写的类命名空间也都要改...
