### ISSUE TITLE
ajax 异步请求 中间件 跳转问题

### ISSUE THREAD

**Issue by cevin** [overtrue/laravel-wechat#176]
非ajax，进入需授权路由，跳转到微信授权，没问题。
但是在ajax环境中，如果当前操作需要用户进行授权，直接就GG了（JS错误，server端发生了一次跳转）

所以现在的做法是 自己再oauth之前再加一个中间件，未登录微信的先自行处理一下然后返回服务端返回一段json，json中包含有跳转路径，然后js跳转。

还有没有更好的解决办法。

**Comment by overtrue** [comment]
ajax 模式下自己解决哦。

**Comment by MrCxin** [comment]
@cevin 
oauth之前的中间件可以看下么

**Comment by cevin** [comment]
@MrCxin 
我扩展了一下，如果用户未登录并且是ajax请求输出个json，前端js根据json判定跳转到 `/passport/oauth/wechat` 携带referer作为redirect然后登录后再跳转回来。

```php
if (!auth('web')->check() && $request->ajax()) return response()->json(['code'=>'redirect','url'=>route('passport.oauth',['redirect'=>$request->server('HTTP_REFERER')])]);
```

**Comment by MrCxin** [comment]
@cevin 
感谢,原理已经明白.
ajax模式下出问题其实就是ajax请求里面不能跨域.
oauth中间件的使用需要先在后端的接口中去做跳转拿微信信息,然后去前端页面让前端来请求接口拿数据.
此时oauth中间件已经把信息写在的session中.开心的使用就好了.

**Comment by cevin** [comment]
@MrCxin 
跨域走jsonp

代码加上个 `|| $request->has('jsonp')` 也可以
