### ISSUE TITLE
配置项 use_laravel_cache 无用

### ISSUE THREAD

**Issue by yyqqing** [overtrue/laravel-wechat#177]
配置项 use_laravel_cache 无用，由于 overtrue/wechat 的 EasyWeChat\Kernel\Traits\InteractsWithCache 中 getCache 方法 判断了 $this->app instanceof ServiceContainer && $this->app['cache'] instanceof CacheInterface ，laravel 的 cache系统无法被使用。

**Comment by mingyoung** [comment]
Laravel 5.5 的 Cache 实现了 PSR-16，所以低于 5.5 的要自己实现 PSR-16 接口…

**Comment by bolechen** [comment]
这里修改的意义在哪里没看懂，`$laravelApp['cache.store']` 在 

```
 $this->app['cache'] instanceof CacheInterface
```

的情况下，一样是返回 false 的啊 @yyqqing @mingyoung @overtrue

**Comment by overtrue** [comment]
@bolechen 你的问题是什么？如果是缓存写入失败，先确定用了哪个缓存系统，Laravel 的还是 EasyWeChat 默认的，如果是 Laravel 的缓存系统，确认你的缓存引擎所依赖的环境能正确保存缓存内容，如果是 EasyWeChat 内置的文件缓存系统，确认你的缓存目录有权限写入，缓存目录参考：
https://github.com/symfony/cache/blob/master/Traits/FilesystemCommonTrait.php#L29

**Comment by bolechen** [comment]
> @bolechen 你的问题是什么？如果是缓存写入失败，先确定用了哪个缓存系统，Laravel 的还是 EasyWeChat 默认的，如果是 Laravel 的缓存系统，确认你的缓存引擎所依赖的环境能正确保存缓存内容，如果是 EasyWeChat 内置的文件缓存系统，确认你的缓存目录有权限写入，缓存目录参考：
> https://github.com/symfony/cache/blob/master/Traits/FilesystemCommonTrait.php#L29

日志里是这样

```
0: Failed to cache verify ticket. {"code":0,"message":"Failed to cache verify ticket.","file":"/home/forge/dev.dilu.co/releases/12/vendor/overtrue/wechat/src/OpenPlatform/Auth/VerifyTicket.php","line":57}
```

然后 .env 里面用的是

```
CACHE_DRIVER=memcached
```

php artinker tinker 下这样测试是正常的
```
>>> app('cache.store')->set('aaa', 'bbb')
=> true
>>> app('cache.store')->get('aaa')
=> "bbb"
```

程序里面是这样调用的

```
$open_platform = app('wechat.open_platform');
```

查了两天了，真没有发现问题在哪？:( 求超哥帮忙 @overtrue

**Comment by bolechen** [comment]
监听 VerifyTicketRefreshedListener 事件是有内容的，输出如下

```
{"AppId":"wxec96c4d4432f0763","CreateTime":"1556166882","InfoType":"component_verify_ticket","ComponentVerifyTicket":"ticket@@@pnUe2TKPlyPDEKbbzYi6Kj492w0xha2KYl_yk7B4o3iEeBtNBuZ_2rtdZgZSiYWGHfw4EhuchpRVBb7FGfF_wg"} 
```

**Comment by bolechen** [comment]
> 监听 VerifyTicketRefreshedListener 事件是有内容的，输出如下
> 
> ```
> {"AppId":"wxec96c4d4432f0763","CreateTime":"1556166882","InfoType":"component_verify_ticket","ComponentVerifyTicket":"ticket@@@pnUe2TKPlyPDEKbbzYi6Kj492w0xha2KYl_yk7B4o3iEeBtNBuZ_2rtdZgZSiYWGHfw4EhuchpRVBb7FGfF_wg"} 
> ```

 同样的环境下，tinker 下写缓存测试也是正常的哇

<img width="631" alt="image" src="https://user-images.githubusercontent.com/195015/56710117-2873bc80-6757-11e9-8bf2-cc3e0d735fdb.png">

**Comment by overtrue** [comment]
@bolechen 跟一下代码，确认 SDK 用的 laravel 的 cache

**Comment by bolechen** [comment]
> @bolechen 跟一下代码，确认 SDK 用的 laravel 的 cache

感谢超哥回复，跟了一下发现是这里有问题

https://github.com/overtrue/wechat/blob/096ed61591fc497e7834559fd14b2eaddedc2acf/src/OpenPlatform/Auth/VerifyTicket.php#L56

$cache->set($key, $value, 3600) 以后，再用 $cache->has($key) 会返回 null
$cache->set($key, $value) 不加时间是正常的

这个是啥原因啊？

<img width="701" alt="image" src="https://user-images.githubusercontent.com/195015/56714112-675d3e80-6766-11e9-99b0-ed5d7dc23038.png">

**Comment by overtrue** [comment]
你的 Laravel 什么版本

**Comment by bolechen** [comment]
> 你的 Laravel 什么版本

最新版 5.8.14

**Comment by overtrue** [comment]
```
> dd($app->verify_ticket->getCache());
```

**Comment by bolechen** [comment]
> dd($app->verify_ticket->getCache());

<img width="1130" alt="image" src="https://user-images.githubusercontent.com/195015/56714334-19950600-6767-11e9-95f2-20c270f58a2b.png">

感觉是 Laravel 的问题？我直接用 Cache 也不行

```
>>> Cache::put('aaa', 'bbb', 3600)
=> true
>>> Cache::has('aaa')
=> false
>>> Cache::put('aaa', 'bbb')
=> true
>>> Cache::has('aaa')
=> true
>>>
```

**Comment by yyqqing** [comment]
@bolechen 当 config('wechat.defaults.use_laravel_cache') 为 true 时，CacheInterface 在 laravel-wechat 的 ServiceProvider.php 中用 CacheBridge 包装 $laravelApp['cache.store'] 的方式被创建。该 bug 是判断 use_laravel_cache 时读取配置项出错，故 #178 修复了此bug

**Comment by overtrue** [comment]
@yyqqing 新版没有 Bridge 了哈

**Comment by overtrue** [comment]
@bolechen 这就奇怪了哈哈，你检查一下为啥内置都不行吧

**Comment by bolechen** [comment]
> @bolechen 这就奇怪了哈哈，你检查一下为啥内置都不行吧

查不到原因，重新部署的新服务器测试也这样，晕死了
临时把 CACHE_DRIVER 换成 redis 正常了。。。

**Comment by yyqqing** [comment]
@overtrue :D 我是基于 #178 的解答。目前我项目中还没有更新到最新版。:)

**Comment by overtrue** [comment]
@yyqqing 嗯啦，多谢！
