### ISSUE TITLE
Laravel5.5+ dev-master 小程序获取session_key错误

### ISSUE THREAD

**Issue by algery** [overtrue/laravel-wechat#181]
配置：'EasyWeChat' => Overtrue\LaravelWeChat\Facade::class,
使用：
````
$miniProgram = app('EasyWeChat')->miniProgram();
$session_key = $miniProgram->sns->getSessionKey($request->input('code'));
````

sns不存在；打印出$miniProgram,也没有看到sns，请问在dev-master中如何使用

**Comment by mingyoung** [comment]
`EasyWeChat:: miniProgram()->auth->session('your-code');`

**Comment by algery** [comment]
@mingyoung Thank you.

**Comment by algery** [comment]
@mingyoung 你好，还想问一下，支付通知在dev-master中如何调用；谢谢

**Comment by mingyoung** [comment]
https://github.com/EasyWeChat/docs/blob/master/zh-CN/payment/notify.md
