### ISSUE TITLE
请问如何设置oauth的state段？

### ISSUE THREAD

**Issue by yyqqing** [overtrue/laravel-wechat#182]
现需要通过state在回调中传递一些参数，请问如何设置oauth的state段？

**Comment by overtrue** [comment]
state 不是用来传递参数的

**Comment by yyqqing** [comment]
state 就是在 oauth 跳转中原样回传给callback的参数，为什么不能设置？

**Comment by overtrue** [comment]
@yyqqing state 是用于验证请求来源是否真实的，并不是用于传递参数用的，传递参数直接在 redirect_url 里传就可以了

**Comment by overtrue** [comment]
@yyqqing state 用于防止 csrf 攻击

**Comment by yyqqing** [comment]
我就是想在state中保存标识，用于防止csrf等非法访问的，这种不适合放在redirect_url中的，但现在没有地方可以设置它

**Comment by keke122765** [comment]
如何解决的
