### ISSUE TITLE
我使用ajax获取微信用户信息，后台重定向失败？

### ISSUE THREAD

**Issue by sowork** [overtrue/laravel-wechat#183]
我做一个SPA应用，添加wechat.oauth:snsapi_userinfo 这个中间件到api访问的路由上时，报错如下：
![image](https://user-images.githubusercontent.com/15050765/33370059-619a6f86-d531-11e7-86b9-e479ae01fd53.png)
我追踪代码到中间件OAuthAuthenticate 发现在重定向时出现了错误，有什么解决办法么
![image](https://user-images.githubusercontent.com/15050765/33370114-88a7dd70-d531-11e7-8dea-875ae77aa934.png)

**Comment by overtrue** [comment]
ajax 模式自己解决，不属于 SDK 范畴
