### ISSUE TITLE
Identifier "shakearound" is not defined.

### ISSUE THREAD

**Issue by vueadmin** [overtrue/laravel-wechat#193]
获取实例
$shakearound = $app->shakearound;

这个实例无论如何都获取不到；

$app在门店，卡券什么的都可以使用，就这个微信摇一摇；

不知道是不是还没有开放这方面的功能；

**Comment by vueadmin** [comment]
查看源码找到答案了
/vendor/overtrue/wechat/src/OfficialAccount/ShakeAround/ShakeAround.php
第38 39行代码
文档是
$shakearound = $app->shakearound;

而实际实例获取是
$shakearound = $app->shake_around;

是不是应该提交一个pr

**Comment by mingyoung** [comment]
尽管提😂
