### ISSUE TITLE
laravel5.5安装报错

### ISSUE THREAD

**Issue by hxfighting** [overtrue/laravel-wechat#194]
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Can only install one of: overtrue/socialite[2.0, 1.3.0].
    - Can only install one of: overtrue/socialite[2.0, 1.3.0].
    - Can only install one of: overtrue/socialite[2.0, 1.3.0].
    - overtrue/wechat 4.0 requires overtrue/socialite ^2.0 -> satisfiable by overtrue/socialite[2.0].
    - overtrue/laravel-wechat 4.0.0 requires overtrue/wechat ^4.0 -> satisfiable by overtrue/wechat[4.0].
    - Installation request for overtrue/laravel-wechat ~4.0 -> satisfiable by overtrue/laravel-wechat[4.0.0].
    - Installation request for overtrue/socialite (locked at 1.3.0) -> satisfiable by overtrue/socialite[1.3.0].

Installation failed, reverting ./composer.json to its original content.

请问这个怎么解决？我把 overtrue/socialite这个包删了也不行，因为我用了"overtrue/laravel-socialite": "~1.0",这个包，希望安大大能告知解决方法。

**Comment by overtrue** [comment]
```shell
$ composer require overtrue/laravel-socialite:~2.0 overtrue/laravel-wechat
```

**Comment by hxfighting** [comment]
@overtrue 
composer require overtrue/laravel-socialite:~2.0 overtrue/laravel-wechat
Using version ^4.0 for overtrue/laravel-wechat
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package overtrue/laravel-socialite ~2.0 exists as overtrue/laravel-socialite[1.0.0, 1.0.1, 1.0.2, 1.0.3, 1.1.0, dev-master] but these are rejected by your constraint.
  Problem 2
    - Can only install one of: overtrue/socialite[2.0, 1.3.0].
    - Can only install one of: overtrue/socialite[2.0, 1.3.0].
    - Can only install one of: overtrue/socialite[2.0, 1.3.0].
    - overtrue/wechat 4.0 requires overtrue/socialite ^2.0 -> satisfiable by overtrue/socialite[2.0].
    - overtrue/laravel-wechat 4.0.0 requires overtrue/wechat ^4.0 -> satisfiable by overtrue/wechat[4.0].
    - Installation request for overtrue/laravel-wechat ^4.0 -> satisfiable by overtrue/laravel-wechat[4.0.0].
    - Installation request for overtrue/socialite (locked at 1.3.0) -> satisfiable by overtrue/socialite[1.3.0].


Installation failed, reverting ./composer.json to its original content.

还是不行呢

**Comment by hxfighting** [comment]
@overtrue 
这是我的依赖
  "require": {
        "php": ">=7.0.0",
        "barryvdh/laravel-ide-helper": "^2.4",
        "fideloper/proxy": "~3.3",
        "guzzlehttp/guzzle": "^6.3",
        "jenssegers/agent": "^2.5",
        "laravel/framework": "5.5.*",
        "laravel/tinker": "~1.0",
        "laravelchen/laravel-editormd": "^2.5",
        "mercuryseries/flashy": "^1.0",
        "mews/captcha": "^2.1",
        "nesbot/carbon": "^1.22",
        "overtrue/easy-sms": "^0.0.9",
        "overtrue/laravel-socialite": "~1.0",
        "predis/predis": "^1.1",
        "watson/rememberable": "^2.0"
    },
    "require-dev": {
        "filp/whoops": "~2.0",
        "fzaninotto/faker": "~1.4",
        "mockery/mockery": "0.9.*",
        "phpunit/phpunit": "~6.0"
    },

**Comment by overtrue** [comment]
额，我知道原因了，你装了 laravel-socialite，这个包我还没发版（现在已经发了）你过一会儿更新  laravel-socialite （2.0.0）就可以了

**Comment by hxfighting** [comment]
@overtrue 
好的，谢谢，再问一个小问题，2.0的 laravel-socialite向下兼容么？

**Comment by overtrue** [comment]
@hxfighting 兼容
