### ISSUE TITLE
composer require "overtrue/laravel-wechat 安装错误

### ISSUE THREAD

**Issue by flyingPigsIsMe** [overtrue/laravel-wechat#196]
![image](https://user-images.githubusercontent.com/26251366/34136487-0efbfb80-e4a1-11e7-9295-490ed47fa78b.png)

**Comment by flyingPigsIsMe** [comment]
叫我不要安装 symfony/http-foundation

**Comment by overtrue** [comment]
试用一下 dev-master 版本，如果没啥问题的话我就发版

**Comment by flyingPigsIsMe** [comment]
原来是laravel的版本太低导致的，laravel版本刚好是5.1。然后我看文档>=5.1  以为可以。
😁
