### ISSUE TITLE
除 officialAccount 外，所有的实例调用都报 class 不存在

### ISSUE THREAD

**Issue by rocco0505** [overtrue/laravel-wechat#198]
`        $payment = app('wechat.payment');
`
或
`        $payment = \EasyWeChat::payment();
`
均报错
`Class wechat.payment does not exist`
可能有点小白，望解答。

**Comment by overtrue** [comment]
你配置呢？

**Comment by rocco0505** [comment]
一语惊醒了我……来说明一下情况，希望能帮到后来的新手们。
我的问题主要集中在两点：

1.我是3.x升级上来的，切记要删除 config 里的配置文件重新生成。
2.因为之前对微信的开发仅限于 open_id 故而没有注意到配置文件中其余部分是注释的。

以上。
最后感谢开发者，捍卫了我的不计其数个的脑细胞和游戏时间。
