### ISSUE TITLE
运行artisan tinker报ServiceProvider报错

### ISSUE THREAD

**Issue by hzw729087** [overtrue/laravel-wechat#199]
【运行环境】
php：7.1
laravel：5.5
laravel-wechat：4.0.1

【错误日志】
array_merge(): Argument #2 is not an array {"exception":"[object] (ErrorException(code: 0): array_merge(): Argument #2 is not an array at /vendor/overtrue/laravel-wechat/src/ServiceProvider.php:94)

【错误代码】
$app = new $class(array_merge(config('wechat.defaults', []), config("wechat.{$name}.{$account}")));

【发现】
config("wechat.{$name}.{$account}") = config("wechat.mini_program.default") = null
但config/wechat.php是完全按照模板配置的

【临时解决】
修改config("wechat.{$name}.{$account}") 为 config("wechat.{$name}.{$account}", [])

只有在运行artisan tinker的时候才会报该错误，其余一切正常

**Comment by niugengyun** [comment]
是的 composer update就出现了这个问题

**Comment by overtrue** [comment]
一会儿我来修

**Comment by niugengyun** [comment]
错误原因
$wechat['official_account']['default'] 不存在

因为默认配置文件是这样的
`    /*
     * 公众号
     */
    'official_account' => [
        'app_id' => env('WECHAT_OFFICIAL_ACCOUNT_APPID', 'your-app-id'),         // AppID
        'secret' => env('WECHAT_OFFICIAL_ACCOUNT_SECRET', 'your-app-secret'),    // AppSecret
        'token' => env('WECHAT_OFFICIAL_ACCOUNT_TOKEN', 'your-token'),           // Token
        'aes_key' => env('WECHAT_OFFICIAL_ACCOUNT_AES_KEY', ''),                 // EncodingAESKey

        /*
         * OAuth 配置
         *
         * only_wechat_browser: 只在微信浏览器跳转
         * scopes：公众平台（snsapi_userinfo / snsapi_base），开放平台：snsapi_login
         * callback：OAuth授权完成后的回调页地址(如果使用中间件，则随便填写。。。)
         */
        // 'oauth' => [
        //     'only_wechat_browser' => false,
        //     'scopes'   => array_map('trim', explode(',', env('WECHAT_OFFICIAL_ACCOUNT_OAUTH_SCOPES', 'snsapi_userinfo'))),
        //     'callback' => env('WECHAT_OFFICIAL_ACCOUNT_OAUTH_CALLBACK', '/examples/oauth_callback.php'),
        // ],
    ],`
