### ISSUE TITLE
建议增加一个配置，直接把缓存改成redis

### ISSUE THREAD

**Issue by vcanson** [overtrue/laravel-wechat#20]
建议laravel版本直接增加redis配置

直接修改配置就能跟laravel自带redis整合一起

**Comment by overtrue** [comment]
@vcan88 请问你指哪个版本？

**Comment by vcan88** [comment]
laravel 5.1最新版本

**Comment by overtrue** [comment]
@vcanson [overtrue/laravel-wechat](https://github.com/overtrue/laravel-wechat) 现已经适配 Laravel
