### ISSUE TITLE
composer remove 失败

### ISSUE THREAD

**Issue by Yaojiale** [overtrue/laravel-wechat#204]
我想卸载3.0版本的然后安装4.0版本的，为什么remove的时候会报这个错

![image](https://user-images.githubusercontent.com/21167327/34510297-ab6a2878-f08d-11e7-8b53-355827a828b6.png)

  
而且我也已经注释了 app.php 里面的配置了，为什么还是会报错呢

**Comment by randiciest** [comment]
所以这811行到底写的啥啊

**Comment by Yaojiale** [comment]
@randiciest laravel 5.5 的自动安装服务好像

**Comment by randiciest** [comment]
@Yaojiale 
话说你remove的时候怎么个操作流程？我的习惯是：
1. 更新 composer.json 去除 laravel-wechat 和 wechat
2. 去除引用
3. composer update
4. 更新 composer.json 加上 laravel-wechat 和 wechat 并指定版本
5. composer update

Laravel 版本同是5.5

还没遇到什么问题。

**Comment by Yaojiale** [comment]
@我就是你这样的，不过我不是composer update，我是composer remove而已，我先试试你的方法，谢谢啦

**Comment by Yaojiale** [comment]
@randiciest 谢谢你的帮助，已经可以了谢啦
