### ISSUE TITLE
企业微信无法使用

### ISSUE THREAD

**Issue by tanshiqi** [overtrue/laravel-wechat#205]
全新安装，配置好后初始化：$app =  app('wechat.work');
提示：Class 'EasyWeChat\Work\AgentFactory' not found

**Comment by tanshiqi** [comment]
找到问题了，https://github.com/overtrue/laravel-wechat/blob/ab5bb7ce34b51fe52af568dd54ab55ddacecddfd/src/ServiceProvider.php#L18

这里似乎应该是 use EasyWeChat\Work\Application as Work;

**Comment by overtrue** [comment]
多谢！
