### ISSUE TITLE
使用中间件wechat.oauth在调试工具里报错：net::ERR_BLOCKED_BY_CLIENT

### ISSUE THREAD

**Issue by yujiak** [overtrue/laravel-wechat#207]
用了wechat.oauth中间件就报：net::ERR_BLOCKED_BY_CLIENT，请问这是怎么回事呢

**Comment by renyang9876** [comment]
有代码吗？

**Comment by yujiak** [comment]
`Route::group(['middleware' => ['web','wechat.oauth']],function ($router)
{
    $router->get('user','UserController@index');

});`
控制器里只是return了个视图文件，刚核对了下文档说明，发现链接里面没有获取到appid，但是我在config/wechat.php里面已经配置了啊...
