### ISSUE TITLE
bug授权登录获取不了用户信息一直都是snsapi_base

### ISSUE THREAD

**Issue by Jackfinal** [overtrue/laravel-wechat#209]
bug授权登录获取不了用户信息一直都是snsapi_base

config/wechat.php
配置了official_account.oauth.scopes 读取不了  
发现缺少default 
\vendor\overtrue\laravel-wechat\src\Middleware\OAuthAuthenticate.php 46行
`$scopes = $scopes ?: array_get($config, $account.'.oauth.scopes', ['snsapi_base']);`

**Comment by reasonpun** [comment]
@Jackfinal 
你可以尝试下这么写：在路由中添加中间件并在参数中指定当前的 scopes
`
#在web.php中

Route::group(['middleware' => ['wechat.oauth:snsapi_userinfo']], function () {
  // ...

});`
应该就可以获取userinfo，以此类推。

**Comment by UpGod** [comment]
我的也是,只 在session('wechat.oauth_user')获取到openid和一些token
@reasonpun,写了也没有用,而且没有微信确认授权的那个页面

**Comment by overtrue** [comment]
请升级到 4.0.7 解决。
