### ISSUE TITLE
开放平台全网发布时报错： [返回Api文本消息] 失败

### ISSUE THREAD

**Issue by niugengyun** [overtrue/laravel-wechat#213]
**权限如下  只要不勾选客服消息全网发布就会通过**

<img width="581" alt="wx20180126-002757 2x" src="https://user-images.githubusercontent.com/4466086/35399757-fc3f2286-022f-11e8-80e9-00f318c73d48.png">

**开放平台报错信息如下**

<img width="588" alt="wx20180126-002814 2x" src="https://user-images.githubusercontent.com/4466086/35399758-fc840de2-022f-11e8-9429-8f10fd0c26ff.png">

**中间件 VerifyCsrfToken**

```php
    protected $except = [
        'open-platform',
        'open-platform/*',
        'wechat',
    ];
```
**消息息与事件接收URL open-platform/$APPID$/callback**
```php
   public function index()
    {
        $appId = request('appId');
        $openPlatform = $this->openPlatform;

        $miniProgram = $openPlatform->miniProgram($appId);
        $server = $miniProgram->server;

        Log::info('callback');
        $server->push(function ($message) use ($miniProgram) {
            Log::info('callbac2222k');
            Log::info($message);

            $miniProgram->customer_service->message("Hello")->to($message['FromUserName'])->send();
            return   'Success';
        });
        return $server->serve();
    }
```

**授权事件接收URL    /open-platform/notify  (这里的代码是没问题的)**
```php
 public function notify()
    {

        $openPlatform = $this->openPlatform;
        $server = $openPlatform->server;

        // 处理授权成功事件
        $server->push(function ($message) use ($openPlatform) {
            Log::info('处理授权成功事件');
            Log::info(json_encode($message));

        }, Guard::EVENT_AUTHORIZED);

        // 处理授权更新事件
        $server->push(function ($message) use ($openPlatform) {
            Log::info(json_encode($message));

            Log::info('处理授权更新事件');

        }, Guard::EVENT_UPDATE_AUTHORIZED);

        // 处理授权取消事件
        $server->push(function ($message) use ($openPlatform) {

            Log::info('处理授权取消事件');
            Log::info(json_encode($message));

        }, Guard::EVENT_UNAUTHORIZED);

        return $server->serve();
    }
```

**日志如下**

I[2018-01-26 01:13:30] production.INFO: 处理授权成功事件  
[2018-01-26 01:13:30] production.INFO: {"AppId":"wxb6dc5afa66b24d35","CreateTime":"1516900410","InfoType":"authorized","AuthorizerAppid":"wxd101a85aa106f53e","AuthorizationCode":"queryauthcode@@@dB0JS92aD7PLy18i5jouKbkHG30_aXuAwV_Jy0oU1whCmKoQ-VhyZw8wrM9Q_LHy3STovJj423Go8ACBPAd8Gw","AuthorizationCodeExpiredTime":"1516904010","PreAuthCode":"preauthcode@@@nY4fJFGVOQOXwszDpT0jGOl0DqCYIS6LkfC1jqs_aBOy4XK65gTbJHMWUAnkRJhv"}  
[2018-01-26 01:13:38] production.INFO: callback  
[2018-01-26 01:13:38] production.INFO: callbac2222k  
[2018-01-26 01:13:38] production.INFO: array (
  'ToUserName' => 'gh_8dad206e9538',
  'FromUserName' => 'oV6P70DM0-NBLoiQKb2JISwLhR80',
  'CreateTime' => '1516900418',
  'MsgType' => 'text',
  'Content' => 'QUERY_AUTH_CODE:queryauthcode@@@dB0JS92aD7PLy18i5jouKbkHG30_aXuAwV_Jy0oU1whCmKoQ-VhyZw8wrM9Q_LHy3STovJj423Go8ACBPAd8Gw',
  'MsgId' => '6515037687057539705',
)  
[2018-01-26 01:13:45] production.INFO: 处理授权取消事件  
[2018-01-26 01:13:45] production.INFO: {"AppId":"wxb6dc5afa66b24d35","CreateTime":"1516900424","InfoType":"unauthorized","AuthorizerAppid":"wxd101a85aa106f53e"}

**Comment by niugengyun** [comment]
@overtrue   希望超哥哥能在百忙之中抽时间解答下 😆

**Comment by niugengyun** [comment]
只要不处理消息就正常了   是不是消息得解密什么的？这方面的文档 官网还没完善吧? @overtrue   打扰了超哥

**Comment by mingyoung** [comment]
客服消息为什么要回复 `"Hello"`？

**Comment by mingyoung** [comment]
https://open.weixin.qq.com/cgi-bin/showdocument?action=dir_list&t=resource/res_list&verify=1&id=open1419318611&token=&lang=zh_CN

**Comment by niugengyun** [comment]
@mingyoung   看到了 谢谢。  但是在easywechat中怎么处理呢？

1）微信模推送给第三方平台方：文本消息，其中Content字段的内容固定为： QUERY_AUTH_CODE:$query_auth_code$（query_auth_code会在专用测试公众号自动授权给第三方平台方时，由微信后台推送给开发者）

2）第三方平台方拿到$query_auth_code$的值后，通过接口文档页中的“使用授权码换取公众号的授权信息”API，将$query_auth_code$的值赋值给API所需的参数authorization_code。然后，调用发送客服消息api回复文本消息给粉丝，其中文本消息的content字段设为：$query_auth_code$_from_api（其中$query_auth_code$需要替换成推送过来的query_auth_code）
