### ISSUE TITLE
3.X版本用于多个公众号是否可行？

### ISSUE THREAD

**Issue by anyforever** [overtrue/laravel-wechat#219]
目前已经在用一个服务号，想再引入一个公众号，单独配置，在使用的时候，服务号与另一个公众号，都用自己的配置初始化（
$app1= app('wechat_1');
$app2= app('wechat_2');
），这样是否会有什么问题？
服务号是全功能，登陆等这类的都走这里
另一个公众号只接入改菜单，接收、回复消息处理

读了源码，我看在存储access_token的时候，是用了前缀和微信的app_id，应该是各自不冲突的，是否还会有其它我没看到的，可能出现的问题？

**Comment by mingyoung** [comment]
没问题

**Comment by anyforever** [comment]
@mingyoung 好勒，谢谢
