### ISSUE TITLE
微信支付获取不到通知地址

### ISSUE THREAD

**Issue by jianminLee** [overtrue/laravel-wechat#228]
![tim 20180410173721](https://user-images.githubusercontent.com/13827117/38549656-1a803cc0-3ce7-11e8-935c-663d1c7d31ba.png)
![tim 20180410173746](https://user-images.githubusercontent.com/13827117/38549657-1abe85de-3ce7-11e8-807c-4984a46c3f2c.png)
![tim 20180410174450](https://user-images.githubusercontent.com/13827117/38549658-1b0d0baa-3ce7-11e8-8ed8-027f8551c6fd.png)
laravel框架版本：5.6
wechat插件版本：4.0
配置文件填写了通知地址，在调试的时候也能获取到，但是
```php
$params['notify_url'] ?? $this->app['config']['notify_url']; //这样调试就返回空了呢？
```

**Comment by overtrue** [comment]
先 dump 你的 $params['notify_url']

**Comment by jianminLee** [comment]
@overtrue  我知道问题了
![tim 20180410175459](https://user-images.githubusercontent.com/13827117/38550168-4d0eb788-3ce8-11e8-8722-fc544cbf0087.png)
zhe'l这里不能包含 notify_url 不然就坑爹

**Comment by overtrue** [comment]
@jianminLee 这里当然可以包含 notify_url 但是你要填写正确的值啊

**Comment by jianminLee** [comment]
@overtrue 因为默认值是空字符串。。。。我以为会判断空字符串然后用默认的配置通知地址。。。
没想到是isset()
