### ISSUE TITLE
开放平台代网页授权问题

### ISSUE THREAD

**Issue by RDCynthia** [overtrue/laravel-wechat#229]
开放平台代授权和调用jssdk，改怎么用啊？我看了授权的中间件，用的是official_account配置，这个应该怎么改啊？
我看了官网，开放平台的授权url参数不一样的，所以，咱们框架的中间件可以写吗？

**Comment by mingyoung** [comment]
代授权方调用 JSSDK: `$openPlatform->officialAccount('appid', 'refresh_token')->jssdk;`
OAuth 中间件暂时不支持，要自己实现

**Comment by RDCynthia** [comment]
好的，十分感谢~
