### ISSUE TITLE
通过laravel队列发消息时, 当发过一次保密消息后, 之后的消息都是保密的.

### ISSUE THREAD

**Issue by yugihuang** [overtrue/laravel-wechat#230]
laravel队列的进程一直运行,通过
```php
 app('wechat.work.应用名')->messenger  
```
获取的\EasyWeChat\Work\Message\Messenger为同一个实例.
当设置了Messenger::secretive()后, 该实例中secretive值保持true.

请问能否增加一个unsecretive的方法, 可把secretive值改回false.

**Comment by overtrue** [comment]
已经修改完发送完会自动修改回去。

**Comment by yugihuang** [comment]
谢谢安大, 发送完改回false确实更好.
