### ISSUE TITLE
开放平台获取 component_access_token 问题

### ISSUE THREAD

**Issue by RDCynthia** [overtrue/laravel-wechat#231]
描述：
1.框架会自动处理verify_ticket，并保存到缓存名为：easywechat.open_platform.verify_ticket.{appid}
2.然后会根据ticket生成component_access_token并存入缓存，名为：easywechat.kernel.access_token.{编_码}
问题：
由于代网页授权需要component_access_token参数，所以
1.描述2中的{编_码}的源代码部分在哪？我需要获取这个值，并更新。原因如2
2.如果不更新component_access_token，是不是会造成旧的令牌无法使用？

**Comment by mingyoung** [comment]
代网页授权已经封装好了，你可以直接使用：

`$openPlatform->officialAccount('appid', 'refresh_token')->oauth;`

**Comment by mingyoung** [comment]
获取 `component_access_token`:
`$openPlatform->access_token->getToken();`

**Comment by RDCynthia** [comment]
封装的时候有一个问题感觉，授权页面会弹出两次，导致code已经被使用的错误。调用的接口Url后面应该加一个'connect_redirect' => 1，微信文档没说，但是加上确实可以。

**Comment by RDCynthia** [comment]
我写的这句代码：return $openPlatform->oauth->scopes(['snsapi_userinfo'])->redirect($request->fullUrl());
现在页面一打开，就提示code已经被使用了。。我该在哪改一下啊

**Comment by overtrue** [comment]
https://github.com/overtrue/socialite/commit/20bc0ac598aa41365c209bbe4cb5c0cf314d46b3

**Comment by RDCynthia** [comment]
十分感谢~~可以不用手写了~作者很强大！
