### ISSUE TITLE
Receiving almost empty answer from basic request

### ISSUE THREAD

**Issue by devondahon** [overtrue/laravel-wechat#233]
I've just tried  `overtrue/laravel-wechat`, however I only get this answer when openning `http://www.mywebsite.com/wechat`:

```
<xml>
    <MsgType>
        <![CDATA[ text ]]>
    </MsgType>
    <Content>
        <![CDATA[ 欢迎关注 overtrue！ ]]>
    </Content>
    <ToUserName>
        <![CDATA[ ]]>
    </ToUserName>
    <FromUserName>
        <![CDATA[ ]]>
    </FromUserName>
    <CreateTime>1523982427</CreateTime>
</xml>
```

Is it the expected answer or did I miss something ?

**Comment by overtrue** [comment]
This entrance if not for human access with browser, it is the entrance for WeChat official server push message.
