### ISSUE TITLE
Class 'Symfony\Component\Cache\Simple\FilesystemCache' not found

### ISSUE THREAD

**Issue by jianzi0307** [overtrue/laravel-wechat#238]
![image](https://user-images.githubusercontent.com/2997173/39265003-c80d1e2c-48f8-11e8-9f4e-4e6e078b5a68.png)

配置里面已经开启使用laravel的缓存系统：

```php
  'use_laravel_cache' => env('USE_LARAVEL_CACHE', true),
```

此处调用会报这个错：
```php
$officialAccount = $this->openPlatform->officialAccount($appId);
$list = $officialAccount->material->list('news', 0, 10);
```

我的laravel版本为5.2，laravel-wechat版本为4.0

**Comment by xianlinzhang** [comment]
这个问题有解决吗？

**Comment by overtrue** [comment]
```php
composer require symfony/cache:^4.0 
```

@xianlinzhang

**Comment by xianlinzhang** [comment]
> ```
> composer require symfony/cache:^4.0 
> ```
> 
> @xianlinzhang

![image](https://user-images.githubusercontent.com/30235909/142983211-51dadc77-0f04-4f10-a9cb-a317b7beaa45.png)

**Comment by overtrue** [comment]
那你就只能装 3.x 了

**Comment by xianlinzhang** [comment]
> 那你就只能装 3.x 了

/*
   * 使用 Laravel 的缓存系统
   */
  'use_laravel_cache' => true,

怎么没用？使用Laravel自己的缓存不行吗？
@overtrue

**Comment by overtrue** [comment]
@xianlinzhang https://github.com/overtrue/laravel-wechat/blob/3.x/src/ServiceProvider.php#L63 看看这里是否有成功
