### ISSUE TITLE
安装时出错

### ISSUE THREAD

**Issue by chenrenyi** [overtrue/laravel-wechat#24]
作者你好，我用composer安装时出现了以下问题，搜寻网上没有找到解决办法，请教如何解决
> ./composer.json has been updated
> Loading composer repositories with package information
> Updating dependencies (including require-dev)
> Your requirements could not be resolved to an installable set of packages.
> 
>   Problem 1
>     - Conclusion: don't install overtrue/laravel-wechat 3.0.1
>     - Conclusion: remove symfony/http-foundation v2.6.13
>     - Installation request for overtrue/laravel-wechat ~3.0 -> satisfiable by overtrue/laravel-wechat[3.0, 3.0.1].
>     - Conclusion: don't install symfony/http-foundation v2.6.13
>     - overtrue/laravel-wechat 3.0 requires overtrue/wechat ~3.0 -> satisfiable by overtrue/wechat[3.0, 3.0.1, 3.0.2, 3.0.3, 3.0.4].
>     - overtrue/wechat 3.0 requires overtrue/socialite ^1.0 -> satisfiable by overtrue/socialite[1.0.0, 1.0.1, 1.0.2, 1.0.3, 1.0.4, 1.0.5, 1.0.6, 1.0.7].
>     - overtrue/wechat 3.0.1 requires overtrue/socialite ^1.0 -> satisfiable by overtrue/socialite[1.0.0, 1.0.1, 1.0.2, 1.0.3, 1.0.4, 1.0.5, 1.0.6, 1.0.7].
>     - overtrue/wechat 3.0.2 requires overtrue/socialite >=1.0.7 -> satisfiable by overtrue/socialite[1.0.7].
>     - overtrue/wechat 3.0.3 requires overtrue/socialite >=1.0.7 -> satisfiable by overtrue/socialite[1.0.7].
>     - overtrue/wechat 3.0.4 requires overtrue/socialite >=1.0.7 -> satisfiable by overtrue/socialite[1.0.7].
>     - overtrue/socialite 1.0.0 requires symfony/http-foundation ~2.8|~2.7 -> satisfiable by symfony/http-foundation[v2.7.0, v2.7.1, v2.7.10, v2.7.2, v2.7.3, v2.7.4, v2.7.5, v2.7.6, v2.7.7, v2.7.8, v2.7.9, v2.8.0, v2.8.1, v2.8.2, v2.8.3].
>     - overtrue/socialite 1.0.1 requires symfony/http-foundation ~2.8|~2.7|~3.0 -> satisfiable by symfony/http-foundation[v2.7.0, v2.7.1, v2.7.10, v2.7.2, v2.7.3, v2.7.4, v2.7.5, v2.7.6, v2.7.7, v2.7.8, v2.7.9, v2.8.0, v2.8.1, v2.8.2, v2.8.3, v3.0.0, v3.0.1, v3.0.2, v3.0.3].
>     - overtrue/socialite 1.0.2 requires symfony/http-foundation ~2.8|~2.7|~3.0 -> satisfiable by symfony/http-foundation[v2.7.0, v2.7.1, v2.7.10, v2.7.2, v2.7.3, v2.7.4, v2.7.5, v2.7.6, v2.7.7, v2.7.8, v2.7.9, v2.8.0, v2.8.1, v2.8.2, v2.8.3, v3.0.0, v3.0.1, v3.0.2, v3.0.3].
>     - overtrue/socialite 1.0.3 requires symfony/http-foundation ~2.8|~2.7|~3.0 -> satisfiable by symfony/http-foundation[v2.7.0, v2.7.1, v2.7.10, v2.7.2, v2.7.3, v2.7.4, v2.7.5, v2.7.6, v2.7.7, v2.7.8, v2.7.9, v2.8.0, v2.8.1, v2.8.2, v2.8.3, v3.0.0, v3.0.1, v3.0.2, v3.0.3].
>     - overtrue/socialite 1.0.4 requires symfony/http-foundation ~2.8|~2.7|~3.0 -> satisfiable by symfony/http-foundation[v2.7.0, v2.7.1, v2.7.10, v2.7.2, v2.7.3, v2.7.4, v2.7.5, v2.7.6, v2.7.7, v2.7.8, v2.7.9, v2.8.0, v2.8.1, v2.8.2, v2.8.3, v3.0.0, v3.0.1, v3.0.2, v3.0.3].
>     - overtrue/socialite 1.0.5 requires symfony/http-foundation ~2.8|~2.7|~3.0 -> satisfiable by symfony/http-foundation[v2.7.0, v2.7.1, v2.7.10, v2.7.2, v2.7.3, v2.7.4, v2.7.5, v2.7.6, v2.7.7, v2.7.8, v2.7.9, v2.8.0, v2.8.1, v2.8.2, v2.8.3, v3.0.0, v3.0.1, v3.0.2, v3.0.3].
>     - overtrue/socialite 1.0.6 requires symfony/http-foundation ~2.8|~2.7|~3.0 -> satisfiable by symfony/http-foundation[v2.7.0, v2.7.1, v2.7.10, v2.7.2, v2.7.3, v2.7.4, v2.7.5, v2.7.6, v2.7.7, v2.7.8, v2.7.9, v2.8.0, v2.8.1, v2.8.2, v2.8.3, v3.0.0, v3.0.1, v3.0.2, v3.0.3].
>     - overtrue/socialite 1.0.7 requires symfony/http-foundation ~2.8|~2.7|~3.0 -> satisfiable by symfony/http-foundation[v2.7.0, v2.7.1, v2.7.10, v2.7.2, v2.7.3, v2.7.4, v2.7.5, v2.7.6, v2.7.7, v2.7.8, v2.7.9, v2.8.0, v2.8.1, v2.8.2, v2.8.3, v3.0.0, v3.0.1, v3.0.2, v3.0.3].
>     - Can only install one of: symfony/http-foundation[v2.7.0, v2.6.13].
>     - Can only install one of: symfony/http-foundation[v2.7.1, v2.6.13].
>     - Can only install one of: symfony/http-foundation[v2.7.10, v2.6.13].
>     - Can only install one of: symfony/http-foundation[v2.7.2, v2.6.13].
>     - Can only install one of: symfony/http-foundation[v2.7.3, v2.6.13].
>     - Can only install one of: symfony/http-foundation[v2.7.4, v2.6.13].
>     - Can only install one of: symfony/http-foundation[v2.7.5, v2.6.13].
>     - Can only install one of: symfony/http-foundation[v2.7.6, v2.6.13].
>     - Can only install one of: symfony/http-foundation[v2.7.7, v2.6.13].
>     - Can only install one of: symfony/http-foundation[v2.7.8, v2.6.13].
>     - Can only install one of: symfony/http-foundation[v2.7.9, v2.6.13].
>     - Can only install one of: symfony/http-foundation[v2.8.0, v2.6.13].
>     - Can only install one of: symfony/http-foundation[v2.8.1, v2.6.13].
>     - Can only install one of: symfony/http-foundation[v2.8.2, v2.6.13].
>     - Can only install one of: symfony/http-foundation[v2.8.3, v2.6.13].
>     - Can only install one of: symfony/http-foundation[v3.0.0, v2.6.13].
>     - Can only install one of: symfony/http-foundation[v3.0.1, v2.6.13].
>     - Can only install one of: symfony/http-foundation[v3.0.2, v2.6.13].
>     - Can only install one of: symfony/http-foundation[v3.0.3, v2.6.13].
>     - Installation request for symfony/http-foundation == 2.6.13.0 -> satisfiable by symfony/http-foundation[v2.6.13].

**Comment by overtrue** [comment]
@chenrenyi 你用的 Laravel 什么版本啊？

**Comment by chenrenyi** [comment]
@overtrue laravel5.0版本。上面的报错信息是composer require时出现的
