### ISSUE TITLE
Authorize Failed: {"errcode":40029,"errmsg":"invalid code

### ISSUE THREAD

**Issue by cnbeir** [overtrue/laravel-wechat#242]
使用的是路由中间件，95%的用户都是正常的，但是有小部分用户授权我非常有问题，困扰好几天了

路由配置：

`//微信授权组
Route::group(['middleware' => ['web', 'wechat.oauth:default,snsapi_userinfo']], function () {
    //微信授权登录
    Route::get('/wechat/auth', 'WechatController@oauth');
});`

操作：

微信中访问 /wechat/auth 正常打开授权页面，点击确认授权后，php这边报了下面的错误

错误日志：
` production.ERROR: Authorize Failed: {"errcode":40029,"errmsg":"invalid code, hints: [ req_id: ch6VSa0585th50 ]"} {"exception":"[object] (Overtrue\\Socialite\\AuthorizeFailedException(code: -1): Authorize Failed: {\"errcode\":40029,\"errmsg\":\"invalid code, hints: [ req_id: ch6VSa0585th50 ]\"} at /mnt/www/wwwroot/newapi.baochequan.cn/baochequan/vendor/overtrue/socialite/src/Providers/AbstractProvider.php:446)
[stacktrace]
#0 /mnt/www/wwwroot/newapi.baochequan.cn/baochequan/vendor/overtrue/socialite/src/Providers/WeChatProvider.php(103): Overtrue\\Socialite\\Providers\\AbstractProvider->parseAccessToken(Array)
#1 /mnt/www/wwwroot/newapi.baochequan.cn/baochequan/vendor/overtrue/socialite/src/Providers/AbstractProvider.php(192): `

**Comment by overtrue** [comment]
也许是他们打开了旧的地址，所以应该是正常的

**Comment by cnbeir** [comment]
感谢神速回复，旧的地址是指？用户都是新用户

**Comment by overtrue** [comment]
比如用户在授权完，点返回之类的动作，就会回到旧的那个地址嘛，相当于用旧的 code 再访问一次了，应该是没问题的。

**Comment by cnbeir** [comment]
这个/wechat/auth的入口我们是放在公众号的菜单里面的，用户没有点击返回的操作，php用session('wechat.oauth_user')和session('wechat.oauth_user.default') 都获取不到用户信息

**Comment by overtrue** [comment]
1: `wechat/auth` -> 2: `OAuth 授权页` -> 3: `wechat/auth?code=xxxx` -> 4: `wechat/auth(无 code)`  

如果从第4步点返回就会到第3步对吧，那么 code 已经在正常流程用过一次了，所以点返回是不是就用了旧的 code?

**Comment by cnbeir** [comment]
那是不是我路由不能这么配置。。

**Comment by cnbeir** [comment]
现在的情况是这部分报错的用户，无法授权成功，我用session取不到用户数据

**Comment by overtrue** [comment]
@cnbeir 麻烦贴一下：

`composer info overtrue/socialite` 的结果

**Comment by cnbeir** [comment]
`name     : overtrue/socialite
descrip. : A collection of OAuth 2 packages that extracts from laravel/socialite.
keywords : login, oauth, qq, social, wechat, weibo
versions : * 2.0.2
type     : library
license  : MIT License (MIT) (OSI approved) https://spdx.org/licenses/MIT.html#licenseText
source   : [git] https://github.com/overtrue/socialite.git 4a8677a9afed57654f1aa55eff2a2de5bbd8e1bc
dist     : [zip] https://files.phpcomposer.com/files/overtrue/socialite/4a8677a9afed57654f1aa55eff2a2de5bbd8e1bc.zip 4a8677a9afed57654f1aa55eff2a2de5bbd8e1bc
names    : overtrue/socialite

autoload
psr-4
Overtrue\Socialite\ => src/

requires
guzzlehttp/guzzle ~5.0|~6.0
php >=7.0
symfony/http-foundation ^2.7|^3.0|^4.0

requires (dev)
mockery/mockery ~0.9
phpunit/phpunit ~4.0`

**Comment by overtrue** [comment]
升级到 2.0.3 试试

**Comment by overtrue** [comment]
https://github.com/overtrue/socialite/compare/2.0.3...master

**Comment by cnbeir** [comment]
好的，测试后再来反馈结果

**Comment by overtrue** [comment]
@cnbeir 这。。。如果你发现原因欢迎贡献代码。

**Comment by hufeng903** [comment]
页面授权的时候，也遇到类似的问题
local.ERROR: exception 'Overtrue\Socialite\AuthorizeFailedException' with message 'Authorize Failed: {"errcode":40163,"errmsg":"code been used, hints: [ req_id: sXdx0a0995th19 ]"}' in /var/www/html/XXXXXXX/vendor/overtrue/socialite/src/Providers/AbstractProvider.php:439

**Comment by serrt** [comment]
网上说是**301重定向**的问题, 中间件在重定向到微信的时候是**301重定向**

**Comment by overtrue** [comment]
@serrt 并没有301跳转

**Comment by qskane** [comment]
我的情况是因为我自己的url中包含一个自己系统的code参数导致这个报错，类似这种 `https://example.com/wechat/auth?code=my_code`

**Comment by kalepan** [comment]
这个问题也困扰了我好久了.
我的功能是微信扫码走H5支付.需要拿snsapi_userinfo
今天有个发现.  发现这些报错的访问大概率不是正常用户.而是腾讯自己发来的.
今天夜里3点多有一个用户完成支付操作. 
然后在6点多有个IP使用了相同CODE再次访问URL.   我又查了下其他报错的.发现来源都是腾讯云数据中心
这种在哪里能限制他. 他明显就不是一个正常的用户. 
不太明白他为什么这样
