### ISSUE TITLE
如何从数据库中读取配置？

### ISSUE THREAD

**Issue by BI7PRK** [overtrue/laravel-wechat#243]
抱歉，刚刚接触 PHP 和 Laravel。
请问，如何将配置信息（$config->official_account）从数据中读取？
并且如何创建 一个全局单例的 (officialAccount) 对象？
请行家指教一下具体步骤。谢谢啦。

**Comment by overtrue** [comment]
数据库的使用：http://www.runoob.com/mysql/mysql-tutorial.html
Laravel 的使用：
> https://laravel-china.org/docs/laravel/5.6

Laravel 单例：https://laravel-china.org/docs/laravel/5.6/container

**Comment by overtrue** [comment]
@BI7PRK 每个项目的使用场景都不一样的，你怎么用起来方便就怎么存，这东西没有那么死板的，按自己最喜欢的方式来就好了。
