### ISSUE TITLE
composer require "overtrue/wechat:~4.0"  后提示

### ISSUE THREAD

**Issue by xiearthur** [overtrue/laravel-wechat#245]
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - overtrue/laravel-wechat 3.1.10 requires overtrue/wechat ^3.3.3 -> satisfiable by overtrue/wechat[3.3.x-dev].
    - overtrue/laravel-wechat 3.1.10 requires overtrue/wechat ^3.3.3 -> satisfiable by overtrue/wechat[3.3.x-dev].
    - Conclusion: don't install overtrue/wechat 3.3.x-dev
    - Installation request for overtrue/laravel-wechat (locked at 3.1.10) -> satisfiable by overtrue/laravel-wechat[3.1.10].

Installation failed, reverting ./composer.json to its original content.

**Comment by overtrue** [comment]
因为你已经锁定安装了 3.1.10 版本
如果你要装 4.0 ， 你也许 需要将 composer.lock 与 vendor 删除后再试试

**Comment by xiearthur** [comment]
删除vender后安装成功，是否要和原来laravel中的vender合并呢

**Comment by xiearthur** [comment]
删除vendor和lock后安装 overtrue/下 无LaravelWeChat文件
Warning: Ambiguous class resolution, "GuzzleHttp\RetryMiddleware" was found in both "/www/sddy/vendor/guzzlehttp/guzzle/src/RetryMiddleware.php" and "/www/sddy/app/Extend/GuzzleHttp/RetryMiddleware.php", the first will be used.
Warning: Ambiguous class resolution, "Psr\Http\Message\UriInterface" was found in both "/www/sddy/vendor/psr/http-message/src/UriInterface.php" and "/www/sddy/app/Extend/Psr/Http/Message/UriInterface.php", the first will be used.
Warning: Ambiguous class resolution, "Psr\Http\Message\RequestInterface" was found in both "/www/sddy/vendor/psr/http-message/src/RequestInterface.php" and "/www/sddy/app/Extend/Psr/Http/Message/RequestInterface.php", the first will be used.
Warning: Ambiguous class resolution, "Psr\Http\Message\ResponseInterface" was found in both "/www/sddy/vendor/psr/http-message/src/ResponseInterface.php" and "/www/sddy/app/Extend/Psr/Http/Message/ResponseInterface.php", the first will be used.
Warning: Ambiguous class resolution, "Psr\Http\Message\ServerRequestInterface" was found in both "/www/sddy/vendor/psr/http-message/src/ServerRequestInterface.php" and "/www/sddy/app/Extend/Psr/Http/Message/ServerRequestInterface.php", the first will be used.
Warning: Ambiguous class resolution, "Psr\Http\Message\UploadedFileInterface" was found in both "/www/sddy/vendor/psr/http-message/src/UploadedFileInterface.php" and "/www/sddy/app/Extend/Psr/Http/Message/UploadedFileInterface.php", the first will be used.
Warning: Ambiguous class resolution, "Psr\Http\Message\MessageInterface" was found in both "/www/sddy/vendor/psr/http-message/src/MessageInterface.php" and "/www/sddy/app/Extend/Psr/Http/Message/MessageInterface.php", the first will be used.
Warning: Ambiguous class resolution, "Psr\Http\Message\StreamInterface" was found in both "/www/sddy/vendor/psr/http-message/src/StreamInterface.php" and "/www/sddy/app/Extend/Psr/Http/Message/StreamInterface.php", the first will be used.
> Illuminate\Foundation\ComposerScripts::postUpdate
> php artisan optimize
PHP Warning:  PHP Startup: Unable to load dynamic library '/www/server/php/71/lib/php/extensions/no-debug-non-zts-20160303/php_fileinfo.dll' - /www/server/php/71/lib/php/extensions/no-debug-non-zts-20160303/php_fileinfo.dll: cannot open shared object file: No such file or directory in Unknown on line 0
Generating optimized class loader
The compiled services file has been removed.

**Comment by overtrue** [comment]
你需要安装 php fileinfo 拓展

**Comment by xiearthur** [comment]
已经安装

**Comment by overtrue** [comment]
>  PHP Warning: PHP Startup: Unable to load dynamic library '/www/server/php/71/lib/php/extensions/no-debug-non-zts-20160303/php_fileinfo.dll' -

**Comment by overtrue** [comment]
你的报错看是没法正常加载的，所以你的拓展应该是装得有问题。

**Comment by overtrue** [comment]
`$ php -m | grep 'fileinfo'`

**Comment by xiearthur** [comment]
是这样一种情况，不在项目目录下跑composer require "overtrue/wechat:~4.0" 没问题，
在laravel项目下跑该命令的问题

**Comment by overtrue** [comment]
因为 composer 会检查 拓展安装情况

**Comment by xiearthur** [comment]
3.0是可以正常安装的 无论是在laravel项目目录下还是不是laravel项目目录下

**Comment by overtrue** [comment]
嗯，毕竟环境要求是不一样的

**Comment by xiearthur** [comment]
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - overtrue/laravel-wechat 4.0.9 requires overtrue/wechat ^4.0 -> satisfiable by overtrue/wechat[4.0.0, 4.0.0-alpha.1, 4.0.0-alpha.2, 4.0.0-beta.1, 4.0.0-beta.2, 4.0.0-beta.3, 4.0.0-beta.4, 4.0.1, 4.0.10, 4.0.11, 4.0.12, 4.0.13, 4.0.14, 4.0.15, 4.0.16, 4.0.17, 4.0.18, 4.0.19, 4.0.2, 4.0.20, 4.0.21, 4.0.22, 4.0.23, 4.0.3, 4.0.4, 4.0.5, 4.0.6, 4.0.7, 4.0.8, 4.0.9, 4.0.x-dev] but these conflict with your requirements or minimum-stability.
    - overtrue/laravel-wechat 4.0.8 requires overtrue/wechat ^4.0 -> satisfiable by overtrue/wechat[4.0.0, 4.0.0-alpha.1, 4.0.0-alpha.2, 4.0.0-beta.1, 4.0.0-beta.2, 4.0.0-beta.3, 4.0.0-beta.4, 4.0.1, 4.0.10, 4.0.11, 4.0.12, 4.0.13, 4.0.14, 4.0.15, 4.0.16, 4.0.17, 4.0.18, 4.0.19, 4.0.2, 4.0.20, 4.0.21, 4.0.22, 4.0.23, 4.0.3, 4.0.4, 4.0.5, 4.0.6, 4.0.7, 4.0.8, 4.0.9, 4.0.x-dev] but these conflict with your requirements or minimum-stability.
    - overtrue/laravel-wechat 4.0.7 requires overtrue/wechat ^4.0 -> satisfiable by overtrue/wechat[4.0.0, 4.0.0-alpha.1, 4.0.0-alpha.2, 4.0.0-beta.1, 4.0.0-beta.2, 4.0.0-beta.3, 4.0.0-beta.4, 4.0.1, 4.0.10, 4.0.11, 4.0.12, 4.0.13, 4.0.14, 4.0.15, 4.0.16, 4.0.17, 4.0.18, 4.0.19, 4.0.2, 4.0.20, 4.0.21, 4.0.22, 4.0.23, 4.0.3, 4.0.4, 4.0.5, 4.0.6, 4.0.7, 4.0.8, 4.0.9, 4.0.x-dev] but these conflict with your requirements or minimum-stability.
    - overtrue/laravel-wechat 4.0.6 requires overtrue/wechat ^4.0 -> satisfiable by overtrue/wechat[4.0.0, 4.0.0-alpha.1, 4.0.0-alpha.2, 4.0.0-beta.1, 4.0.0-beta.2, 4.0.0-beta.3, 4.0.0-beta.4, 4.0.1, 4.0.10, 4.0.11, 4.0.12, 4.0.13, 4.0.14, 4.0.15, 4.0.16, 4.0.17, 4.0.18, 4.0.19, 4.0.2, 4.0.20, 4.0.21, 4.0.22, 4.0.23, 4.0.3, 4.0.4, 4.0.5, 4.0.6, 4.0.7, 4.0.8, 4.0.9, 4.0.x-dev] but these conflict with your requirements or minimum-stability.
    - overtrue/laravel-wechat 4.0.5 requires overtrue/wechat ^4.0 -> satisfiable by overtrue/wechat[4.0.0, 4.0.0-alpha.1, 4.0.0-alpha.2, 4.0.0-beta.1, 4.0.0-beta.2, 4.0.0-beta.3, 4.0.0-beta.4, 4.0.1, 4.0.10, 4.0.11, 4.0.12, 4.0.13, 4.0.14, 4.0.15, 4.0.16, 4.0.17, 4.0.18, 4.0.19, 4.0.2, 4.0.20, 4.0.21, 4.0.22, 4.0.23, 4.0.3, 4.0.4, 4.0.5, 4.0.6, 4.0.7, 4.0.8, 4.0.9, 4.0.x-dev] but these conflict with your requirements or minimum-stability.
    - overtrue/laravel-wechat 4.0.4 requires overtrue/wechat ^4.0 -> satisfiable by overtrue/wechat[4.0.0, 4.0.0-alpha.1, 4.0.0-alpha.2, 4.0.0-beta.1, 4.0.0-beta.2, 4.0.0-beta.3, 4.0.0-beta.4, 4.0.1, 4.0.10, 4.0.11, 4.0.12, 4.0.13, 4.0.14, 4.0.15, 4.0.16, 4.0.17, 4.0.18, 4.0.19, 4.0.2, 4.0.20, 4.0.21, 4.0.22, 4.0.23, 4.0.3, 4.0.4, 4.0.5, 4.0.6, 4.0.7, 4.0.8, 4.0.9, 4.0.x-dev] but these conflict with your requirements or minimum-stability.
    - overtrue/laravel-wechat 4.0.3 requires overtrue/wechat ^4.0 -> satisfiable by overtrue/wechat[4.0.0, 4.0.0-alpha.1, 4.0.0-alpha.2, 4.0.0-beta.1, 4.0.0-beta.2, 4.0.0-beta.3, 4.0.0-beta.4, 4.0.1, 4.0.10, 4.0.11, 4.0.12, 4.0.13, 4.0.14, 4.0.15, 4.0.16, 4.0.17, 4.0.18, 4.0.19, 4.0.2, 4.0.20, 4.0.21, 4.0.22, 4.0.23, 4.0.3, 4.0.4, 4.0.5, 4.0.6, 4.0.7, 4.0.8, 4.0.9, 4.0.x-dev] but these conflict with your requirements or minimum-stability.
    - overtrue/laravel-wechat 4.0.2 requires overtrue/wechat ^4.0 -> satisfiable by overtrue/wechat[4.0.0, 4.0.0-alpha.1, 4.0.0-alpha.2, 4.0.0-beta.1, 4.0.0-beta.2, 4.0.0-beta.3, 4.0.0-beta.4, 4.0.1, 4.0.10, 4.0.11, 4.0.12, 4.0.13, 4.0.14, 4.0.15, 4.0.16, 4.0.17, 4.0.18, 4.0.19, 4.0.2, 4.0.20, 4.0.21, 4.0.22, 4.0.23, 4.0.3, 4.0.4, 4.0.5, 4.0.6, 4.0.7, 4.0.8, 4.0.9, 4.0.x-dev] but these conflict with your requirements or minimum-stability.
    - overtrue/laravel-wechat 4.0.10 requires overtrue/wechat ^4.0 -> satisfiable by overtrue/wechat[4.0.0, 4.0.0-alpha.1, 4.0.0-alpha.2, 4.0.0-beta.1, 4.0.0-beta.2, 4.0.0-beta.3, 4.0.0-beta.4, 4.0.1, 4.0.10, 4.0.11, 4.0.12, 4.0.13, 4.0.14, 4.0.15, 4.0.16, 4.0.17, 4.0.18, 4.0.19, 4.0.2, 4.0.20, 4.0.21, 4.0.22, 4.0.23, 4.0.3, 4.0.4, 4.0.5, 4.0.6, 4.0.7, 4.0.8, 4.0.9, 4.0.x-dev] but these conflict with your requirements or minimum-stability.
    - overtrue/laravel-wechat 4.0.1 requires overtrue/wechat ^4.0 -> satisfiable by overtrue/wechat[4.0.0, 4.0.0-alpha.1, 4.0.0-alpha.2, 4.0.0-beta.1, 4.0.0-beta.2, 4.0.0-beta.3, 4.0.0-beta.4, 4.0.1, 4.0.10, 4.0.11, 4.0.12, 4.0.13, 4.0.14, 4.0.15, 4.0.16, 4.0.17, 4.0.18, 4.0.19, 4.0.2, 4.0.20, 4.0.21, 4.0.22, 4.0.23, 4.0.3, 4.0.4, 4.0.5, 4.0.6, 4.0.7, 4.0.8, 4.0.9, 4.0.x-dev] but these conflict with your requirements or minimum-stability.
    - overtrue/laravel-wechat 4.0.0 requires overtrue/wechat ^4.0 -> satisfiable by overtrue/wechat[4.0.0, 4.0.0-alpha.1, 4.0.0-alpha.2, 4.0.0-beta.1, 4.0.0-beta.2, 4.0.0-beta.3, 4.0.0-beta.4, 4.0.1, 4.0.10, 4.0.11, 4.0.12, 4.0.13, 4.0.14, 4.0.15, 4.0.16, 4.0.17, 4.0.18, 4.0.19, 4.0.2, 4.0.20, 4.0.21, 4.0.22, 4.0.23, 4.0.3, 4.0.4, 4.0.5, 4.0.6, 4.0.7, 4.0.8, 4.0.9, 4.0.x-dev] but these conflict with your requirements or minimum-stability.
    - Installation request for overtrue/laravel-wechat ~4.0 -> satisfiable by overtrue/laravel-wechat[4.0.0, 4.0.1, 4.0.10, 4.0.2, 4.0.3, 4.0.4, 4.0.5, 4.0.6, 4.0.7, 4.0.8, 4.0.9].


Installation failed, reverting ./composer.json to its original content.

**Comment by overtrue** [comment]
贴你的 composer.json

**Comment by xiearthur** [comment]
"name": "laravel/laravel",
    "description": "The Laravel Framework.",
    "keywords": ["framework", "laravel"],
    "license": "MIT",
    "type": "project",
    "require": {
        "php": ">=5.6.4",
        "barryvdh/laravel-ide-helper": "^2.4",
        "dingo/api": "1.0.x@dev",
        "encore/laravel-admin": "1.4.x-dev",
        "guzzlehttp/guzzle": "^6.2",
        "jaeger/querylist": "^3.2",
        "laravel/framework": "5.4.*",
        "laravel/tinker": "~1.0",
        "league/html-to-markdown": "^4.4",
        "overtrue/laravel-follow": "^1.1",
        "overtrue/wechat": "~3.1",
        "simplesoftwareio/simple-qrcode": "~1",
        "tymon/jwt-auth": "0.5.*",
        "zgldh/qiniu-laravel-storage": "^0.6.7"
    },
    "require-dev": {
        "fzaninotto/faker": "~1.4",
        "mockery/mockery": "0.9.*",
        "phpunit/phpunit": "~5.7"
    },
    "autoload": {
        "classmap": [
            "database",
            "app/Extend/AliyunMNS",
            "app/Extend/GuzzleHttp",
"app/Extend/Psr"
        ],
        "psr-4": {
            "App\\": "app/"
        }
    },
    "autoload-dev": {
        "psr-4": {
            "Tests\\": "tests/"
        }
    },
    "scripts": {
        "post-root-package-install": [
            "php -r \"file_exists('.env') || copy('.env.example', '.env');\""
        ],
        "post-create-project-cmd": [
            "php artisan key:generate"
        ],
        "post-install-cmd": [
            "Illuminate\\Foundation\\ComposerScripts::postInstall",
            "php artisan optimize"
        ],
        "post-update-cmd": [
            "Illuminate\\Foundation\\ComposerScripts::postUpdate",
            "php artisan optimize"
        ]
    },
    "config": {
        "preferred-install": "dist",
        "sort-packages": true,
        "optimize-autoloader": true
    }

**Comment by overtrue** [comment]
你要装 overtrue/laravel-wechat ，它依赖 overtrue/wechat" 的 4.0 版本，但是你的 composer.json 里写死了要 "overtrue/wechat": "~3.1" 所以肯定是装不上的，冲突了嘛。

```sh
$ composer remove overtrue/wechat -vvv
$ composer require overtrue/laravel-wechat -vvv
```

**Comment by xiearthur** [comment]
这个地方我删除过，一开始发现这个问题了，我处理一下。

**Comment by overtrue** [comment]
@xiearthur 在 composer.json 里删除是无效的，因为有 composer.lock 存在， 要想删除生效，你还得在删除后 composer update 一下才起作用。

**Comment by xiearthur** [comment]
update过。ok 我看下

**Comment by xiearthur** [comment]
thanks 已经解决
