### ISSUE TITLE
第三方平台推送事件没起作用，我已经用了各种姿势了，但就是没反应

### ISSUE THREAD

**Issue by Ecareyu** [overtrue/laravel-wechat#248]
php7.2,laravel5.6,easywechat:~4.0

EventServiceProvider.php

```php
// 公众号三方授权成功
 'Overtrue\LaravelWeChat\Events\OpenPlatform\Authorized' => [
       // 刷新微信菜单
       'App\Listeners\FreshWechatMenusListener',
 ],
```

FreshWechatMenusListener.php

```php
  /**
     * Handle the event.
     *
     * @param  Authorized  $event
     * @return void
     */
    public function handle(Authorized $event)
    {
        $appId = $event->getAuthorizerAppid();
       \Log::info('sass open platform result', ['app' => $appId, 'pre_auth_code' => $event->getPreAuthCode()]);
    }
```

路由表
![image](https://user-images.githubusercontent.com/2928867/40308268-36635852-5d38-11e8-9cf1-07e3bc08bf0e.png)

我试过`\Overtrue\LaravelWeChat\Events\OpenPlatform\Authorized`，也没有任何反应，日志啥的也不打印，感觉根本就没有触发。

难道只能类似如下自己定义controller来触发事件？
```php
use EasyWeChat\OpenPlatform\Server\Guard;
Route::post('open-platform', function () {
    $server = $openPlatform->server;
    // 处理授权成功事件，其他事件同理
    $server->push(function ($message) {
        // $message 为微信推送的通知内容，不同事件不同内容，详看微信官方文档
        // 获取授权公众号 AppId： $message['AuthorizerAppid']
        // 获取 AuthCode：$message['AuthorizationCode']
        // 然后进行业务处理，如存数据库等...
    }, Guard::EVENT_AUTHORIZED);

    return $server->serve();
});
```

**Comment by Ecareyu** [comment]
@overtrue 求大佬鼓励。

**Comment by Ecareyu** [comment]
我知道了问题了，感觉每次都会把文档里的红底字给忽略，谢谢大佬不理之恩！

**Comment by Ecareyu** [comment]
补一句问题在哪里，防止有人打我，问题在于这一句

> 如已经授权的公众号、小程序再次进行授权，而未修改已授权的权限的话，是没有相关事件推送的。

对的，好好读这一句就知道问题所在了。

**Comment by overtrue** [comment]
🤷‍♂️

**Comment by mingyoung** [comment]
🤷‍♂️

**Comment by Ecareyu** [comment]
唉，好吧，我知道错了，你们群开嘲讽也是够够的。

**Comment by overtrue** [comment]
@Ecareyu 一个男人不要那么玻璃心啦，这个表情怎么就是嘲讽了？

**Comment by overtrue** [comment]
@Ecareyu 🤣

**Comment by pengwei1986** [comment]
请问文档在哪？

**Comment by pengwei1986** [comment]
@overtrue 请问有文档吗？我授权成功了，就是接收不了授权成功的事件
 $openPlatform = app('wechat.open_platform');
            // 第三方平台接入处理
            $server = $openPlatform->server;
            // 处理授权成功事件
            $server->push(function ($event) use ($openPlatform) {
                //获取（刷新）授权公众号或小程序的接口调用凭据（令牌）
                $res = $openPlatform->handleAuthorize($event->AuthorizationCode);
                $appid2 = $res->authorization_info['authorizer_appid'];
                $refresh_token = $res->authorization_info['authorizer_refresh_token'];

                //获取授权方的帐号基本信息
                $data = $openPlatform->getAuthorizer($appid2);
                $account = Account::query()->where('appid', $appid2)->first();
                $info2 = $data['authorizer_info'];
                $info1 = $data['authorization_info'];
                if (is_null($account)) {
                    $account = Account::query()->create([
                        'appid' => $info1['authorizer_appid'],
                        'refresh_token' => $refresh_token,
                        'name' => $info2['nick_name'],
                        'head_img' => $info2['head_img'],
                        'original' => $info2['user_name'],
                        'com_main_body' => $info2['principal_name'],
                        'headimg' => $info2['qrcode_url'], //二维码
                        'status' => 1,
                        'level' => $this->getLevel($info2),
                        'type' => 0,
                        'token' => random(32),
                        'encodingaeskey' => random(43)
                    ]);
                } else {
                    $account->refresh_token = $refresh_token;
                    $account->name = $info2['nick_name'];
                    $account->type = 0;
                    $account->original = $info2['user_name'];
                    $account->level = $this->getLevel($info2);
                    $account->head_img = $info2['head_img'];
                    $account->save();
                }
            }, Guard::EVENT_AUTHORIZED);


            // 处理授权更新事件
            $server->push(function ($event) use ($openPlatform) {

            }, Guard::EVENT_UPDATE_AUTHORIZED);

            // 处理授权取消事件
            $server->push(function ($event) {
                $appid = $event->AuthorizerAppid;
                $account = Account::query()->where('appid', $appid)->first();
                if (!is_null($account)) {
                    $account->refresh_token = '';
                    $account->save();
                }
            }, Guard::EVENT_UNAUTHORIZED);

            //VerifyTicket component_verify_ticket协议推送
            $server->push(function ($event) use ($openPlatform) {
                $appid = $event->AppId;
                $ticket = $event->ComponentVerifyTicket;

                //保存component_verify_ticket协议
                Redis::set($appid . '_component_verify_ticket', $ticket);//存储起来方便后续多台服务器并发调用

                $wechatTicket = WechatTicket::query()->where('appid', $appid)->orderBy('id')->first();
                if (is_null($wechatTicket)) {
                    $wechatTicket = WechatTicket::query()->create([
                        'appid' => $appid,
                        'ticket' => $ticket,
                        'create_time' => time(),
                        'update_time' => time()
                    ]);
                } else {
                    $wechatTicket->ticket = $ticket;
                    $wechatTicket->update_time = time();
                    $wechatTicket->save();
                }
            }, Guard::EVENT_COMPONENT_VERIFY_TICKET);

            return $server->serve();

        } catch (\Exception $e) {
            if (env('APP_DEBUG')) {
                echo $e->getMessage();
            } else {
                abort(404);
            }
        }

**Comment by overtrue** [comment]
@pengwei1986 

1. 检查 nginx 日志确认微信的推送事件到达了你的服务器；
2. 查看 nginx 日志里的状态码是否为200，非 200 请对应判断问题所在；
3. 确认请求正常转发到 fpm 的服务，检查 PHP 错误日志里是否有错误；
4. 检查框架错误日志；
5. 在业务逻辑入口增加日志记录确认请求正确到达方法部分，排除被中间件或其它逻辑拦截情况。

**Comment by pengwei1986** [comment]
@overtrue 您好，不适用$server->push(function ($event)就可以接收到授权信息
