### ISSUE TITLE
jssdk 是我哪写的不对吗

### ISSUE THREAD

**Issue by dupengshenyang** [overtrue/laravel-wechat#252]
public function inspection(Request $request)
    {
        $user = session('wechat.oauth_user'); // 拿到授权用户资料

        $openId = $user['default']->id;
        $userInfo = User::where('openid',$openId)->first();
        $json = app('wechat.official_account')->jssdk->buildConfig([
            'onMenuShareTimeline',
            'onMenuShareAppMessage',
            'startRecord',
            'stopRecord',
            'playVoice',
            'chooseImage',
            'uploadImage',
            'getLocation',
            'openLocation',
            'getLocalImgData',
            'pauseVoice',
            'uploadVoice'
        ], true);
        if (empty($userInfo)) {
            $isBind = 0;
        } else {
            $isBind = 1;
        }
        return view('wechat',['openId' => $openId,'isBind' => $isBind,'json' => $json]);
    }

上面的openid可以拿到  
kernel.php代码
    protected $routeMiddleware = [
        'auth' => \Illuminate\Auth\Middleware\Authenticate::class,
        'auth.basic' => \Illuminate\Auth\Middleware\AuthenticateWithBasicAuth::class,
        'bindings' => \Illuminate\Routing\Middleware\SubstituteBindings::class,
        'can' => \Illuminate\Auth\Middleware\Authorize::class,
        'guest' => \App\Http\Middleware\RedirectIfAuthenticated::class,
        'throttle' => \Illuminate\Routing\Middleware\ThrottleRequests::class,
        'cros' => \App\Http\Middleware\CrosHttp::class,
        'wechat.oauth' => \Overtrue\LaravelWeChat\Middleware\OAuthAuthenticate::class,
    ];
}
使用的是wechat.oauth这个中间件 laravel5.5 easywechat 4.x
提示我 Class 'EasyWeChat\Kernel\MessageFormatter' not found

**Comment by overtrue** [comment]
更新版本，4.0.27有bug

dupeng <notifications@github.com>于2018年6月7日 周四上午2:00写道：
