### ISSUE TITLE
获取商户订单信息超时或商户返回httpcode非200

### ISSUE THREAD

**Issue by devondahon** [overtrue/laravel-wechat#256]
I'm following instructions given earlier by @overtrue at https://github.com/overtrue/laravel-wechat/issues/236 but I'm getting the following error message whatever I do after scanning the generated QR code:
"获取商户订单信息超时或商户返回httpcode非200"

I've read that that it should be fixed this way:
"签名错误，请仔细检查签名。"

So I double checked all signature information but everything looks fine to me.

Below is the code and configuration I'm using.

**web.php**
```
Route::any('/scanpay', 'WeChatController@scanpay');
Route::any('/scanreply', 'WeChatController@scanreply');
```

**WeChatController.php**
```
    public function scanpay()
    {
        Log::info('SCAN PAY');
        $payment = app('wechat.payment');
        $scheme = $payment->scheme('foo123');
        return view('wechat', compact('payment', 'scheme'));
    }

    public function scanreply()
    {
        Log::info('SCAN REPLY');
    }
```

**wechat.blade.php**
```
    <pre>
        {{ var_dump($scheme) }}
    </pre>

    {!! QrCode::size(200)->generate($payment, $scheme) !!}
```

WeChat configuration at
https://pay.weixin.qq.com/index.php/extend/pay_setting:
<img width="947" alt="pay_setting" src="https://user-images.githubusercontent.com/612946/41498353-06525ada-719e-11e8-886a-d71567a385d3.png">

**config/wechat.php**
<img width="1048" alt="wechat php" src="https://user-images.githubusercontent.com/612946/41498408-9630369e-719f-11e8-94da-d07aba6c9881.png">

I tried with `sandbox` set as `true` and `false`, but the result is the same.

When checking logs, it's never passing the `scanreply()` function.

Any idea what I'm doing wrong in my code ?

**Comment by overtrue** [comment]
check you nginx access log to confirm that wechat server has accessed the uri.

**Comment by devondahon** [comment]
I checked apache2 logs, I get this when scanning the QR code:
`140.207.54.75 - - [16/Jun/2018:22:04:44 +0800] "POST /scanreply HTTP/1.1" 419 2151 "-" "Mozilla/4.0"`

**Comment by overtrue** [comment]
Add a method `app/Providers/RouteServiceProvider.php`:

```php
    protected function mapThirdRoutes()
    {
        Route::namespace($this->namespace)
             ->group(base_path('routes/third.php'));
    }
```

and update the `map` method: 

```php
public function map()
    {
        $this->mapApiRoutes();

        $this->mapWebRoutes();
         
        $this->mapThirdRoutes();
    }
```

move the wechat related routes in to `app/routes/third.php`:

```php
Route::any('/scanpay', 'WeChatController@scanpay');
Route::any('/scanreply', 'WeChatController@scanreply');
```

try it again.

**Comment by devondahon** [comment]
It's working! Thanks a lot!!

**Comment by devondahon** [comment]
Sorry for re-opening, but I still need a last step to process WeChat scan payment.

After scanning the QR code, the `scanreply()` method is properly called and I get a `code_url` value like below in the `$order` array:
weixin://wxpay/bizpayurl?pr=5niGrL6

If I paste it manually from **WeChat desktop** to **WeChat phone**, I just need to "click" it in the phone to process the payment. But when scanning the QR code, I always get the message "系统繁忙".

I guess it's because I'm not returning the `code_url` properly:
```
return $order['code_url'];
```

What's the correct syntax to return it ?

```
    public function scanreply(Request $request)
    {
        Log::info('SCAN REPLY');
        $bodyContent = $request->getContent();
        $xml = simplexml_load_string($bodyContent);

        $payment = app('wechat.payment');
        $order = $payment->order->unify([
            'trade_type' => 'NATIVE',
            'notify_url' => 'http://www.***.com/scannotify',
            'body' => 'TEST',
            'detail' => 'TEST DETAILS',
            'out_trade_no' => 'MyPreOrderId129',
            'total_fee' => '101',
            'openid' => $xml->openid,
            'sign' => $xml->sign
        ]);
        Log::info($order);

        if ($order['result_code'] == 'SUCCESS') {
            Log::info('SCAN REPLY returning code_url');
            return url($order['code_url']);
        }
    }
```

**Comment by overtrue** [comment]
![image](https://user-images.githubusercontent.com/1472352/41576176-8080f52a-73b8-11e8-8b88-3e7f2e4ef4a0.png)

```php
return $order['prepay_id'];
```

**Comment by devondahon** [comment]
Returning the `prepay_id` still gives me the same error message:
> 系统繁忙

The content of `$order` is:
```
[2018-06-19 09:49:36] local.INFO: array (
  'return_code' => 'SUCCESS',
  'return_msg' => 'OK',
  'appid' => 'wxa************549',
  'mch_id' => '12******01',
  'nonce_str' => 'eY*************9Tc',
  'sign' => '009CD328*********************D42DD',
  'result_code' => 'SUCCESS',
  'prepay_id' => 'wx191****************************3957',
  'trade_type' => 'NATIVE',
  'code_url' => 'weixin://wxpay/bizpayurl?pr=1b***6u',
)
```

**Comment by overtrue** [comment]
maybe you should check the response was clean, not contains another contents.
