### ISSUE TITLE
企业微信使用OAuth2怎么根据code和state获取userinfo

### ISSUE THREAD

**Issue by ataraxia82** [overtrue/laravel-wechat#260]
根据微信开发文档，构造如下url： https://open.weixin.qq.com/connect/oauth2/authorize?appid=111111&redirect_uri=http://url&response_type=code&scope=snsapi_userinfo&agentid=111111&state=1#wechat_redirect 
微信浏览器访问时跳转为 https://url?code=_bvvLYpZasT0lke71n_PeUj6btZle8satf-Jd5-7-fk&state=1 
根据文档 应该用code换取userid，然后根据userid获取userinfo，之前没有用easywechat我就是这么做的
 _根据code获取成员信息 
请求方式：GET（HTTPS） 请求地址：https://qyapi.weixin.qq.com/cgi-bin/user/getuserinfo?access_token=ACCESS_TOKEN&code=CODE_ 

那么，请问在laravel-wechat中如何根据code、state获取userinfo呢？

**Comment by ataraxia82** [comment]
@overtrue 您好 按照您给的教程做了一遍 但还有问题 再请教一下

配置wechat.php
`    /*
     * 企业微信
     */
    'work' => [
        'operations' => [
            'corp_id' => '222222',
            'agent_id' => 111111,
            'secret'   => '111111',
            'token'   => '222222',
            'aes_key' => '333333',

            'oauth' => [
                'scopes' => ['snsapi_userinfo'],
                'callback' => ['/wechat/auth/callback/'],
            ],
         ],
    ],`

kernel.php中添加
'wechat.oauth' => \Overtrue\LaravelWeChat\Middleware\OAuthAuthenticate::class,

web.php中添加
`Route::group(['middleware' => ['web', 'wechat.oauth']], function () {
    Route::get('/wechat/user', function () {
        $user = session('wechat.oauth_user'); // 拿到授权用户资料
        dd($user);
    });
});
`
然后在微信里访问 https://url/wechat/user 的url
显示appid不能为空 错误码10012

在微信web开发者工具里访问  https://url/wechat/user 的url
显示跳转链接为
https://open.weixin.qq.com/connect/oauth2/authorize?appid=**your-app-id**&redirect_uri=http%3A%2F%2Furl%2Fwechat%2Fuser&response_type=code&scope=snsapi_base&state=a9b4c9f21dfa386c7aabd857c2627e5a&connect_redirect=1#wechat_redirect

问题点：
1、appid没有获取到
2、redirect_uri 为什么不是我原来的https？

**Comment by overtrue** [comment]
@ataraxia82 你说的企业微信哦，那不支持。。

**Comment by mingyoung** [comment]
@ataraxia82 

是不是这个？https://github.com/overtrue/socialite/blob/master/src/Providers/WeWorkProvider.php

暂时没文档，可以看源码实现一下。。
