### ISSUE TITLE
微信支付的 XXE 这边做修改了吗？貌似没有更高的版本更新啊！

### ISSUE THREAD

**Issue by duncansun94** [overtrue/laravel-wechat#262]
微信支付的 XXE 这边做修改了吗？貌似没有更高的版本更新啊！

**Comment by overtrue** [comment]
https://github.com/overtrue/wechat/releases

**Comment by duncansun94** [comment]
安哥 我还想问下 如果之前在laravel 里面已经使用了  可否用composer 去更新 还是说要去你给的地址 下载覆盖额

**Comment by overtrue** [comment]
@duncansun94 从来就没有下载一说，composer update 即可

**Comment by duncansun94** [comment]
但是wechat 的src 是包含在 laravel-wechat 的composer.josn 里面的   我的项目下的composer.json 和 lock 里面  "overtrue/laravel-wechat": "^4.0",  都是 一样的 update 更新不了  麻烦安哥解答了。

**Comment by duncansun94** [comment]
好了 谢谢安哥。
