### ISSUE TITLE
微信支付 notify_url 回调地址 支付成功够 微信没有通知 是怎么回事？

### ISSUE THREAD

**Issue by RingoBool** [overtrue/laravel-wechat#263]
控制器里的日志没有调用成功 说明微信没有调用 设置的 notify_url 是什么原因呢

**Comment by overtrue** [comment]
@RingoBool 看 nginx 日志才能证明微信没有调用，另外就是 https， 还有就是需要在微信支付那里支持白名单吧

**Comment by tony80s** [comment]
@RingoBool 我的也是没有回调  
'notify_url'         => 'https://fitclub.qissnet.com/payments/wechat-notify/'
微信商户平台 添加的也是  这个地址
postman 测试该地址也是正常的   
但是微信支付成功后  貌似就没有发起调用一样

**Comment by overtrue** [comment]
@tony80s 检查 nginx 访问日志。

**Comment by tony80s** [comment]
@overtrue 已解决 地址换成  'http://fitclub.qissnet.com/payments/wechat-notify/' 就可以了 
不知道为什不能用 https
