### ISSUE TITLE
通过wechat.oauth中间件，如何获取用户的openid等信息

### ISSUE THREAD

**Issue by OranTing** [overtrue/laravel-wechat#264]
`

Route::get('/test', function () {

    $user = session('wechat.oauth_user');

    echo  $user['id'];

    echo $user->id;

})->middleware(['wechat.oauth']);

`

我用  $user['id'] ,$user->id  为什么都获取不到呢？正确的方式是什么呢？
使用$user->getId() 也不行。

dump($user) 如下

![3511531586943_ pic_hd](https://user-images.githubusercontent.com/13476576/42726562-faea5530-87c8-11e8-8c91-70a9d1ac9002.jpg)

**Comment by OranTing** [comment]
找到问题了。
`
` $user = session('wechat.oauth_user.default');
` dd($user->getId());
`
session('wechat.oauth_user.default');  加上.default就可以使用getId()正确获取，但是不加default，只使用session('wechat.oauth_user');就会报错，这个是什么原因呢？
![3691531619816_ pic](https://user-images.githubusercontent.com/13476576/42729764-82a798ec-8815-11e8-9ede-6c7e7e023ed6.jpg)

**Comment by overtrue** [comment]
因为写入的就是 default 啊
