### ISSUE TITLE
安装第一步就失败

### ISSUE THREAD

**Issue by tony80s** [overtrue/laravel-wechat#265]
composer require "overtrue/laravel-wechat:~4.0"

Installation failed, reverting ./composer.json to its original content.
[RuntimeException]                                                                                      
  Could not scan for classes inside "app/libs/aessample" which does not appear to be a file nor a folder  

laravel  5.5
php  7.2
Composer version 1.5.1

**Comment by overtrue** [comment]
一个英文都不认识还是你根本就没去看？

```
Could not scan for classes inside "app/libs/aessample" which does not appear to be a file nor a folder
```

**Comment by tony80s** [comment]
看了  没看懂   app目录下没有libs目录啊
