### ISSUE TITLE
PHP Fatal error:  Class 'Symfony\Component\HttpFoundation\Request' not found

### ISSUE THREAD

**Issue by tony80s** [overtrue/laravel-wechat#266]
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover
PHP Fatal error:  Class 'Symfony\Component\HttpFoundation\Request' not found in /Users/lipeng/workspace/blog.box/vendor/laravel/framework/src/Illuminate/Http/Request.php on line 15

In Request.php line 15:
                                                              
  Class 'Symfony\Component\HttpFoundation\Request' not found  
                                                              

Script @php artisan package:discover handling the post-autoload-dump event returned with error code 255

Installation failed, reverting ./composer.json to its original content.
第一次接触laravel-wechat  在线等

**Comment by overtrue** [comment]
请正确安装你的项目，你的项目 vendor 是不完整的，删除 vendor 重新 composer install 一次
