### ISSUE TITLE
DecryptData sometimes throw 500 error?

### ISSUE THREAD

**Issue by stone009** [overtrue/laravel-wechat#269]
There is an error threw when i use ```decryptData``` function to get use's phonenumber in mini program, and here is my code:
Document [https://developers.weixin.qq.com/miniprogram/dev/api/signature.html#wxchecksessionobject](url)
```
$code = $request->code;
$encryptedData = $request->encryptedData;
$iv = $request->iv;
$miniProgram = \EasyWeChat::miniProgram();
$data = $miniProgram->auth->session($code);
if (isset($data['errcode'])) {
   return $this->response->errorUnauthorized('code invalid');
}
$session_key = $data['session_key'];
$result = $miniProgram->encryptor->decryptData($session_key, $iv, $encryptedData);
```
And the strange thing is sometimes it worked fine, but sometimes were threw an error: ```The given payload is invalid.``` It seems not very stable.

![image](https://user-images.githubusercontent.com/25975586/43987354-dc1ad6fe-9d51-11e8-9722-6b5092da319d.png)

How can i solve it?

Development environment:
PHP Version: 7.2
Laravel Version: 5.6
overtrue/laravel-wechat: ~4.0

**Comment by overtrue** [comment]
确保你的小程序部分的 session key 还在有效期就好了。
