### ISSUE TITLE
几台服务器公用access_token

### ISSUE THREAD

**Issue by dptobat** [overtrue/laravel-wechat#272]
将access_token中，有没有办法可以自己对redis的access_token进行设置以及读取，是否可以统一做管理

**Comment by overtrue** [comment]
当然可以啊，自定义缓存了，缓存类都是你自己写的，你爱怎么样操作都可以啊。

https://www.easywechat.com/docs/master/zh-CN/customize/cache

**Comment by dptobat** [comment]
好的，谢谢了，是可以自己设置access_token的值的，对吧
