### ISSUE TITLE
消息解密出现 The given payload is invalid.

### ISSUE THREAD

**Issue by hankin-h-k** [overtrue/laravel-wechat#278]
EasyWeChat\Kernel\Exceptions\DecryptException
The given payload is invalid.

$user_info = $mp->encryptor->decryptData($session_key, $request->iv, $request->encryptedData);
EasyWechat 小程序解密消息 有时会出现The given payload is invalid. 数据无效，请教有没有什么解决办法？

**Comment by overtrue** [comment]
https://github.com/overtrue/wechat/issues/1312
