### ISSUE TITLE
dingoapi，前后端分离的情况下，地址返回问题

### ISSUE THREAD

**Issue by ljyljy0211** [overtrue/laravel-wechat#279]
微信公众号认证，前后端分离
1、登录，后台
            $response = $app->oauth->scopes(['snsapi_userinfo'])
                            ->setRequest($request)
                            ->redirect();
            return $response;
会直接跳转
2、怎么返回这个生成的链接，通过给前端来进行跳转

**Comment by mingyoung** [comment]
getTargetUrl()
