### ISSUE TITLE
QR扫码支付获得qr码的方式

### ISSUE THREAD

**Issue by fzhan** [overtrue/laravel-wechat#28]
非常棒的插件！已打赏！

我在更新2.x 到3.x的过程中，没有发现扫码支付中获得qr码的方式，您的schema已经准备好了，但是没有办法获得图片。请问这里是需要用第三方插件再次生成对吗？

https://easywechat.org/docs/zh-cn/payment.html#u751F_u6210_u5171_u4EAB_u6536_u8D27_u5730_u5740_JS__u914D_u7F6E
文档中也未体现获得qr码链接地址函数。

**Comment by overtrue** [comment]
@fzhan 对的，因为考虑到不同的生成需求，有的喜欢用js在客户端生成，有的想要加个logo,等。所以就自己选择喜欢的第三方库来生成了。
