### ISSUE TITLE
该公众号提供的服务出现故障

### ISSUE THREAD

**Issue by zengonly** [overtrue/laravel-wechat#281]
按手册配置，微信平台tocken校验成功，但却始终无法收到微信消息，nginx访问日志有收到请求，路由无法收到请求，服务器是nginx https，最终发现，再微信官方配置的时候填写的是http:// 改为https:// 一切正常了。不知道laravel哪个中间件拦截了请求，还是nginx反向代理的时候某些头信息没传，才导致了这种问题。。。thinkjs中间件好歹有个日志记录，laravel没有吗，比如csrf中间件拦截，可以开发时配置下日志，方便调试。感谢老大的sdk，就为了这sdk从node跑到php来了

**Comment by overtrue** [comment]
微信已经声明过不再支持 http 大半年了
