### ISSUE TITLE
enable_mock为什么删除了

### ISSUE THREAD

**Issue by hawkefly** [overtrue/laravel-wechat#282]
以前有个enable_mock挺好用的，发现这个功能删除了，想知道这是为什么。

**Comment by overtrue** [comment]
很多人找我建议，但是满足不了各自的定制化效果，所以把定制权力交给大家，你可以自行按 readme 去创建 mock 资料

**Comment by overtrue** [comment]
https://github.com/overtrue/laravel-wechat#%E6%A8%A1%E6%8B%9F%E6%8E%88%E6%9D%83

**Comment by hawkefly** [comment]
明白，谢谢
