### ISSUE TITLE
使用中间件获取的用户信息为空

### ISSUE THREAD

**Issue by muzilong** [overtrue/laravel-wechat#283]
如图：
![img_2518](https://user-images.githubusercontent.com/9568149/49128808-01c86b80-f308-11e8-8e31-cb6ab20b4c0f.PNG)

使用正常的授权，可以得到用户的信息 $app->oauth->scopes，如图
![img_2520](https://user-images.githubusercontent.com/9568149/49128964-a185f980-f308-11e8-8afc-c59ffffd20ab.PNG)

求助..

**Comment by muzilong** [comment]
中间件设置的为   
![screen shot 2018-11-28 at 12 43 35 pm](https://user-images.githubusercontent.com/9568149/49129681-a4ceb480-f30b-11e8-806f-e4da8da68060.png)

scope没有使用 snsapi_userinfo
![img_2523](https://user-images.githubusercontent.com/9568149/49129762-0000a700-f30c-11e8-91d5-810541f4a96c.PNG)

中间件好像没有起作用...

**Comment by zhouribin** [comment]
> 中间件设置的为
> ![screen shot 2018-11-28 at 12 43 35 pm](https://user-images.githubusercontent.com/9568149/49129681-a4ceb480-f30b-11e8-806f-e4da8da68060.png)
> 
> scope没有使用 snsapi_userinfo
> ![img_2523](https://user-images.githubusercontent.com/9568149/49129762-0000a700-f30c-11e8-91d5-810541f4a96c.PNG)
> 
> 中间件好像没有起作用...

怎么解决的?我和你一样的问题
