### ISSUE TITLE
有计划改成从数据库读取配置吗？

### ISSUE THREAD

**Issue by bolechen** [overtrue/laravel-wechat#284]
公司要做一套 saas 系统，选择了这个类库，商户配置这块，我看到目前是写死的，也没办法注入，不想直接用 easywechat 想问下，有没有计划把配置读取这块改灵活一点。

感谢！

**Comment by overtrue** [comment]
自己读取出来手动实例化服务类就好了：https://github.com/overtrue/wechat

**Comment by bolechen** [comment]
> 自己读取出来手动实例化服务类就好了：https://github.com/overtrue/wechat

用了 overtrue/wechat 自己实现了，感谢回复
