### ISSUE TITLE
这里的appid无法通过调用时自定义吗？

### ISSUE THREAD

**Issue by zengonly** [overtrue/laravel-wechat#285]
![image](https://user-images.githubusercontent.com/21103564/49433794-c2a98700-f7ed-11e8-95be-ca795df7e092.png)

![image](https://user-images.githubusercontent.com/21103564/49433896-fd132400-f7ed-11e8-8aa3-d1a8eff43940.png)

**Comment by overtrue** [comment]
不可以，你要自定义就自己实例化对应的服务模块：https://github.com/overtrue/wechat

**Comment by zengonly** [comment]
谢谢

**Comment by yyqqing** [comment]
@zengonly 现已支持多账户，参见 #192
