### ISSUE TITLE
Config is not loaded by default

### ISSUE THREAD

**Issue by pallmallshow** [overtrue/laravel-wechat#29]
Hello,

I'm trying to seta OAuth with WeChat on my app.
It seems the config file was not loaded, let see : 

In the OAuthAuthenticate middleware, in the handle() function, you create a new $wechat like this :

```php
$wechat = app('EasyWeChat\\Foundation\\Application');
```

But this error was thrown :
```
Unresolvable dependency resolving [Parameter #0 [ <required> $config ]] in class EasyWeChat\Foundation\Application
```

If I set the default param to empty array, and load the config file after like this : 

```php
public function __construct($config)
    {
        parent::__construct();
        $config = config('wechat');

        $this['config'] = function () use ($config) {
            return new Config($config);
        };

        if ($this['config']['debug']) {
            error_reporting(E_ALL);
        }

        $this->registerProviders();
        $this->registerBase();
        $this->initializeLogger();

        Log::debug('Current configuration:', $config);
    }
```

It works well.

PR was made : #30

**Comment by overtrue** [comment]
@pallmallshow Hi, did you forgot add the follow line to  the 'providers' section of  `config/app.php`:

```php
Overtrue\LaravelWechat\ServiceProvider::class,
```

**Comment by pallmallshow** [comment]
Hi @overtrue 
Yes I had the service provider in providers array. 
I'm on Laravel 5.2.29.

**Comment by overtrue** [comment]
@pallmallshow OK，I got it.

**Comment by overtrue** [comment]
@pallmallshow plz upgrade to version 3.0.4
