### ISSUE TITLE
Failed to cache access token.

### ISSUE THREAD

**Issue by mrchenzifan** [overtrue/laravel-wechat#290]
laravel 5.5 好像没法获取这个

**Comment by hqweiyu** [comment]
我也碰到这个问题了，依赖的overtrue/wechat回退到4.1.15试试

**Comment by luozhenyu** [comment]
我也是，很尴尬，生产系统不定时崩，还是rollback吧

**Comment by overtrue** [comment]
@1812587695 那应该就是你的缓存是真的写入不了了。

**Comment by jorycn** [comment]
overtrue/wechat  4.1.15升级4.1.17 会报错，依然遇到

**Comment by overtrue** [comment]
@jorycn 检查一下缓存目录是否真的可写入，谢谢

**Comment by asundust** [comment]
PHP 版本：7.2.4
overtrue/laravel-wechat 版本：4.0.22
overtrue/wechat 版本：4.1.17
框架名称：Laravel v5.5.44

查看了另一个问题，我和他都使用了redis缓存模式，在4.1.17下无法正常使用报错信息如下
ERROR: 0: Failed to cache access token. {"code":0,"message":"Failed to cache access token.","file":"***/vendor/overtrue/wechat/src/Kernel/AccessToken.php","line":141} 
暂时回退overtrue/wechat 到4.1.15生产环境正常了

**Comment by overtrue** [comment]
@asundust 去看一下 redis 里是否真的缓存进去了。

**Comment by asundust** [comment]
@asundust 下午花了2个多小时去查了，找到了出错点，出错原因因为时间关系没有查。希望给大家一点帮助吧。
这有个人和我的情况很类似
 [https://www.jianshu.com/p/226095ae0641](url)
在寻找的过程中发现了文档中有提到 
[https://github.com/overtrue/wechat/wiki/%E8%87%AA%E5%AE%9A%E4%B9%89%E7%BC%93%E5%AD%98](url)
在我本地Windows下开发环境下，最终生成的Access Token缓存路径为 `'directory' => 'C:\\Users\\asundust\\AppData\\Local\\Temp/ symfony-cache\\',`，Windows下是可以正常写入的，至于为什么在Linux无法正常写入还是其他情况这个点倒是没测试。
如果是权限问题的话这就证实了Windows下开发是没有问题的，而在Linux下是无权限写入才造成报错。这点你在 [https://github.com/overtrue/wechat/issues/1023#issuecomment-343834474](url)有提到过。

以下针对大众做一下解答
既然存在这个情况，以前没有出现的原因在于新版本做了判断 `vendor/overtrue/wechat/src/Kernel/AccessToken.php` 133行代码。新加了 `if (!$this->getCache()->has($this->getCacheKey())) {
            throw new RuntimeException('Failed to cache access token.');
        }`
由于自己的东西日访问次数不会超过获取access token的日上限次数，所以每次都是重新获取，但是也不会出现问题，有这个问题的小伙伴可以去看看有没有这个情况。解决方案也简单： [https://www.easywechat.com/docs/master/customize/cache](url)

**Comment by overtrue** [comment]
@asundust :+1:

**Comment by RJustice** [comment]
Laravel : 5.7.20
overtrue/laravel-wechat: 4.0.22
overtrue/wechat : 4.1.16

其中 vendor/overtrue/wechat/src/Kernel/AccessToken.php  中的 line: 135 ~ line: 145
实际在使用laravel的file缓存时, set 方法实际是没有返回的, 所以 $ok 永远都是null, 但是实际上 storage/framework/cache/data 已经有缓存内容
```php
$ok = $this->getCache()->set($this->getCacheKey(), [
            $this->tokenKey => $token,
            'expires_in' => $lifetime,
        ], $lifetime - $this->safeSeconds);
        
        if (!$ok) {
            throw new RuntimeException('Failed to cache access token.');
        }
```
所以可以注释掉 line:140 ~ line:142 , 或者 catch 一下 set 的异常.

同样 vendor/overtrue/wechat/src/BasicService/Jssdk/Client.php 中的 line: 89 ~ line: 109
```php
public function getTicket(bool $refresh = false, string $type = 'jsapi'): array
    {
        $cacheKey = sprintf('easywechat.basic_service.jssdk.ticket.%s.%s', $type, $this->getAppId());

        if (!$refresh && $this->getCache()->has($cacheKey)) {
            return $this->getCache()->get($cacheKey);
        }

        $result = $this->castResponseToType(
            $this->requestRaw($this->ticketEndpoint, 'GET', ['query' => ['type' => $type]]),
            'array'
        );

        $ok = $this->getCache()->set($cacheKey, $result, $result['expires_in'] - 500);

        if (!$ok) {
            throw new RuntimeException('Failed to cache jssdk ticket.');
        }

        return $result;
    }
```

同样注释掉判断 $ok 的部分即可. 


还有一个解决方法就是 配置文件 config/wechat.php 中 
` 'use_laravel_cache' => false,`

不需要修改内容代码

**Comment by overtrue** [comment]
@RJustice 你的代码是旧版了，已经第一时间发布了补丁版本哈。

**Comment by SuzutsukiKagami** [comment]
overtrue/wechat 4.1.16    升级到 overtrue/wechat      4.1.20 
目前可以正常执行

**Comment by sky8652** [comment]
overtrue/wechat 5.0 出现这个问题怎么解决

**Comment by xlight** [comment]
遇到这个报错，最后发现是cache默认写到 /tmp 目录，没有写权限
