### ISSUE TITLE
oauth是出现带code跳转了两次，使用的是中间件的方式

### ISSUE THREAD

**Issue by u5de6** [overtrue/laravel-wechat#291]
oauth是出现带code跳转了两次，使用的是中间件的方式，版本是4.1.17
在OAuthAuthenticate.php里加日志记录，发现带code跳转了两次，微信返回41008，是session没保存成功的缘故？

**Comment by overtrue** [comment]
@u5de6 应该是

**Comment by u5de6** [comment]
我看4.1.17版本修复了那个access_token的缓存信息，那这个是不是也要相应的调整？

**Comment by u5de6** [comment]
\Illuminate\Session\Middleware\StartSession::class
而且在web路由里是开启了session了的

**Comment by u5de6** [comment]
` OAuthAuthenticate.php 52行的代码
        $session = session($sessionKey, []);
        LogUtils::debug('1');
        LogUtils::debug(session($sessionKey));

        if (!$session) {
            if ($request->has('code')) {
                session([$sessionKey => $officialAccount->oauth->user() ?? []]);
                $isNewSession = true;

                Event::fire(new WeChatUserAuthorized(session($sessionKey), $isNewSession, $account));

                LogUtils::debug('2');
                LogUtils::debug(session($sessionKey));
                return redirect()->to($this->getTargetUrl($request));
            }

            session()->forget($sessionKey);

            return $officialAccount->oauth->scopes($scopes)->redirect($request->fullUrl());
        }`
输出的结果
`
[2019-01-13 15:40:00] debug.DEBUG: 1  
[2019-01-13 15:40:00] debug.DEBUG:   
[2019-01-13 15:40:00] debug.DEBUG: 1  
[2019-01-13 15:40:00] debug.DEBUG:   
[2019-01-13 15:40:01] debug.DEBUG: 1  
[2019-01-13 15:40:01] debug.DEBUG:   
[2019-01-13 15:40:59] debug.DEBUG: 1  
[2019-01-13 15:40:59] debug.DEBUG:
`
最后的这个15:40:59的日志，过了近一分钟之后又进来一次？

**Comment by u5de6** [comment]
嗯  我知道了情况  用的laravels
\Overtrue\LaravelWeChat\ServiceProvider::class下的这个代码不能获取到第二次请求的Request
$app['request'] = $laravelApp['request'];

每次请求重新注册下\Overtrue\LaravelWeChat\ServiceProvider::class就行了[laravels的处理](https://github.com/hhxsv5/laravel-s/blob/master/KnownIssues-CN.md)
