### ISSUE TITLE
获取商户订单信息超时或者商户返回的httpcode非200

### ISSUE THREAD

**Issue by renzhifan** [overtrue/laravel-wechat#292]
![1547721058 1](https://user-images.githubusercontent.com/29975218/51312393-275f2f00-1a86-11e9-936c-ade594c4a8eb.jpg)
![1547721134 1](https://user-images.githubusercontent.com/29975218/51312436-39d96880-1a86-11e9-8b34-fc6f37177466.jpg)
zh这里还需要别的参数吗  

我现在扫码  返回    获取商户订单信息超时或者商户返回的httpcode非200

**Comment by overtrue** [comment]
你要自己 try catch 看看异常内容哦

**Comment by renzhifan** [comment]
已经解决了   是因为统一下单  缺少参数导致的    多谢超哥的源码

**Comment by overtrue** [comment]
@renzhifan 好。
