### ISSUE TITLE
使用snsapi_userinfo授权获取用户信息的问题

### ISSUE THREAD

**Issue by yadgen** [overtrue/laravel-wechat#296]
我是通过unionid确定用户的唯一性，问题是，获取到的用户信息不是本人。
比如系统里面已经有A，B，C通过微信授权获取了基本信息。
D进来获取到A的用户信息，这种问题是什么情况导致的？

**Comment by overtrue** [comment]
你的 unionid 可能本身就存错了吧，这个我就猜不到原因了，可能性太多了。
