### ISSUE TITLE
Failed to cache access token

### ISSUE THREAD

**Issue by akrick** [overtrue/laravel-wechat#298]
ERROR: Failed to cache access token. {"exception":"[object] (EasyWeChat\\Kernel\\Exceptions\\RuntimeException(code: 0): Failed to cache access token. at /xxxx/vendor/overtrue/wechat/src/Kernel/AccessToken.php:141

当使用分布式缓存的时候，貌似不支持？！
`<?php

/*
 * This file is part of the overtrue/wechat.
 *
 * (c) overtrue <i@overtrue.me>
 *
 * This source file is subject to the MIT license that is bundled
 * with this source code in the file LICENSE.
 */

namespace EasyWeChat\Kernel\Traits;

use EasyWeChat\Kernel\ServiceContainer;
use Psr\SimpleCache\CacheInterface;
use Symfony\Component\Cache\Simple\FilesystemCache;

/**
 * Trait InteractsWithCache.
 *
 * @author overtrue <i@overtrue.me>
 */
trait InteractsWithCache
{
    /**
     * @var \Psr\SimpleCache\CacheInterface
     */
    protected $cache;

    /**
     * Get cache instance.
     *
     * @return \Psr\SimpleCache\CacheInterface
     */
    public function getCache()
    {
        if ($this->cache) {
            return $this->cache;
        }

        if (property_exists($this, 'app') && $this->app instanceof ServiceContainer
            && isset($this->app['cache']) && $this->app['cache'] instanceof CacheInterface) {
            return $this->cache = $this->app['cache'];
        }

        return $this->cache = $this->createDefaultCache();
    }

    /**
     * Set cache instance.
     *
     * @param \Psr\SimpleCache\CacheInterface $cache
     *
     * @return $this
     */
    public function setCache(CacheInterface $cache)
    {
        $this->cache = $cache;

        return $this;
    }

    /**
     * @return \Symfony\Component\Cache\Simple\FilesystemCache
     */
    protected function createDefaultCache()
    {
        return new FilesystemCache();
    }
}
`

**Comment by akrick** [comment]
加了这段貌似能解决问题 ，在没有用到分布式缓存的情况下， 或者在配置里把 'use_laravel_cache' => false, 
use Symfony\Component\Cache\Simple\RedisCache;

$predis = app('redis')->connection()->client(); // connection($name), $name 默认为 `default`
$cache = new RedisCache($predis);

$app->rebind('cache', $cache);

**Comment by bendan365** [comment]
找不到rebind函数，所以我用
use Illuminate\Support\Facades\Redis;
$redis = Redis::connection()->client();
$cache = new RedisCache($redis);
$app->cache = $cache;

**Comment by bolechen** [comment]
这个问题一直没有得到解决吗？配置文件中的 `use_laravel_cache` 并没有用

**Comment by liwei1991** [comment]
我的也是，配置文件中的 use_laravel_cache设为true,缓存文件任然在/tmp/symfony-cache
目录下 @overtrue

**Comment by overtrue** [comment]
https://github.com/overtrue/laravel-wechat/issues/319 @li
