### ISSUE TITLE
请问一下微信的测试账号出现：该公众号暂时无法提供服务，请稍后再试

### ISSUE THREAD

**Issue by raomingchao** [overtrue/laravel-wechat#3]
<?php namespace App\Http\Controllers;

use App;
use Wechat;
use Log;

class WechatController extends Controller {

    /**
     * 处理微信的请求消息
     *
     * @return string
     */
    public function serve() {

        Wechat::on('message', function ($message) {
            Log::info("收到来自'{$message['FromUserName']}'的消息：{$message['Content']}");
        });

        return Wechat::serve();

    }
}

Debug 微信请求数据：
[22/Apr/2015:10:34:03 +0800] "POST /wechat?signature=d812694d5391dd2d02b129a5947648c70c5a3aa0&timestamp=1429670043&nonce=1101729333 HTTP/1.0" "<xml><ToUserName><![CDATA[gh_e1fd4612b2f2]]></ToUserName>\x0A<FromUserName><![CDATA[ohYvKtzdxxCBlIJdZ2SBU0G8zAQ4]]></FromUserName>\x0A<CreateTime>1429670043</CreateTime>\x0A<MsgType><![CDATA[text]]></MsgType>\x0A<Content><![CDATA[\xE5\x93\x88\xE5\x93\x88\xE5\x93\x88]]></Content>\x0A<MsgId>6140386078960211765</MsgId>\x0A</xml>" 500 12378 "-" "Mozilla/4.0" - "0.070,0.138"

网上说是：
请开发者注意，一旦遇到以下情况，微信都会在公众号会话中，向用户下发系统提示“该公众号暂时无法提供服务，请稍后再试”：
1、开发者在5秒内未回复任何内容
2、开发者回复了异常数据，比如JSON数据等

请问一下不知道是否是库本身原因还是微信这边的问题呢？

**Comment by overtrue** [comment]
@raomingchao 你的框架日志应该会有报错

**Comment by raomingchao** [comment]
有的，貌似是Csrf里面有问题，这个L5刚用，之前都用4，这个也没有改过，不知道是什么原因呢？
[2015-04-22 04:29:19] local.ERROR: exception 'Illuminate\Session\TokenMismatchException' in /home/wwwroot/zmwechat/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php:46
Stack trace:
#0 /home/wwwroot/zmwechat/app/Http/Middleware/VerifyCsrfToken.php(17): Illuminate\Foundation\Http\Middleware\VerifyCsrfToken->handle(Object(Illuminate\Http\Request), Object(Closure))
#1 /home/wwwroot/zmwechat/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(125): App\Http\Middleware\VerifyCsrfToken->handle(Object(Illuminate\Http\Request), Object(Closure))
#2 /home/wwwroot/zmwechat/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(55): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#3 /home/wwwroot/zmwechat/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(125): Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#4 /home/wwwroot/zmwechat/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(61): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#5 /home/wwwroot/zmwechat/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(125): Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#6 /home/wwwroot/zmwechat/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(36): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#7 /home/wwwroot/zmwechat/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(125): Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))
#8 /home/wwwroot/zmwechat/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(40): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#9 /home/wwwroot/zmwechat/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(125): Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
#10 /home/wwwroot/zmwechat/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(42): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#11 /home/wwwroot/zmwechat/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(125): Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#12 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#13 /home/wwwroot/zmwechat/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(101): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#14 /home/wwwroot/zmwechat/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(115): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#15 /home/wwwroot/zmwechat/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(84): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#16 /home/wwwroot/zmwechat/public/index.php(53): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))

**Comment by raomingchao** [comment]
把Middleware中的Csrf注释掉就可以了，具体原因还未分析

**Comment by overtrue** [comment]
原因就是crsf拦截了

2015-04-22 13:16 GMT+08:00 Misael <notifications@github.com>:

**Comment by raomingchao** [comment]
好的，非常感谢~

**Comment by overtrue** [comment]
@raomingchao 不客气
