### ISSUE TITLE
PHP7.2版本下，count函数报错

### ISSUE THREAD

**Issue by gongjieqi** [overtrue/laravel-wechat#300]
homestead下用的是PHP7.2的版本，报了：

count(): Parameter must be an array or an object that implements Countable
--
目前暂时的解决方案是把PHP的版本切到了7.1

**Comment by overtrue** [comment]
哪行？

**Comment by gongjieqi** [comment]
看了下日志，guzzle报出来的
local.ERROR: ErrorException: count(): Parameter must be an array or an object that implements Countable in /home/vagrant/code/tmccn/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php:67

**Comment by overtrue** [comment]
升级一下 guzzle 版本吧

**Comment by coderKong** [comment]
guzzlehttp/guzzle 6.2.* 升级到 6.3.* 问题解决
