### ISSUE TITLE
Readme中OAuth中间件wechat.oauth路径有误

### ISSUE THREAD

**Issue by zhiyuanchen1991** [overtrue/laravel-wechat#302]
Readme.md中关于OAuth中间件
` 'wechat.oauth' => \Overtrue\LaravelWeChat\Middleware\OAuthAuthenticate::class,`
应该改成
` 'wechat.oauth' => \Overtrue\LaravelWechat\Middleware\OAuthAuthenticate::class,`
namespace中定义的LaravelWe**chat**是小写，而Readme中是LaravelWe**Chat**，会导致ReflectionException。

**Comment by overtrue** [comment]
https://github.com/overtrue/laravel-wechat/blob/master/src/Middleware/OAuthAuthenticate.php#L12
