### ISSUE TITLE
接收不到RAW格式的xml消息内容

### ISSUE THREAD

**Issue by g30225579** [overtrue/laravel-wechat#306]
Laravel版本：5.7
overtrue/laravel-wechat版本：4.0.23
overtrue/wechat版本：4.1.20
PHP版本：7.2

按照教程所说的方式，通过微信接口调试工具调试时，接收不到消息，代码如下：
```
$app->server->push(function($message) {
            \Log::info('push: ' . json_encode($message));
            switch($message['MsgType']) {
                case 'subscribe': return '欢迎关注公众号'; break;
                case 'text': return '收到文字消息'; break;
                default:;
    }
});
return $app->server->serve();
```

使用的是微信公众号测试号
用request()->getContent()能正常收到消息的xml内容，但使用上述代码，以及官方提供的方法getMessage()，获取到的消息体为空，请问可能是什么原因导致的呢

**Comment by overtrue** [comment]
xml 内容是从 php://input 里读取的，只允许读一次，也就是说读完一次再读就是空的了，所以测试的时候确保你只读了一次。

**Comment by g30225579** [comment]
谢谢提醒， 应该就是这个问题， 但是我看插件里使用的 request->getContent()获取，理论上没有问题，不知道是不是跟我使用了swooletw有关，我加了如下一句代码，似乎可以解决问题
```
$app = Factory::officialAccount(config('wechat.official_account.default'));
$app->rebind('request',request()); //增加这一句
```

**Comment by overtrue** [comment]
swoole 环境请自行解决问题，不提供这类非 PHP 标准环境下使用的问题解答。
