### ISSUE TITLE
wechat.oauth:snsapi_base中间件验证问题

### ISSUE THREAD

**Issue by anyforever** [overtrue/laravel-wechat#308]
之前项目中用的是V3版本（laravel 5.5），在路由中同时限了两个中间件，`->middleware(['auth', 'wechat.oauth:snsapi_base'])`，两者的关系是这样的，前面的必须登陆通过了，就可以进入，后面的如果是在微信打开可以拿用户信息，如果不是，也不限制
现在用的V4（laravel 5.8），两者的关系是，auth登陆必限，没问题。后面的拿微信信息会自动跳转到需要在微信打开才可以，而不是之前那样，不在微信打开的就不拿用户信息了

是否两个版本间这块有改动了？如果是我之前那种形式的需求，目前如何实现？

**Comment by overtrue** [comment]
判断浏览器来动态使用中间件
