### ISSUE TITLE
laravel5.8 can't generate config file

### ISSUE THREAD

**Issue by Ucer** [overtrue/laravel-wechat#309]
> php artisan vendor:publish --provider="Overtrue\LaravelWeChat\ServiceProviders"

cant't generate config file config/wechat.php

**Comment by aogg** [comment]
laravel5.5 +1

**Comment by bolechen** [comment]
`php artisan vendor:publish --provider="Overtrue\LaravelWeChat\ServiceProvider"`

Laravel 5.8.34 实则可用，注意拼写

**Comment by aogg** [comment]
> `php artisan vendor:publish --provider="Overtrue\LaravelWeChat\ServiceProvider"`
> 
> Laravel 5.8.34 实测可用，注意拼写

说来是easywechat  4.2的
