### ISSUE TITLE
关于在CSRF中排除微信路由的做法疑问

### ISSUE THREAD

**Issue by wh469012917** [overtrue/laravel-wechat#31]
看到你文档写的做微信开发的时候必须要在CSRF验证中去除微信的路由，但是这样做我在测试中发现在Laravel5.2版本中是有问题的，原因如下：
根据Laravel文档我们可以设置$excerpt属性来排除部分不需要csrf的路由，但是我实际测试发现设置了也没用。查看csrf的源码如下：
```php
public function handle($request, Closure $next)
    {
        if (
            $this->isReading($request) ||
            $this->runningUnitTests() ||
            $this->shouldPassThrough($request) ||
            $this->tokensMatch($request)
        ) {
            return $this->addCookieToResponse($request, $next($request));
        }

        throw new TokenMismatchException;
    }
```
从以上源码可以看到，if条件中四个只要满足一个就会执行这个中间件,第一个`$this->isReading`方法的源码：
```php
protected function isReading($request)
    {
        return in_array($request->method(), ['HEAD', 'GET', 'OPTIONS']);
    }
```
可以看到如果是`HEAD`,`GET`,`OPTIONS`请求方法就不会执行`$this->shouldPassThrough`这个方法来判定当前是否需要过CSRF中间件了。而且微信是GET和POST请求都有，所以我觉得在csrf中排除微信相关的路由这个做法有点不适合，你觉得呢？

**Comment by overtrue** [comment]
“ if条件中四个只要满足一个就会执行这个中间件 ” 是不对的，这个中间件永远都会执行，只是说执行后是否在检查没有token或者token不对时是否报错而已，而报错就是最后那个 ` throw new TokenMismatchException ; ` 只有走到这行才会报异常，所以你对代码的理解是错误的，那四个条件只要有一个成立就不会抛出异常。

via CloudMagic for Mac [https://cloudmagic.com/k/d/mailapp?ct=dx&cv=7.11.26&pv=10.11.5&source=email_footer_2]
On 周六, 4月 30, 2016 at 11:39 上午, 翁航 <notifications@github.com> wrote:
看到你文档写的做微信开发的时候必须要在CSRF验证中去除微信的路由，但是这样做我在测试中发现在Laravel5.2版本中是有问题的，原因如下：
根据Laravel文档我们可以设置$excerpt属性来排除部分不需要csrf的路由，但是我实际测试发现设置了也没用。查看csrf的源码如下：

publicfunctionhandle($request, Closure$next)    {if ($this->isReading($request) ||$this->runningUnitTests() ||$this->shouldPassThrough($request) ||$this->tokensMatch($request)        ) {return$this->addCookieToResponse($request, $next($request));        }thrownewTokenMismatchException;    }

从以上源码可以看到，if条件中四个只要满足一个就会执行这个中间件,第一个 $this->isReading 方法的源码：

protectedfunctionisReading($request)    {returnin_array($request->method(), ['HEAD', 'GET', 'OPTIONS']);    }

可以看到如果是 HEAD , GET , OPTIONS 请求方法就不会执行 $this->shouldPassThrough 这个方法来判定当前是否需要过CSRF中间件了。而且微信是GET和POST请求都有，所以我觉得在csrf中排除微信相关的路由这个做法有点不适合，你觉得呢？

**Comment by wh469012917** [comment]
这样子，谢谢啦！
