### ISSUE TITLE
laravel框架微信发送的Token验证失败问题

### ISSUE THREAD

**Issue by linjin101** [overtrue/laravel-wechat#318]
Token验证失败：
必须添加ob_end_clean(); //必须清空缓冲区
这样微信才能通过。。。
不知道什么原因？？？？

 public function serve()
    {
        Log::info('request arrived.'); # 注意：Log 为 Laravel 组件，所以它记的日志去 Laravel 日志看，而不是 EasyWeChat 日志

        $app = app('wechat.official_account');
        $app->server->push(function($message){
            return "欢迎关注普育吧！";
        });
        ob_end_clean(); //必须清空缓冲区
        return $app->server->serve();
    }

**Comment by chjw8016** [comment]
如果配置了laravel-debugbar，也会导致Token验证失败

**Comment by tkwong94** [comment]
> 如果配置了laravel-debugbar，也会导致Token验证失败

1. specify the env variable to disable debugbar, i.e. APP_DEBUG=true, OR 
2. add 'wechat' into the `except` array inside debugbar config file (debugbar.php)
