### ISSUE TITLE
laravel5.8 配置use_laravel_cache 无效 还是走symfony/cache

### ISSUE THREAD

**Issue by CodeMonkeyLuffy** [overtrue/laravel-wechat#319]
默认存系统目录缓存，导致无法实现多台服务器操作微信接口。

**Comment by liangmingfu** [comment]
我遇到跟你类似的问题，然后我发现使用 Factory 实例化出来的实例，跟 app() 实例化出来的实例有点不一样，大概就是在缓存这里。Factory 貌似实例化出来的总是 symfony 的 cache，我用的 redis ，发现缓存一直读取失败，就换了 app() 这种方式实例化，然后就可以了。我觉得你可以尝试一下。或者根据文档，使用 \WeChat::openPlatform() 这种方式实例化，我测试过，跟 app() 实例化的效果应该一样，因为这样子我也能使用 redis 缓存了，建议你试下。

**Comment by bolechen** [comment]
see #177

**Comment by overtrue** [comment]
@CodeMonkeyLuffy 分布式部署请使用 laravel redis cache 或者自己实现缓存驱动，比如使用 redis. 
@liangmingfu factory 实例化是 SDK 最基础的实例化方式，该方式接受配置来决定最终模块的功能，laravel-wechat 是 SDK 的高阶封装，内部实现可以查看本库的源代码，其实就是在 Factory 实例化以后替换了缓存模块为 laravel 的缓存。
