### ISSUE TITLE
服务器token验证

### ISSUE THREAD

**Issue by stevejobsii** [overtrue/laravel-wechat#32]
我的控制器：
 public function serve()
    {
        Log::info('request arrived.'); # 注意：Log 为 Laravel 组件，所以它记的日志去 Laravel 日志看，而不是 EasyWeChat 日志
        $wechat = app('wechat');
        //return $wechat;
        app('wechat')->server->setMessageHandler(function($message){
            return "欢迎关注 overtrue！";
        });
        Log::info('return response.');
        return app('wechat')->server->serve();
    }
我的route：Route::any('/weixin', 'WeixinController@serve');
我的middle：
    protected $except = [
        'weixin',
    ];
我的报告：BadRequestException in Guard.php line 317:
Invalid request.
我的日记：所有参数key，id等传输正确
腾讯验证：token验证错误

**Comment by overtrue** [comment]
```php
public function serve()
{
    Log::info('request arrived.'); 
    $server = app('wechat')->server;

    $server->setMessageHandler(function($message){
        return "欢迎关注 overtrue！";
    });
    Log::info('return response.');
    return $server->serve();
}
```

然后看日志。

**Comment by stevejobsii** [comment]
感谢！原来是routes.php的<?php前面多了个空格，谢谢！

**Comment by YangEndly** [comment]
我的也是这个问题，日志 是这样的
local	 信息	14:47:08	
return response.
local	 信息	14:47:08	
request arrived.
