### ISSUE TITLE
创建支付订单返回null

### ISSUE THREAD

**Issue by ManiuLtd** [overtrue/laravel-wechat#321]
下面是代码：
![代码](https://user-images.githubusercontent.com/36794003/61121524-04ac5100-a4d2-11e9-88fd-0c6fb1951e4e.png)

下面是执行后返回的结果：
![结果](https://user-images.githubusercontent.com/36794003/61121525-0544e780-a4d2-11e9-8325-ad873003b0c6.png)

请大佬们能给指导下，万分感激

**Comment by overtrue** [comment]
费用写成 100 试试 ？

另外你的证书地址全是没配置的？

![image](https://user-images.githubusercontent.com/1472352/61137906-ff163180-a4f8-11e9-8623-b33f68023381.png)

**Comment by ManiuLtd** [comment]
> 费用写成100试试？
> 
> 另外你的证书地址全是没配置的？
> 
> ![图片](https://user-images.githubusercontent.com/1472352/61137906-ff163180-a4f8-11e9-8623-b33f68023381.png)

大佬，创建订单我看文档上说不需要证书啊，

![001](https://user-images.githubusercontent.com/36794003/61151800-588e5880-a519-11e9-8a91-185c9de936da.png)



我把证书加上后、费用设置成100或者更大结果还是一样，下面是我的路由配置：

VerifyCsrfToken.php
```       
protected $except = [
        'wechat',
        'pay',
        'pay/store'
    ];
```

web.php
```
 Route::any('/wechat', 'Wechat\WeChatController@serve');
 Route::prefix('pay')->group(function (){
     Route::any('/store','Wechat\PayController@pay');
 });
```

微信支付平台上设置的JSAPI支付授权目录是：

> https://www.myproduct.com/pay/


下面是执行访问

> https://www.myproduct.com/pay/store 后nginx的日志记录

```
171.80.47.99 - - [13/Jul/2019:02:46:59 +0800] "GET /pay/store HTTP/1.1" 499 0 "-" "Mozilla/5.0 (iPad; CPU OS 11_2_5 like Mac OS X) AppleWebKit/604.5.6 (KHTML, like Gecko) Version/11.0 Mobile/15D60 Safari/604.1 wechatdevtools/1.02.1904090 MicroMessenger/6.7.3 webview/15629083994811177 webdebugger port/21584"
171.80.47.99 - - [13/Jul/2019:02:47:00 +0800] "GET /pay/store HTTP/1.1" 200 47528 "-" "Mozilla/5.0 (iPad; CPU OS 11_2_5 like Mac OS X) AppleWebKit/604.5.6 (KHTML, like Gecko) Version/11.0 Mobile/15D60 Safari/604.1 wechatdevtools/1.02.1904090 MicroMessenger/6.7.3 webview/15629083994811177 webdebugger port/21584"
171.80.47.99 - - [13/Jul/2019:02:47:01 +0800] "GET /favicon.ico HTTP/1.1" 200 4286 "https://www.myproduct.com/pay/store" "Mozilla/5.0 (iPad; CPU OS 11_2_5 like Mac OS X) AppleWebKit/604.5.6 (KHTML, like Gecko) Version/11.0 Mobile/15D60 Safari/604.1 wechatdevtools/1.02.1904090 MicroMessenger/6.7.3 webview/15629083994811177 webdebugger port/21584"

```

# 还望超哥百忙之中能指点一二，不胜感激

**Comment by ManiuLtd** [comment]
不知道是文档的坑还是这个5.0版本的问题，使用laravel-wechat文档中说明的和演示的
EasyWeChat::payment(); 和 app('wechat.payment'); 这两个均会返回null;
直接使用EasyWeChat文档中的Factory::payment($config)就可以了

**Comment by overtrue** [comment]
如果  `app('wechat.payment'); ` 和 `Factory::payment($config)` 不一样，证明你的 `$config` 和 `config/wechat.php` 里的配置有差别

**Comment by ManiuLtd** [comment]
感谢超哥时隔两个月的回复 😜

**Comment by overtrue** [comment]
忙忘记了

码牛科技 <notifications@github.com>于2019年9月9日 周一下午2:44写道：
