### ISSUE TITLE
图文消息好像不行

### ISSUE THREAD

**Issue by yjqxq** [overtrue/laravel-wechat#323]
图文消息提示
Class "EasyWeChat\Kernel\Messages\Message" cannot support transform to XML message.

` return new Article([
                'title'   => 'EasyWeChat',
                'author'  => 'overtrue',
                'content' => 'EasyWeChat 是一个开源的微信 SD',

            ]);`

**Comment by myischen** [comment]
解决了吗？ 我更你一样的问题 @yjqxq

**Comment by yjqxq** [comment]
> 解决了吗？ 我跟你一样的问题 @yjqxq

现在 微信图文只让发一条 通过菜单获取图文就可以了 通过菜单设置关键字回复

**Comment by myischen** [comment]
![image](https://user-images.githubusercontent.com/29190298/63843990-e8993c00-c9b9-11e9-8f5f-aec2ae2a9872.png)
出现一下错误
local.ERROR: Class "EasyWeChat\Kernel\Messages\Message" cannot support transform to XML message. {"exception":"[object] (Mockery\\Exception\\BadMethodCallException(code: 0): Class \"EasyWeChat\\Kernel\\Messages\\Message\" cannot support transform to XML message. at /home/vagrant/Code/wechat/vendor/overtrue/wechat/src/Kernel/Messages/Message.php:204)

**Comment by myischen** [comment]
明白了 这个 方法废了 @yjqxq
