### ISSUE TITLE
开放平台component_verify_ticket推送问题

### ISSUE THREAD

**Issue by zhushiqiang** [overtrue/laravel-wechat#325]
![image](https://user-images.githubusercontent.com/17295335/61918790-58647300-af85-11e9-910c-ea96d59cde7e.png)
![image](https://user-images.githubusercontent.com/17295335/61918869-a1b4c280-af85-11e9-805e-65eaf32d9406.png)

以上代码，redis中并没有存储component_verify_ticket，也没有生成wachat日志。自己记录的日志是有的

**Comment by zhushiqiang** [comment]
自己在本地测试，发现数据记录在了var/tmp/symfony-cache， 这是有什么bug吗

**Comment by overtrue** [comment]
你这种手动创建实例的需要自己实现缓存模块，https://github.com/overtrue/laravel-wechat/blob/master/src/ServiceProvider.php#L91-L93

**Comment by zhushiqiang** [comment]
好的， 明白了， 谢谢超哥
