### ISSUE TITLE
这是什么问题?

### ISSUE THREAD

**Issue by 449134904** [overtrue/laravel-wechat#326]
![image](https://user-images.githubusercontent.com/17736664/63002865-80baff80-bea9-11e9-8862-465884632c80.png)
配置文件都是对的

**Comment by 449134904** [comment]
Illegal offset type in isset or empty

**Comment by mingyoung** [comment]
PHP 版本是？

**Comment by 449134904** [comment]
7.0  laravel5.6




------------------ 原始邮件 ------------------
发件人: "张铭阳"<notifications@github.com>; 
发送时间: 2019年8月14日(星期三) 下午3:39
收件人: "overtrue/laravel-wechat"<laravel-wechat@noreply.github.com>; 
抄送: "宁静的夏天"<449134904@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [overtrue/laravel-wechat] 这是什么问题? (#326)




PHP 版本是？

**Comment by 449134904** [comment]
7.2.15 也不行

**Comment by overtrue** [comment]
其实你的提问我也看不出来什么问题，除了一句报错信息外没有任何有用的信息，报错位置。报错文件。报错行数，使用代码。https://yike.io/threads/2

**Comment by liubeibei125** [comment]
一样的问题

**Comment by liubeibei125** [comment]
![image](https://user-images.githubusercontent.com/26593443/63145817-6b6dde80-c02b-11e9-838e-a9dbc14654f0.png)

**Comment by liubeibei125** [comment]
laravel5.8  php版本7.1

**Comment by mingyoung** [comment]
composer update


liubeibei125 <notifications@github.com>于2019年8月16日 周五下午1:41写道：

**Comment by emocheng** [comment]
一样的问题，楼上的解决了吗

**Comment by 449134904** [comment]
更新这个composer require symfony/event-dispatcher:^4.3可以 但是不是处理包的问题

**Comment by 449134904** [comment]
> 
> 
> 其实你的提问我也看不出来什么问题，除了一句报错信息外没有任何有用的信息，报错位置。报错文件。报错行数，使用代码。https://yike.io/threads/2
> 
> > **[一刻 | 高品质微信开发者社区](https://yike.io/threads/2)**

![图片](https://user-images.githubusercontent.com/17736664/63156135-9f0a3200-c046-11e9-9a5b-8112d2066015.png)

**Comment by liubeibei125** [comment]
> 一样的问题，楼上的解决了吗

@449134904  这个小伙伴那个方法可以

**Comment by emocheng** [comment]
> 更新这个composer require symfony/event-dispatcher:^4.3可以 但是不是处理包的问题

厉害了！兄弟～亲测可用

**Comment by dwt11** [comment]
> 更新这个composer require symfony/event-dispatcher:^4.3可以 但是不是处理包的问题

找了三个小时才找到这里,同样的问题.  laravel5.6    overtrue/laravel-wechat4.0.23

更新了event-dispatcher:^4.3 才OK
