### ISSUE TITLE
Laravel 5.7 安装 ~4.0 报错

### ISSUE THREAD

**Issue by BboyFate** [overtrue/laravel-wechat#329]
你好，请问一下我这个是什么原因造成的呢？
[查了一下这个 warning](https://stackoverflow.com/questions/29275435/suppress-ambiguous-class-resolution-warning)
错误截图如下 ↓
![image](https://user-images.githubusercontent.com/43459833/63494833-25b08a80-c4f1-11e9-9e11-22e7cedd7a51.png)
**删 vendor 后就不再提示这个报错**
`
"scripts": {
    "pre-autoload-dump": [
        "rm -rf vendor/symfony/cache-contracts vendor/symfony/service-contracts"
    ]
}
`

**但是呢还是调用不了** 
`php artisan tinker`

报错如下 ↓
`PHP Warning:  Illegal offset type in isset or empty in /home/vagrant/Code/demo/wonder-shop/vendor/symfony/event-dispatcher/EventDispatcher.php on line 56`

截图如下 ↓
![image](https://user-images.githubusercontent.com/43459833/63495741-06b2f800-c4f3-11e9-921e-700af2ccde53.png)

**Comment by overtrue** [comment]
```
composer require overtrue/wechat:~4.2
```

**Comment by BboyFate** [comment]
> ```
> composer require overtrue/wechat:~4.2
> ```

我重新换了个镜像就好了，暂时先略过~谢谢！！
