### ISSUE TITLE
支持企业号吗？

### ISSUE THREAD

**Issue by waimanlam** [overtrue/laravel-wechat#33]
貌似企业号验证方式不一样，是否也支持？

**Comment by overtrue** [comment]
不支持企业号

Sent using CloudMagic Email [https://cloudmagic.com/k/d/mailapp?ct=pi&cv=7.11.24&pv=9.3.1&source=email_footer_2]
On 周三, 5月 25, 2016 at 7:39 下午, LinHuiMin <notifications@github.com> wrote:
貌似企业号验证方式不一样，是否也支持？
