### ISSUE TITLE
laravel6.0安装不上

### ISSUE THREAD

**Issue by allowing** [overtrue/laravel-wechat#333]
![image](https://user-images.githubusercontent.com/20262949/64306335-015eae80-cfc5-11e9-927c-a26880cd64fa.png)

**Comment by bolechen** [comment]
我这里可以

**Comment by allowing** [comment]
我这里还是不行。你的laravel也是6.0吗

**Comment by allowing** [comment]
@overtrue 大神，帮忙看看什么原因，还是装不上。我看你最后提交是兼容了laravel 6.0的，但还是提示因为版本问题。

**Comment by overtrue** [comment]
删除 lock 和 vendor 再装

silai <notifications@github.com>于2019年9月5日 周四下午2:58写道：

**Comment by allowing** [comment]
可以，安装上了。3Q
