### ISSUE TITLE
update后不读取config文件

### ISSUE THREAD

**Issue by echoyl** [overtrue/laravel-wechat#335]
今天composer更新了下 获取用户信息snsapi_userinfo，但是不会读取config下的wechat.php中的配置。微信appid SECRET什么都读到了。然后我直接修改中间件handle方法把snsapi_base改成snsapi_userinfo。暂时这样解决

**Comment by overtrue** [comment]
在 tinker 中运行：

```shell
> config('wechat');
```

**Comment by overtrue** [comment]
然后贴一下结果，把敏感内容改成 xxx 或者  ***

**Comment by echoyl** [comment]
![QQ图片20190906155759](https://user-images.githubusercontent.com/21699984/64411198-47983880-d0bf-11e9-9998-619b3a715a6e.png)
config是没问题的。
