### ISSUE TITLE
laravel6.0 安装报错

### ISSUE THREAD

**Issue by Fendy5** [overtrue/laravel-wechat#337]
Laravel6.0 安装一直报版本错误，看了一下之前有两个关于Laravel6.0的Issues，但是好像解决不了问题。

**Comment by overtrue** [comment]
麻烦再试一下:https://github.com/overtrue/wechat/releases/tag/4.2.3

**Comment by Fendy5** [comment]
> 麻烦再试一下:https://github.com/overtrue/wechat/releases/tag/4.2.3
> 
> > <img alt="" width="48" src="https://avatars1.githubusercontent.com/u/1472352?s=400&amp;v=4"><img alt="" height="14" src="https://camo.githubusercontent.com/4908d9947135e4536ef61d61512ee575f869bf6f/68747470733a2f2f6769746875622e6769746875626173736574732e636f6d2f66617669636f6e2e69636f"> GitHub**[overtrue/wechat](https://github.com/overtrue/wechat)**📦 It is probably the best SDK in the world for developing WeChat App. - overtrue/wechat

安装成功啦，嘻嘻~

**Comment by overtrue** [comment]
好的。
