### ISSUE TITLE
officialAccount的授权中间件异常有时会报错了，不同手机不同微信号打印出来的session('wechat.oauth_user')是同一个微信用户信息

### ISSUE THREAD

**Issue by jerminegao** [overtrue/laravel-wechat#339]
{"message":"Authorize Failed: {\"errcode\":41008,\"errmsg\":\"missing code, hints: [ req_id: rIeeP34ce-LwrB3 ]\"}","code":-1,"status_code":500,"debug":{"line":448,"file":"\/data\/project\/api\/vendor\/overtrue\/socialite\/src\/Providers\/AbstractProvider.php","class":"Overtrue\\Socialite\\AuthorizeFailedException","trace":["#0 \/data\/project\/api\/vendor\/overtrue\/socialite\/src\/Providers\/WeChatProvider.php(102): Overtrue\\Socialite\\Providers\\AbstractProvider->parseAccessToken(Array)","#1 \/data\/project\/api\/vendor\/overtrue\/socialite\/src\/Providers\/AbstractProvider.php(192): Overtrue\\Socialite\\Providers\\WeChatProvider->getAccessToken(NULL)","#2 \/data\/project\/api\/vendor\/overtrue\/laravel-wechat\/src\/Middleware\/OAuthAuthenticate.php(53):

**Comment by overtrue** [comment]
session 是和 cookie 关联的，不同手机不同微信号不可能用同一个 sessionid ，建议详细排查
