### ISSUE TITLE
文档服务器挂了,建议能不能弄一个离线文档呢？

### ISSUE THREAD

**Issue by roobe** [overtrue/laravel-wechat#34]
https://easywechat.org/zh-cn/docs/ 文档服务器挂了,建议能不能弄一个离线文档呢？

**Comment by overtrue** [comment]
@roobe 服务器挂掉是很小机率的事情，而且基本都能很快得到修复，在线文档能给我带来服务器的运维费用，所以这也是没有离线版的原因之一，当然最重要的原因是离线版无法保持更新。
