### ISSUE TITLE
你好，请问模拟数据测试的时候数组内的$user是如何获取的呢

### ISSUE THREAD

**Issue by chianz** [overtrue/laravel-wechat#341]
#### 在您的laravel-wechat 项目中的 模拟登陆那段代码没能明白数组内的$user 是怎么来的，麻烦解答下。谢谢。
---
### 模拟授权
> 有时候我们希望在本地开发完成后线上才真实的走微信授权流程，这将减少我们的开发成本，那么你需要做以下两步：

准备假资料：
以下字段在 scope 为 snsapi_userinfo 时尽可能配置齐全哦，当然，如果你的模式只是 snsapi_base 的话只需要 openid 就好了。
```php
use Illuminate\Support\Arr;
use Overtrue\Socialite\User as SocialiteUser;

$user = new SocialiteUser([
                'id' => Arr::get($user, 'openid'),
                'name' => Arr::get($user, 'nickname'),
                'nickname' => Arr::get($user, 'nickname'),
                'avatar' => Arr::get($user, 'headimgurl'),
                'email' => null,
                'original' => [],
                'provider' => 'WeChat',
            ]);
```

**Comment by mingyoung** [comment]
就是你自己需要模拟的数据，比如这样也可以：

```php
$user = new SocialiteUser([
    'id' => 'openidopenidopenidopenid',
    'name' => '张三',
    'nickname' => '张三',
    'avatar' => 'http://example.com/avatar.jpg',
    'email' => null,
    'original' => [],
    'provider' => 'WeChat',
]);
```

**Comment by chianz** [comment]
> 就是你自己需要模拟的数据，比如这样也可以：
> 
> ```
> $socialiteUser = new SocialiteUser([
>     'id' => 'openidopenidopenidopenid',
>     'name' => '张三',
>     'nickname' => '张三',
>     'avatar' => 'http://example.com/avatar.jpg',
>     'email' => null,
>     'original' => [],
>     'provider' => 'WeChat',
> ]);
> ```

好的 明白了 感谢解答
