### ISSUE TITLE
如何获取 EasyWeChat 每次调微信接口时的 request body ？

### ISSUE THREAD

**Issue by KiddoLin** [overtrue/laravel-wechat#348]
因为业务需要，须记录请求的原始数据，请问如何在请求后获取 request 的 body 呢？感谢回答！
例如：
$response = EasyWeChat::payment()->order->unify($params);

overtrue/laravel-wechat: 5.0.0

**Comment by overtrue** [comment]
可以调用 `$app->pushMiddleware($middleware)` 实现，中间件写法请参考：

http://docs.guzzlephp.org/en/stable/handlers-and-middleware.html#middleware

```php
$app->pushMiddleware(Middleware::mapRequest(function (RequestInterface $request) {
    // $request 
}));
```
