### ISSUE TITLE
laravel 6.x 无法安装 5.0 

### ISSUE THREAD

**Issue by moell-peng** [overtrue/laravel-wechat#349]
## 错误
  - Installing easywechat-composer/easywechat-composer (1.2.0): Loading from cache
Plugin installation failed, rolling back
  - Removing easywechat-composer/easywechat-composer (1.2.0)

  [RuntimeException]
  Could not delete /home/vagrant/code/yanyanxiyi/vendor/easywechat-composer/easywechat-composer/src/Commands:

## 已尝试
* rm -Rf composer.lock
* rm -Rf vendor

**Comment by mingyoung** [comment]
试试 `composer i --no-plugins`

**Comment by moell-peng** [comment]
@mingyoung 谢谢
