### ISSUE TITLE
通过alias方式获取实例发生exception

### ISSUE THREAD

**Issue by gewuxy** [overtrue/laravel-wechat#35]
具体配置
config providers：
Overtrue\LaravelWechat\ServiceProvider::class,

alias：
'Wechat' => Overtrue\LaravelWechat\Facade::class,

代码：
$wechat = Wechat::server();
$payment = $wechat->payment;

异常情况：
<img width="1280" alt="2016-07-24 22 05 55" src="https://cloud.githubusercontent.com/assets/8190691/17084204/d7e0c724-51ea-11e6-927c-ec265e6c44fd.png">

**Comment by overtrue** [comment]
@gewuxy 你在 server 里获取 payment? 你确定你没懵？

**Comment by gewuxy** [comment]
在user里获取payment也错误，没看到laravel wechat更多的文档介绍，可以指引一下么

**Comment by overtrue** [comment]
@gewuxy 你是怎么可能会想到 “从用户模块里拿支付模块” 的？所有模块都在主应用里  `Wechat::payment()` https://easywechat.org/zh-cn/docs/ . 😢

**Comment by gewuxy** [comment]
我已经通过注入暂时解决这个问题了，现在遇到[CDATA[JSAPI支付必须传openid]的问题，支付的文档也没有传open ID，现在时间比较急，还没研究透你的代码，这是不是一个bug

**Comment by overtrue** [comment]
@gewuxy 时间紧才更需要认真看文档。
