### ISSUE TITLE
lumen 使用lavavel框架包或者直接wechat包都报Illegal offset type in isset or empty

### ISSUE THREAD

**Issue by zhoulisheng** [overtrue/laravel-wechat#354]
依赖和错误消息如下图
![image](https://user-images.githubusercontent.com/19283357/71864297-6f191380-313a-11ea-89a3-a61a89a5cfad.png)
![image](https://user-images.githubusercontent.com/19283357/71864325-7c360280-313a-11ea-8f3f-31238964bf5b.png)

**Comment by overtrue** [comment]
更新包的版本，目前最新的是 4.2.11，使用命令检查：

```bash
$ composer info overtrue/wechat
```

**Comment by zhoulisheng** [comment]
你好  我尝试更新成4.2.11 仍然是这个错误
![image](https://user-images.githubusercontent.com/19283357/71946465-e74c0b80-3204-11ea-867d-c8dc6482e0c2.png)

**Comment by zhoulisheng** [comment]
> 更新包的版本，目前最新的是 4.2.11，使用命令检查：
> 
> ```shell
> $ composer info overtrue/wechat
> ```

我去wechat下看到了#1666的issue，和那老哥一样，使用4.1.31版本也是可以的。但是4.2.1不行
php7.3.1   
lumen5.7

**Comment by zhangweiwei0326** [comment]
这个问题解决了吗，我更新之后也报这个了
