### ISSUE TITLE
小程序订阅消息4.x版本支持吗？  

### ISSUE THREAD

**Issue by feivorid** [overtrue/laravel-wechat#356]
php : 7.2.x
laravel : 5.5.x
laravel-wechat : ~4.0
目前这样的

小程序订阅消息4.x版本支持吗？  
我更新了一下 貌似没有支持

**Comment by almas1992** [comment]
提issue前不能搜一下以前issue麽 ？https://github.com/overtrue/laravel-wechat/issues/350

**Comment by feivorid** [comment]
@almas1992    这个看了 但是官网上的easywechat  master 对应laravel-wechat 什么版本 ？   貌似看不出来

**Comment by almas1992** [comment]
> @almas1992 这个看了 但是官网上的easywechat master 对应laravel-wechat 什么版本 ？ 貌似看不出来

看看源码 https://github.com/overtrue/wechat/blob/master/src/MiniProgram/Application.php#L49-L71  中有没注册 `ubscribeMessage\ServiceProvider::class` ，切换对应的版本tag

**Comment by feivorid** [comment]
@almas1992    谢了。
