### ISSUE TITLE
Call to undefined method EasyWeChat\OfficialAccount\Application::menu()

### ISSUE THREAD

**Issue by fivenull** [overtrue/laravel-wechat#359]
laravel版本5.7
laravel-wechat版本4.0
调用服务端接口是可以的，调用自定义菜单的时候不可以。
![image](https://user-images.githubusercontent.com/49241070/73586996-6aa10a00-44f0-11ea-9dbe-1820202a8858.png)

**Comment by overtrue** [comment]
麻烦看清楚文档，是 `menu` 不是 `menu()`

oooooo <notifications@github.com>于2020年2月1日 周六下午12:43写道：

**Comment by fivenull** [comment]
不好意思，看错文档了
