### ISSUE TITLE
php7.3 使用simplexml_load_string() 报错

### ISSUE THREAD

**Issue by gw123** [overtrue/laravel-wechat#366]
Call to undefined function EasyWeChat\Kernel\Support\simplexml_load_string()

**Comment by overtrue** [comment]
https://www.easywechat.com/docs

文档首页就列明了需要哪些拓展哈

gw123 <notifications@github.com>于2020年3月29日 周日下午12:07写道：

**Comment by Vanson** [comment]
安装这个 php7-simplexml
