### ISSUE TITLE
公众号设置ip白名单无效

### ISSUE THREAD

**Issue by donguuuu** [overtrue/laravel-wechat#367]
{"errcode":40164,"errmsg":"invalid ip 101.45.43.1 ipv6 ::ffff:101.45.43.1, not in whitelist hint: [jotvMa01143580]"} {"exception":"[object] (EasyWeChat\\Kernel\\Exceptions\\HttpException(code: 0): Request access_token fail: {\"errcode\":40164,\"errmsg\":\"invalid ip 101.45.43.100 ipv6 ::ffff:101.45.43.100, not in whitelist hint: [jotvMa01143580]\"} at 、、vendor\\overtrue\\wechat\\src\\Kernel\\AccessToken.php:179)

已核实，ip在后台已经设置白名单。依旧提示

**Comment by overtrue** [comment]
这事儿你的找微信官方，SDK又没办法绕过微信限制啊亲……

donguuuu <notifications@github.com>于2020年3月29日 周日下午5:01写道：
