### ISSUE TITLE
lumen 在調用微信中間件 獲取的域名和我配置的域名不是同一個，我在nginx上做了代理 ，獲取的是我代理服務器的域名

### ISSUE THREAD

**Issue by penglzy** [overtrue/laravel-wechat#368]
我這樣調用的  提示10003 錯誤
微信網頁後臺設置的是a.com/api/project_name  中間件跳轉的redirect_url 參數是b.com
$router->group(['prefix' => '/users','middleware'=>'wechat.oauth'], function () use ($router) {
    //修改菜單
    $router->get("/create-menu", 'UserController@createMenu');.......

**Comment by penglzy** [comment]
感到很疑惑  :  在bootstrap 裏面的app   OAuthAuthenticate  $request->fullUrl()獲取的域名 并非我微信後臺設置的域名  $this->isFromTrustedProxy()  原因處在這個地方 更改了域名

**Comment by overtrue** [comment]
代理的时候设置 host
