### ISSUE TITLE
求同步更新，求文档

### ISSUE THREAD

**Issue by davidfromtheeast** [overtrue/laravel-wechat#373]
EasyWeChat有新功能出来了，希望有人维护此项目。

更关键的是如果有Wiki文档就最好了。

**Comment by mingyoung** [comment]
让我们行动起来 👉https://www.easywechat.com/donate 催更 🤣

**Comment by overtrue** [comment]
@mingyoung 哈哈哈😄

张铭阳 <notifications@github.com>于2020年5月28日 周四上午10:08写道：

**Comment by davidfromtheeast** [comment]
@overtrue 请大佬喝奶茶🤣

**Comment by overtrue** [comment]
这个项目只是针对 Laravel 的一个外壳，里面 EasyWeChat 就是最新的啊，请问你说的是哪里需要更新？

**Comment by davidfromtheeast** [comment]
@overtrue 懂了。
