### ISSUE TITLE
Undefined index: HTTP_HOST while using JSSDK

### ISSUE THREAD

**Issue by jonasva** [overtrue/laravel-wechat#378]
I'm using the WeChat JSSDK through a view composer on one of the pages on my website. Everything works fine for normal users, but I noticed that when **certain bots and crawlers** visit my site, the WeChat package throws this error:
`Undefined index: HTTP_HOST`, which comes from [this line](https://github.com/overtrue/wechat/blob/master/src/Kernel/Support/Helpers.php#L104) in the underlying WeChat SDK. 

I haven't been able to figure out why certain bots trigger this error, and others don't.

View composer code:

```php
class WeChatJsComposer
{
    public function compose(View $view)
    {
        if (config('settings.enable-wechat-api')) {
            // generate config for WeChat JSSDK (provides custom share msgs)
            try {
                $officialAccount    = EasyWeChat::officialAccount();
                $js                 = $officialAccount->jssdk->buildConfig(['updateTimelineShareData' , 'updateAppMessageShareData'], config('app.debug', false));
                $view->with('weChatJs', $js);
            } catch (HttpException $e) {
                // Send error to sentry instead of crashing the whole app
                SentryService::captureError($e);
            }
        }
    }
}
```

Would it be possible to catch this error somewhere in this package to prevent it from flooding the error logs when the site gets hits from bots?

**Comment by overtrue** [comment]
jssdk only works for web, so please access via fpm mode.

**Comment by jonasva** [comment]
I am using FPM mode. It's just that some bots and crawlers manage to not send correct Host information, which triggers this error. Also in the [PHP docs](https://www.php.net/manual/en/reserved.variables.server.php), it does say that the HTTP_HOST may not always be set. 

> Contents of the Host: header from the current request, **if there is one.**

Maybe a solution would be to imitate the approach Laravel/Symfony use to grab the current URL, as I'm not getting any error when using their `url()->current()` function.

**Comment by wilbur-oo** [comment]
Or set the URL manually
`$officialAccount->jssdk->setUrl($request->url())->buildConfig()`
