### ISSUE TITLE
关于 lumen 的 EasyWeChat 的 alias 问题

### ISSUE THREAD

**Issue by zqbinary** [overtrue/laravel-wechat#379]
我的版本是6.x lumen

放 bootstrap/app.php
在 $app->register 最后一行下面 加上

$app->withFacades(true, [
    'Overtrue\LaravelWeChat\Facade' => 'EasyWeChat',
]);

**Comment by overtrue** [comment]
那么你的问题是啥？全程都是陈述句，我没看出你的问题是啥……

**Comment by zqbinary** [comment]
一开始确实有问题，后来解决了，然后我看你readme 没说这个，我就当补充喽。

**Comment by overtrue** [comment]
好吧，我以为要提问……

xixili <notifications@github.com>于2020年7月23日 周四上午9:09写道：
