### ISSUE TITLE
本包所依赖的 overtrue/wechat 版本不是最新的？

### ISSUE THREAD

**Issue by KiddoLin** [overtrue/laravel-wechat#381]
## 我用的环境

* PHP 版本：7.3
* overtrue/laravel-wechat 版本：5.0.4
* 是否使用了框架？框架名称：laravel
* overtrue/wechat 版本：4.2.23

## 问题及现象

更新 overtrue/laravel-wechat 后，所依赖的 overtrue/wechat 只到4.2.23版本，缺少部分企业微信的接口，例如 企业微信-外部联系人-客户群管理 相关的接口。
请问在不把  overtrue/wechat 手动加入 composer.json 文件的情况下，如何将本包所依赖的 overtrue/wechat 升至最新版呢？

**Comment by overtrue** [comment]
composer update overtrue/wechat

KID <notifications@github.com>于2020年7月23日 周四下午12:16写道：

**Comment by KiddoLin** [comment]
@overtrue 执行过很多次 ```composer update overtrue/wechat``` 了哦，仍是只到 4.2.23 版本，提示“nothing to install or update“

**Comment by overtrue** [comment]
用的那个源？换阿里的

**Comment by KiddoLin** [comment]
> 用的那个源？换阿里的

还是 4.2.23 。原本是用 packagist 的 https://getcomposer.org/installer ，换阿里的 https://mirrors.aliyun.com/composer/ 也是一样哦

**Comment by overtrue** [comment]
https://github.com/overtrue/wechat/releases/tag/4.2.25 最新已经是 4.2.25

**Comment by KiddoLin** [comment]
@overtrue 多谢，知道最新版是4.2.25的。可能是这些源还没同步到最新版 T..T 我再找找其它源试试吧

**Comment by KiddoLin** [comment]
问题已解决。
这几天 overtrue/laravel-wechat 发布了 5.0.5、5.0.6 ，今天再次 ```composer update overtrue/laravel-wechat``` 后，overtrue/laravel-wechat 到 5.0.6 ，而 overtrue/wechat 就升级到 4.2.25 了。
【总结】
根本原因：未知。换过很多个 composer 的源，也清除了 composer 的缓存，但仍只能升级到 4.2.23 。
试过手动在 composer.lock 文件中直接修改为 4.2.25 ，结果是可以安装下来的。
可能原因：1.各个 composer 源有缓存，虽然直接 require overtrue/wechat 的是4.2.25，但缓存中的 overtrue/laravel-wechat 依赖的  overtrue/wechat 最新版是 4.2.23。
