### ISSUE TITLE
OA中间件报错：syntax error, unexpected 'Config' (T_STRING), expecting function (T_FUNCTION) or const (T_CONST)

### ISSUE THREAD

**Issue by Chen-Zhitong** [overtrue/laravel-wechat#382]
https://flareapp.io/share/lm2YkO5x#F44

var/www/wwwroot/wisdom_cloud/shared/vendor/overtrue/socialite/src/SocialiteManager.php:12

syntax error, unexpected 'Config' (T_STRING), expecting function (T_FUNCTION) or const (T_CONST)

Laravel version
7.19.1
Laravel locale
zh-CN
Laravel config cached
false
PHP version
7.3.20

**Comment by EricRun** [comment]
您好，这个问题怎么解决的？

**Comment by wangliqin** [comment]
您好，这个问题怎么解决的？

**Comment by overtrue** [comment]
升级 PHP 到 7.4
