### ISSUE TITLE
Laravel6 最新版使用公众号授权有问题？

### ISSUE THREAD

**Issue by shuqingzai** [overtrue/laravel-wechat#383]
提示重复定义头

![image](https://user-images.githubusercontent.com/44406033/88475071-336f5b00-cf5f-11ea-90bd-3d65f0090069.png)
![image](https://user-images.githubusercontent.com/44406033/88475087-5437b080-cf5f-11ea-92be-4e5425a30c74.png)
![image](https://user-images.githubusercontent.com/44406033/88475079-42eea400-cf5f-11ea-8ebd-b7d704bd65f5.png)

Header may not contain more than a single header, new line detected in file /home/www/lms/vendor/symfony/http-foundation/Response.php on line 346

**Comment by fengzifz** [comment]
5.8 也有这个问题。我也是一模一样的问题

**Comment by laravuel** [comment]
一毛一样的问题

**Comment by yuhal** [comment]
使用的 laravel 7.28，也是有这个问题。

**Comment by bolechen** [comment]
可以暂时换 5.0.7 版本，等超哥修复最新版本
2020年9月27日 +0800 13:48 Yohann <notifications@github.com>，写道：

**Comment by futuremeng** [comment]
"name": "laravel/framework",
            "version": "v6.20.6",
 "name": "overtrue/laravel-wechat",
            "version": "5.1.0",

以上组合没有问题了。
