### ISSUE TITLE
Laravel v6.18.35  overtrue/laravel-wechat v5.0.7 无法读取配置文件

### ISSUE THREAD

**Issue by daizhongxing** [overtrue/laravel-wechat#386]
Laravel版本： v6.18.35
overtrue/laravel-wechat 版本：v5.0.7
问题：无法读取配置文件 config/wechat.php
请求接口报错：appid missing

**Comment by overtrue** [comment]
请证明是 SDK 读不到配置，比如在 tinker 中截图 `config('wechat')` 的结果！

**Comment by daizhongxing** [comment]
已解决，版本问题，换成5.0.3就正常了
