### ISSUE TITLE
求支持laravel8

### ISSUE THREAD

**Issue by ethanfly** [overtrue/laravel-wechat#387]
求支持laravel8

**Comment by Wkan** [comment]
还应该升级 `overtrue/wechat` 到 `5`，`overtrue/wechat@4` 依赖的 `overtrue/socialite@~2.0` 使用了 `guzzlehttp/guzzle@6` 会和 laravel8 的 `guzzlehttp/guzzle@7` 冲突

**Comment by overtrue** [comment]
https://github.com/overtrue/laravel-wechat/releases/tag/5.0.8
