### ISSUE TITLE
Laravel8 OAuth中间件 网页授权问题

### ISSUE THREAD

**Issue by Fendy5** [overtrue/laravel-wechat#392]
1、微信公众号网页授权，抛出如下错误：

![image](https://user-images.githubusercontent.com/27864474/93086568-e8a1d200-f6c9-11ea-86a8-a8c77e6b22a9.png)

--------------------------------------分割线-----------------------------------------------

2、企业微信网页授权则显示中间件没有找到：

![image](https://user-images.githubusercontent.com/27864474/93086706-1850da00-f6ca-11ea-852c-354bab757247.png)

中间件明明已经注册了：

![image](https://user-images.githubusercontent.com/27864474/93086838-4df5c300-f6ca-11ea-905b-be5b15b5f48d.png)

// web.php
![image](https://user-images.githubusercontent.com/27864474/93087161-c3619380-f6ca-11ea-89c9-0dc49fe4a0f4.png)

**Comment by overtrue** [comment]
企业微信不适用这个中间件
