### ISSUE TITLE
laravel 8.0 网页授权中间件报错 undefined method WeChat::user()

### ISSUE THREAD

**Issue by nosun** [overtrue/laravel-wechat#397]
- laravel 8.0
- php:7.4
- "overtrue/laravel-wechat": "~5.0",
- "overtrue/wechat": "~5.0"

网页授权
```
Call to undefined method Overtrue\Socialite\Providers\WeChat::user()
```
代码 47行：
```
$officialAccount->oauth->user()
```
修改为：
```
$officialAccount->oauth->userFromCode($request->input('code') )
```
是可以的。

**Comment by overtrue** [comment]
https://github.com/overtrue/laravel-wechat/blob/master/src/Middleware/OAuthAuthenticate.php#L62-L66
