### ISSUE TITLE
laravel 7.28 授权用户资料失败

### ISSUE THREAD

**Issue by yuhal** [overtrue/laravel-wechat#398]
# 环境

- laravel 7.28

- php 7.3.21

- composer.json

```
"overtrue/laravel-lang": "^3.0",
"overtrue/laravel-wechat": "~5.0"
```

# 路由

```
Route::group(['middleware' => ['web', 'wechat.oauth']], function () {
    Route::get('/user', function () {
        $user = session('wechat.oauth_user.default'); // 拿到授权用户资料

        dd($user);
    });
});
```

# 问题

![image](https://user-images.githubusercontent.com/24805661/94356931-b4b1ae00-00c6-11eb-8f3f-074e3543dbf4.png)

> 浏览器访问 http://c2twmb.natappfree.cc/user，报错如上。

恳请大家给予帮助~

**Comment by bolechen** [comment]
可以暂时换 5.0.7 版本，等超哥修复最新版本
2020年9月27日 +0800 13:40 Yohann <notifications@github.com>，写道：
