### ISSUE TITLE
composer update 之后报错

### ISSUE THREAD

**Issue by zhimeiRaomc** [overtrue/laravel-wechat#4]
PHP Parse error: syntax error, unexpected '{' in /home/wwwroot/weixin.xxx.com/vendor/overtrue/laravel-wechat/src/ServiceProvider.php on line 62

**Comment by lazyou** [comment]
我手动把 ServiceProvider,php下的
 return new {$service}(config('wechat.appId'), config('wechat.secret')); 
改成
 return new $service(config('wechat.appId'), config('wechat.secret')); 

接着又有下面的问题了。
[2015-04-24 19:49:38] local.ERROR: exception 'ErrorException' with message 'Class 'Overtrue\LaravelWechat\Facade' not found' in /var/www/meishenghuo/web/vendor/laravel/framework/src/Illuminate/Foundation/AliasLoader.php:63

**Comment by overtrue** [comment]
@lazyou 抱歉，我昨天在开发中，还没完成，今天已经完成了，在新版里已经没有Facade了，新版是针对overtrue/wechat 2.0所更新的，所以请回滚到旧版：`composer require "overtrue/laravel-wechat:1.0.3"`

**Comment by lazyou** [comment]
恩。退回来是解决了，那要怎么使用 jssdk？
顺便问下你有没有遇到过在微信浏览器内提交表单乱码的情况（ipd iphone没问题，联想的安卓机就出现类似 http://segmentfault.com/q/1010000002627452）？

**Comment by overtrue** [comment]
@lazyou 可能还是部分机型浏览器有bug吧，因为如果服务端有问题，在任何设备上提交同样的内容即可重现。
