### ISSUE TITLE
微信公众号网页授权获取用户信息报错

### ISSUE THREAD

**Issue by gyp719** [overtrue/laravel-wechat#400]
"overtrue/laravel-wechat": "^5.0",
laravel5.8

Call to undefined method Overtrue\Socialite\Providers\WeChatProvider::userFromCode()

```
$app = app('wechat.official_account');
return $user = $app->oauth->userFromCode('031D5f1003RyrK1m7u300WHVU31D5f1r');
```

**Comment by bolechen** [comment]
约束到 5.x 版本
2020年10月14日 +0800 11:10 亦平凡 <notifications@github.com>，写道：

**Comment by Amos1st** [comment]
这个问题 我也遇到了，是包的版本问题么

**Comment by Amos1st** [comment]
> 约束到 5.x 版本 2020年10月14日 +0800 11:10 亦平凡 <notifications@github.com>，写道：
> […](#)
> "overtrue/laravel-wechat": "^5.0", laravel5.8 Call to undefined method Overtrue\Socialite\Providers\WeChatProvider::userFromCode() $app = app('wechat.official_account'); return $user = $app->oauth->userFromCode('031D5f1003RyrK1m7u300WHVU31D5f1r'); — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.



> 约束到 5.x 版本 2020年10月14日 +0800 11:10 亦平凡 <notifications@github.com>，写道：
> […](#)
> "overtrue/laravel-wechat": "^5.0", laravel5.8 Call to undefined method Overtrue\Socialite\Providers\WeChatProvider::userFromCode() $app = app('wechat.official_account'); return $user = $app->oauth->userFromCode('031D5f1003RyrK1m7u300WHVU31D5f1r'); — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

@bolechen 您好，这个问题我也遇到了，请问是包的版本问题么

**Comment by Amos1st** [comment]
> 约束到 5.x 版本 2020年10月14日 +0800 11:10 亦平凡 <notifications@github.com>，写道：
> […](#)
> "overtrue/laravel-wechat": "^5.0", laravel5.8 Call to undefined method Overtrue\Socialite\Providers\WeChatProvider::userFromCode() $app = app('wechat.official_account'); return $user = $app->oauth->userFromCode('031D5f1003RyrK1m7u300WHVU31D5f1r'); — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

@bolechen  您好，这个问题我也遇到了，请问是包的版本问题么
