### ISSUE TITLE
Lumen 6.3.3 composer 安装失败

### ISSUE THREAD

**Issue by BruceFan-FS71** [overtrue/laravel-wechat#403]
执行 composer require overtrue/laravel-wechat，报错信息如下，尝试 rm -rf composer.lock 后再执行，错误也一样：

Using version ^6.0 for overtrue/laravel-wechat
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - overtrue/wechat 5.0.0 requires overtrue/socialite dev-develop -> no matching package found.
    - Installation request for overtrue/laravel-wechat ^6.0 -> satisfiable by overtrue/laravel-wechat[6.0.0].
    - Conclusion: remove symfony/http-foundation v4.4.16
    - overtrue/laravel-wechat 6.0.0 requires overtrue/wechat ^5.0 -> satisfiable by overtrue/wechat[5.0.0, 5.0.1, 5.0.2, 5.0.3, 5.0.4, 5.0.5, 5.0.6, 5.0.7, 5.0.8, 5.0.9, 5.1.0, 5.1.1, 5.1.2, 5.1.3].
    - overtrue/wechat 5.0.1 requires overtrue/socialite ^3.0 -> satisfiable by overtrue/socialite[3.0.0, 3.0.1, 3.0.2, 3.0.3, 3.0.4, 3.0.5, 3.0.6].
    - overtrue/wechat 5.0.2 requires overtrue/socialite ^3.0 -> satisfiable by overtrue/socialite[3.0.0, 3.0.1, 3.0.2, 3.0.3, 3.0.4, 3.0.5, 3.0.6].
    - overtrue/wechat 5.0.3 requires overtrue/socialite ^3.0 -> satisfiable by overtrue/socialite[3.0.0, 3.0.1, 3.0.2, 3.0.3, 3.0.4, 3.0.5, 3.0.6].
    - overtrue/wechat 5.0.4 requires overtrue/socialite ^3.0 -> satisfiable by overtrue/socialite[3.0.0, 3.0.1, 3.0.2, 3.0.3, 3.0.4, 3.0.5, 3.0.6].
    - overtrue/wechat 5.0.5 requires overtrue/socialite ^3.0 -> satisfiable by overtrue/socialite[3.0.0, 3.0.1, 3.0.2, 3.0.3, 3.0.4, 3.0.5, 3.0.6].
    - overtrue/wechat 5.0.6 requires overtrue/socialite ^3.0 -> satisfiable by overtrue/socialite[3.0.0, 3.0.1, 3.0.2, 3.0.3, 3.0.4, 3.0.5, 3.0.6].
    - overtrue/wechat 5.0.7 requires overtrue/socialite ^3.0 -> satisfiable by overtrue/socialite[3.0.0, 3.0.1, 3.0.2, 3.0.3, 3.0.4, 3.0.5, 3.0.6].
    - overtrue/wechat 5.0.8 requires overtrue/socialite ^3.0 -> satisfiable by overtrue/socialite[3.0.0, 3.0.1, 3.0.2, 3.0.3, 3.0.4, 3.0.5, 3.0.6].
    - overtrue/wechat 5.0.9 requires overtrue/socialite ^3.0 -> satisfiable by overtrue/socialite[3.0.0, 3.0.1, 3.0.2, 3.0.3, 3.0.4, 3.0.5, 3.0.6].
    - overtrue/wechat 5.1.0 requires overtrue/socialite ^3.0 -> satisfiable by overtrue/socialite[3.0.0, 3.0.1, 3.0.2, 3.0.3, 3.0.4, 3.0.5, 3.0.6].
    - overtrue/wechat 5.1.1 requires overtrue/socialite ^3.0 -> satisfiable by overtrue/socialite[3.0.0, 3.0.1, 3.0.2, 3.0.3, 3.0.4, 3.0.5, 3.0.6].
    - overtrue/wechat 5.1.2 requires overtrue/socialite ^3.0 -> satisfiable by overtrue/socialite[3.0.0, 3.0.1, 3.0.2, 3.0.3, 3.0.4, 3.0.5, 3.0.6].
    - overtrue/wechat 5.1.3 requires overtrue/socialite ^3.0 -> satisfiable by overtrue/socialite[3.0.0, 3.0.1, 3.0.2, 3.0.3, 3.0.4, 3.0.5, 3.0.6].
    - overtrue/socialite 3.0.0 requires symfony/http-foundation ^5.0 -> satisfiable by symfony/http-foundation[5.0.x-dev, 5.1.x-dev, 5.x-dev, v5.0.0, v5.0.0-BETA1, v5.0.0-BETA2, v5.0.0-RC1, v5.0.1, v5.0.10, v5.0.11, v5.0.2, v5.0.3, v5.0.4, v5.0.5, v5.0.6, v5.0.7, v5.0.8, v5.0.9, v5.1.0, v5.1.0-BETA1, v5.1.0-RC1, v5.1.0-RC2, v5.1.1, v5.1.2, v5.1.3, v5.1.4, v5.1.5, v5.1.6, v5.1.7, v5.1.8, v5.2.0-BETA1, v5.2.0-BETA2, v5.2.0-BETA3].
    - overtrue/socialite 3.0.1 requires symfony/http-foundation ^5.0 -> satisfiable by symfony/http-foundation[5.0.x-dev, 5.1.x-dev, 5.x-dev, v5.0.0, v5.0.0-BETA1, v5.0.0-BETA2, v5.0.0-RC1, v5.0.1, v5.0.10, v5.0.11, v5.0.2, v5.0.3, v5.0.4, v5.0.5, v5.0.6, v5.0.7, v5.0.8, v5.0.9, v5.1.0, v5.1.0-BETA1, v5.1.0-RC1, v5.1.0-RC2, v5.1.1, v5.1.2, v5.1.3, v5.1.4, v5.1.5, v5.1.6, v5.1.7, v5.1.8, v5.2.0-BETA1, v5.2.0-BETA2, v5.2.0-BETA3].
    - overtrue/socialite 3.0.2 requires symfony/http-foundation ^5.0 -> satisfiable by symfony/http-foundation[5.0.x-dev, 5.1.x-dev, 5.x-dev, v5.0.0, v5.0.0-BETA1, v5.0.0-BETA2, v5.0.0-RC1, v5.0.1, v5.0.10, v5.0.11, v5.0.2, v5.0.3, v5.0.4, v5.0.5, v5.0.6, v5.0.7, v5.0.8, v5.0.9, v5.1.0, v5.1.0-BETA1, v5.1.0-RC1, v5.1.0-RC2, v5.1.1, v5.1.2, v5.1.3, v5.1.4, v5.1.5, v5.1.6, v5.1.7, v5.1.8, v5.2.0-BETA1, v5.2.0-BETA2, v5.2.0-BETA3].
    - overtrue/socialite 3.0.3 requires symfony/http-foundation ^5.0 -> satisfiable by symfony/http-foundation[5.0.x-dev, 5.1.x-dev, 5.x-dev, v5.0.0, v5.0.0-BETA1, v5.0.0-BETA2, v5.0.0-RC1, v5.0.1, v5.0.10, v5.0.11, v5.0.2, v5.0.3, v5.0.4, v5.0.5, v5.0.6, v5.0.7, v5.0.8, v5.0.9, v5.1.0, v5.1.0-BETA1, v5.1.0-RC1, v5.1.0-RC2, v5.1.1, v5.1.2, v5.1.3, v5.1.4, v5.1.5, v5.1.6, v5.1.7, v5.1.8, v5.2.0-BETA1, v5.2.0-BETA2, v5.2.0-BETA3].
    - overtrue/socialite 3.0.4 requires symfony/http-foundation ^5.0 -> satisfiable by symfony/http-foundation[5.0.x-dev, 5.1.x-dev, 5.x-dev, v5.0.0, v5.0.0-BETA1, v5.0.0-BETA2, v5.0.0-RC1, v5.0.1, v5.0.10, v5.0.11, v5.0.2, v5.0.3, v5.0.4, v5.0.5, v5.0.6, v5.0.7, v5.0.8, v5.0.9, v5.1.0, v5.1.0-BETA1, v5.1.0-RC1, v5.1.0-RC2, v5.1.1, v5.1.2, v5.1.3, v5.1.4, v5.1.5, v5.1.6, v5.1.7, v5.1.8, v5.2.0-BETA1, v5.2.0-BETA2, v5.2.0-BETA3].
    - overtrue/socialite 3.0.5 requires symfony/http-foundation ^5.0 -> satisfiable by symfony/http-foundation[5.0.x-dev, 5.1.x-dev, 5.x-dev, v5.0.0, v5.0.0-BETA1, v5.0.0-BETA2, v5.0.0-RC1, v5.0.1, v5.0.10, v5.0.11, v5.0.2, v5.0.3, v5.0.4, v5.0.5, v5.0.6, v5.0.7, v5.0.8, v5.0.9, v5.1.0, v5.1.0-BETA1, v5.1.0-RC1, v5.1.0-RC2, v5.1.1, v5.1.2, v5.1.3, v5.1.4, v5.1.5, v5.1.6, v5.1.7, v5.1.8, v5.2.0-BETA1, v5.2.0-BETA2, v5.2.0-BETA3].
    - overtrue/socialite 3.0.6 requires symfony/http-foundation ^5.0 -> satisfiable by symfony/http-foundation[5.0.x-dev, 5.1.x-dev, 5.x-dev, v5.0.0, v5.0.0-BETA1, v5.0.0-BETA2, v5.0.0-RC1, v5.0.1, v5.0.10, v5.0.11, v5.0.2, v5.0.3, v5.0.4, v5.0.5, v5.0.6, v5.0.7, v5.0.8, v5.0.9, v5.1.0, v5.1.0-BETA1, v5.1.0-RC1, v5.1.0-RC2, v5.1.1, v5.1.2, v5.1.3, v5.1.4, v5.1.5, v5.1.6, v5.1.7, v5.1.8, v5.2.0-BETA1, v5.2.0-BETA2, v5.2.0-BETA3].
    - Can only install one of: symfony/http-foundation[v4.4.16, 5.0.x-dev].
    - Can only install one of: symfony/http-foundation[v4.4.16, 5.1.x-dev].
    - Can only install one of: symfony/http-foundation[v4.4.16, 5.x-dev].
    - Can only install one of: symfony/http-foundation[v5.0.0, v4.4.16].
    - Can only install one of: symfony/http-foundation[v5.0.0-BETA1, v4.4.16].
    - Can only install one of: symfony/http-foundation[v5.0.0-BETA2, v4.4.16].
    - Can only install one of: symfony/http-foundation[v5.0.0-RC1, v4.4.16].
    - Can only install one of: symfony/http-foundation[v5.0.1, v4.4.16].
    - Can only install one of: symfony/http-foundation[v5.0.10, v4.4.16].
    - Can only install one of: symfony/http-foundation[v5.0.11, v4.4.16].
    - Can only install one of: symfony/http-foundation[v5.0.2, v4.4.16].
    - Can only install one of: symfony/http-foundation[v5.0.3, v4.4.16].
    - Can only install one of: symfony/http-foundation[v5.0.4, v4.4.16].
    - Can only install one of: symfony/http-foundation[v5.0.5, v4.4.16].
    - Can only install one of: symfony/http-foundation[v5.0.6, v4.4.16].
    - Can only install one of: symfony/http-foundation[v5.0.7, v4.4.16].
    - Can only install one of: symfony/http-foundation[v5.0.8, v4.4.16].
    - Can only install one of: symfony/http-foundation[v5.0.9, v4.4.16].
    - Can only install one of: symfony/http-foundation[v5.1.0, v4.4.16].
    - Can only install one of: symfony/http-foundation[v5.1.0-BETA1, v4.4.16].
    - Can only install one of: symfony/http-foundation[v5.1.0-RC1, v4.4.16].
    - Can only install one of: symfony/http-foundation[v5.1.0-RC2, v4.4.16].
    - Can only install one of: symfony/http-foundation[v5.1.1, v4.4.16].
    - Can only install one of: symfony/http-foundation[v5.1.2, v4.4.16].
    - Can only install one of: symfony/http-foundation[v5.1.3, v4.4.16].
    - Can only install one of: symfony/http-foundation[v5.1.4, v4.4.16].
    - Can only install one of: symfony/http-foundation[v5.1.5, v4.4.16].
    - Can only install one of: symfony/http-foundation[v5.1.6, v4.4.16].
    - Can only install one of: symfony/http-foundation[v5.1.7, v4.4.16].
    - Can only install one of: symfony/http-foundation[v5.1.8, v4.4.16].
    - Can only install one of: symfony/http-foundation[v5.2.0-BETA1, v4.4.16].
    - Can only install one of: symfony/http-foundation[v5.2.0-BETA2, v4.4.16].
    - Can only install one of: symfony/http-foundation[v5.2.0-BETA3, v4.4.16].
    - Installation request for symfony/http-foundation (installed at v4.4.16) -> satisfiable by symfony/http-foundation[v4.4.16].

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.
 - It's a private package and you forgot to add a custom repository to find it

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

Installation failed, reverting ./composer.json to its original content.

**Comment by overtrue** [comment]
```bash
$ composer require overtrue/laravel-wechat:^5.0
```

**Comment by BruceFan-FS71** [comment]
是的，指定 ^5.1 可以支持 Lumen 6.3.3。

但，如果想在 Lumen 6.3.3 下使用 6.0，该怎么办？或是，6.0 后续版本会修复这个问题？

**Comment by BruceFan-FS71** [comment]
> ```shell
> $ composer require overtrue/laravel-wechat:^5.0
> ```

是的，指定 ^5.1 可以支持 Lumen 6.3.3
但，如果想在 Lumen 6.3.3 下使用 6.0，该怎么办？或是 6.0 后续版本会修复这个问题？

**Comment by overtrue** [comment]
抱歉，这不是问题不需要修复，你安装了不对应的版本而已，你要使用 6.0 就升级你的框架到新版本就好了。

**Comment by BruceFan-FS71** [comment]
超哥，那在文档里面标注版本对应的框架要求吧。

因为文档里面是 Laravel/Lumen >= 5.1，我以为 Lumen6.3.3 也可以使用 6.0

**Comment by overtrue** [comment]
@BruceFan-FS71 上次改版忘记改 readme 了，马上改

**Comment by BruceFan-FS71** [comment]
多谢超哥

**Comment by overtrue** [comment]
不客气哈
