### ISSUE TITLE
Credential "component_verify_ticket" does not exist in cache.

### ISSUE THREAD

**Issue by penglzy** [overtrue/laravel-wechat#404]
![image](https://user-images.githubusercontent.com/16076894/100589772-7b97f300-332e-11eb-88a2-ffe53819036f.png)
有时候去跳转页面的时候报 verify ticket 不存在

![image](https://user-images.githubusercontent.com/16076894/100589932-ada95500-332e-11eb-967c-34dda4dddea2.png)

**Comment by overtrue** [comment]
抱歉这里不解决这个问题:https://github.com/w7corp/easywechat/issues?q=component_verify_ticket
