### ISSUE TITLE
小程序登录 The given payload is invalid 错误 

### ISSUE THREAD

**Issue by zhanghoo** [overtrue/laravel-wechat#409]
更新到了 6.0 还是会出现这个错误 The given payload is invalid，请问该怎么解决一下呢。
我这里是这么操作的 （mini是返回那个配置）
`$info = mini()->auth->session(request()->input("code"));`
`if (!isset($info["openid"])) {`
`    return $this->sendResults(400, [], "获取openid失败，请更换code");`
`}`
`$decryptedData = mini()->encryptor->decryptData($info['session_key'], request()->input("iv"), request()->input("encryptedData"));`

**Comment by aoxiang594** [comment]
同上，确定iv  session_key 没有问题。

**Comment by overtrue** [comment]
麻烦提供版本号：

```
$ composer info overtrue/wechat 
```

**Comment by lhyaax** [comment]
我也碰到这个问题。
overtrue/laravel-wechat:* 5.1.0
overtrue/wechat:* 4.4.0

@overtrue 试了先$app->auth->session($code)获取到session_key,把session_key缓存起来。

**Comment by overtrue** [comment]
确保每次前端都调用了登录方法获取最新的 key
