### ISSUE TITLE
以scopes=snsapi_base获取openid会返回48001 api unauthorized

### ISSUE THREAD

**Issue by teiiken** [overtrue/laravel-wechat#412]
直接$app->oauth->userFromCode($code)->getId();想只拿openid，会返回48001 api unauthorized。如果先用snsapi_userinfo获得一次后则没有问题。请问是我的手法问题还是有什么需要注意

name     : overtrue/laravel-wechat
descrip. : 微信 SDK for Laravel
keywords : laravel, sdk, wechat, weixin
versions : * 6.0.0
type     : library
license  : MIT License (MIT) (OSI approved) https://spdx.org/licenses/MIT.html#licenseText
homepage : 
source   : [git] https://github.com/overtrue/laravel-wechat.git 80645b30306d4fe78b8dcc884a98e1a241d77fbe
dist     : [zip] https://api.github.com/repos/overtrue/laravel-wechat/zipball/80645b30306d4fe78b8dcc884a98e1a241d77fbe 80645b30306d4fe78b8dcc884a98e1a241d77fbe
path     : /www/wwwroot/wzz-api/vendor/overtrue/laravel-wechat
names    : overtrue/laravel-wechat

support
issues : https://github.com/overtrue/laravel-wechat/issues
source : https://github.com/overtrue/laravel-wechat/tree/6.0.0

autoload
psr-4
Overtrue\LaravelWeChat\ => src/

requires
illuminate/container ^5.1 || ^6.0 || ^7.0 || ^8.0
overtrue/wechat ^5.0

requires (dev)
friendsofphp/php-cs-fixer ^2.16
laravel/framework ^8.5

**Comment by overtrue** [comment]
这个我就不清楚了，可以仔细看看微信文档了解一下

**Comment by ikencheng** [comment]
> 这个我就不清楚了，可以仔细看看微信文档了解一下

你好，我是楼主，CallBack的时候我改用原生php代码是没有问题的

//这是跳转拿code的代码
public function getOpenidOnly($callback = '/api/wechat/test/getopenidonlycallback')
    {
        $config = [
            'app_id' => config('wechat.app_id'),
            'secret' => config('wechat.secret'),
            'response_type' => 'array',
            'oauth' => [
                'scopes' => ['snsapi_base'],
//                'callback' => '/api/wechat/test/getopenidonlycallback',
                'callback' => $callback,
            ],
        ];
        $app = Factory::officialAccount($config);
        $oauth = $app->oauth;
        return $oauth->redirect();
    }

//这个代码会返回48001
public function getOpenidOnlyCallBack($code)
    {
        $config = [
            'app_id' => config('wechat.app_id'),
            'secret' => config('wechat.secret'),
            'response_type' => 'array',
            // ...
        ];
        $app = Factory::officialAccount($config);
        $oauth = $app->oauth;
        return $oauth->userFromCode($code)->getId();
    }

//改用原生php代码是能正常获取的
public function getOpenidOnlyCallBack($code)
    {
        $appid = "***********************"; 
        $secret = "*******************************************"; 
        $get_token_url = 'https://api.weixin.qq.com/sns/oauth2/access_token?appid='.$appid.'&secret='.$secret.'&code='.$code.'&grant_type=authorization_code';
        $ch = curl_init();
        curl_setopt($ch,CURLOPT_URL,$get_token_url); 
        curl_setopt($ch,CURLOPT_HEADER,0); 
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1 ); 
        curl_setopt($ch, CURLOPT_CONNECTTIMEOUT, 10); 
        $res = curl_exec($ch); 
        curl_close($ch); 
        $json_obj = json_decode($res,true); 
        $openid = $json_obj['openid']; 
    }

**Comment by teiiken** [comment]
callback的时候在 $config里面的 'oauth' 加'scopes' => ['snsapi_base']似乎解决了。开始只在跳转去微信前加了
