### ISSUE TITLE
wechat.log 日志的分割与乱码

### ISSUE THREAD

**Issue by luokelong** [overtrue/laravel-wechat#421]
在 wechat.php 配置文件中看到：

`        'log'               => [
            'level' => env('WECHAT_LOG_LEVEL', 'debug'),
            'file'  => env('WECHAT_LOG_FILE', storage_path('logs/wechat.log')),
        ],
`
使用过程中有如下问题：

1、如何设置使日志按 daily 保存
2、图片、声音、视频消息会导致 wechat.log 中包含巨量的乱码，应该是存储了大量的媒体数据，如何避免。

**Comment by overtrue** [comment]
https://easywechat.com/docs/5.x/official-account/configuration#heading-h2-0
