### ISSUE TITLE
Invalid message content:(0) Function libxml_disable_entity_loader() is deprecated

### ISSUE THREAD

**Issue by liu-sen** [overtrue/laravel-wechat#422]
Laravel版本: 7.29
PHP版本: 8.0
laravel-wechat: 5.1

![image](https://user-images.githubusercontent.com/22153494/126030165-47fdbfa5-0ff3-4f58-b791-6e77300ee999.png)

**Comment by overtrue** [comment]
更新一下版本啦：https://github.com/w7corp/easywechat/blob/5.x/src/Kernel/Support/XML.php#L30-L36
