### ISSUE TITLE
微信统一下单 v3 出错

### ISSUE THREAD

**Issue by andy236726493** [overtrue/laravel-wechat#427]
$payment = \EasyWeChat::payment();
  $result       = $payment->order->unify([
                'mchid'        => '1399120****',
                'out_trade_no' => 'NO12177525012014070332333',
                'appid'        => 'wxaa1e3729b5***',
                'description'  => 'Image ',
                'notify_url'   => ‘https://www.***.com/pay/notify’
                'amount'       => [
                    'total'    => 1,
                    'currency' => 'CNY'
                ],
                'payer'       => [ 'openid' => ‘oEcdL5D8mxXuZD*****‘’ ]
            ]);
出现错误
ErrorException: Undefined index: trade_type in file .../vendor/overtrue/wechat/src/Payment/Order/Client.php on line 38

**Comment by overtrue** [comment]
https://www.easywechat.com/5.x/payment/order.html#%E7%BB%9F%E4%B8%80%E4%B8%8B%E5%8D%95
