### ISSUE TITLE
自动发现别名问题

### ISSUE THREAD

**Issue by JimChenWYU** [overtrue/laravel-wechat#429]
能否把自动发现中别名注册去掉，让用户自行决定是否注册别名

PS: 个人觉得 laravel 提供类别名功能设计并不是一个好设计

**Comment by overtrue** [comment]
@JimChenWYU 嗯，所以后来的包我都基本不提供了，这得发大版本才能去掉，或者你使用 `dont-discover` 来禁用掉它吧
