### ISSUE TITLE
laravel 5.1.46 (LTS)  安装不了 

### ISSUE THREAD

**Issue by xianlinzhang** [overtrue/laravel-wechat#430]
laravel版本： 5.1.46 (LTS)  
安装4.0：composer require "overtrue/laravel-wechat:^4.0" --with-all-dependencies
![image](https://user-images.githubusercontent.com/30235909/142792132-b16778e8-84f7-4468-aaff-eff1b29822ad.png)

laravel 依赖的某个扩展和 overtrue/laravel-wechat 依赖的扩展有冲突，
是不支持 laravel 5.1.46吗？

**Comment by overtrue** [comment]
这个报错看不出问题哦，你试试直接：
```php
$ composer require "overtrue/laravel-wechat:^4.0" 
```

**Comment by xianlinzhang** [comment]
是composer的版本问题，用的是composer2的版本，
