### ISSUE TITLE
laravel 9 报错

### ISSUE THREAD

**Issue by waney** [overtrue/laravel-wechat#436]
https://github.com/overtrue/laravel-wechat/blob/f8300dac610baae3736fcdeb1ea4ee17e2f1fac9/src/ServiceProvider.php#L93

PHP 8.0.13
laravel 9.1.0
···
Cannot use object of type EasyWeChat\OpenPlatform\Application as array
···
![微信截图_20220222095533](https://user-images.githubusercontent.com/69211/155049031-e16843f4-9806-4190-8444-25da906f47c9.png)

**Comment by overtrue** [comment]
哪个版本啊？

麻烦检查一下：

1.  pimple/container 版本
2. vendor 代码是否动过？
3. 删掉 vendor 重新装试试？

**Comment by waney** [comment]
只是单纯的升了laravel 9.1.0, 其他什么都没动，
```
 w7corp/easywechat (6.0-beta17)
overtrue/laravel-wechat (master)
```

**Comment by overtrue** [comment]
overtrue/laravel-wechat 目前只支持 overtrue/wechat 5.x 不支持  w7corp/easywechat 。。。
