### ISSUE TITLE
Cannot use object of type EasyWeChat\OfficialAccount\Application as array 

### ISSUE THREAD

**Issue by zbage** [overtrue/laravel-wechat#438]
Route::get('/test',function(){
    $user = session('easywechat.oauth_user.default');
    // dd($user);
    echo 'hello:'.$user['id'];
})->middleware(['easywechat.oauth'])->name('test');

local.ERROR: Cannot use object of type EasyWeChat\OfficialAccount\Application as array {"exception":"[object] (Error(code: 0): Cannot use object of type EasyWeChat\\OfficialAccount\\Application as array at ...../testing_laravel9/vendor/overtrue/laravel-wechat/src/ServiceProvider.php:73)

**Comment by overtrue** [comment]
还没改完哈

**Comment by overtrue** [comment]
已修复
