### ISSUE TITLE
Client error: `POST https://qyapi.weixin.qq.com/cgi-bin/externalcontact/unionid_to_external_userid_3rd` resulted in a `404 Not Found` response

### ISSUE THREAD

**Issue by 94lvgang** [overtrue/laravel-wechat#443]
unionid查询external_userid接口有问题，请求地址404，我看官方的地址是https://qyapi.weixin.qq.com/cgi-bin/service/externalcontact/unionid_to_external_userid_3rd，少了service

**Comment by overtrue** [comment]
w7corp/easywechat#2428
