### ISSUE TITLE
6.x版微信支付报错

### ISSUE THREAD

**Issue by weiyechaocat** [overtrue/laravel-wechat#444]
<img width="359" alt="图片" src="https://user-images.githubusercontent.com/18710965/162146157-546749fb-1d68-4e4a-b8f5-10f680ef20cc.png">
php 8.1.3
代码如下
<img width="566" alt="图片" src="https://user-images.githubusercontent.com/18710965/162146579-f2759ef9-edf4-4503-a3c5-a9618a2ba220.png">

错误信息如下
<img width="846" alt="图片" src="https://user-images.githubusercontent.com/18710965/162146213-93e29879-9928-49ae-b2b4-fab659972164.png">

**Comment by overtrue** [comment]
把配置里的 http.throw 改为 false 看看具体错误原因

**Comment by overtrue** [comment]
https://www.easywechat.com/6.x/client.html#%E5%A4%84%E7%90%86%E5%93%8D%E5%BA%94
