### ISSUE TITLE
postJson() 方法找不到

### ISSUE THREAD

**Issue by badongdyc** [overtrue/laravel-wechat#448]
![IK 9}{9P_G{RHL2TDB `0UP](https://user-images.githubusercontent.com/17975624/171692776-b0d2c344-a8f2-4326-81fd-6d2c6e18e701.png)
如图

**Comment by overtrue** [comment]
版本不对哈

**Comment by badongdyc** [comment]
> 

哪个版本不对？

**Comment by badongdyc** [comment]
> 版本不对哈

哪个版本不对？

**Comment by overtrue** [comment]
> > 版本不对哈
> 
> 
> 
> 哪个版本不对？
> 
> 

EasyWeChat版本需要 6.5.0以上

**Comment by badongdyc** [comment]
> > > 版本不对哈
> > 
> > 
> > 哪个版本不对？
> 
> EasyWeChat版本需要 6.5.0以上

composer require "overtrue/laravel-wechat" 我这样装的，easywechat好像是6.0的

**Comment by overtrue** [comment]
删掉你的阿里云的packagist源

**Comment by badongdyc** [comment]
已解决
