### ISSUE TITLE
公众号报错

### ISSUE THREAD

**Issue by ClearSeve** [overtrue/laravel-wechat#449]
打开url或者公众号接入都不对，提示
Failed to decode request contents.

所用到的代码是官方的例子
```
    public function serve()
    {
      $server = app('easywechat.official_account')->getServer();
      $server->with(function($message){
            return "欢迎关注 overtrue！";
        });

        return $server->serve();
    }
```
PHP 8.1
"laravel/framework": "^8.75",
"overtrue/laravel-wechat": "^7.0",

![1](https://user-images.githubusercontent.com/26833671/172513397-7cf7de56-8eea-4bfa-8fc3-16f57c261dd3.png)

**Comment by huanhuashengling** [comment]
@ClearSeve Have you resolve this problem? I am stuck at this several days...

**Comment by ClearSeve** [comment]
> @ClearSeve Have you resolve this problem? I am stuck at this several days...

This problem occurs when the browser opens the link. WeChat can be used to interact normally
