### ISSUE TITLE
ENGLISH README.MD

### ISSUE THREAD

**Issue by Heinirich** [overtrue/laravel-wechat#451]
Could we please have an English Version of Readme.md. Thank you!

**Comment by overtrue** [comment]
@Heinirich This package is a wrapper of [w7corp/easywechat](https://github.com/w7corp/easywechat), So, if we provide the English README, We must also provide the English documentation for [w7corp/easywechat](https://github.com/w7corp/easywechat).  it will take a lot of time. Also, WeChat's main business is in mainland China, where not many developers are currently using it, and there may also be API incompatibilities in parts outside of China, so it's not quite sure if the same code will work outside of mainland China.

Of course, we will consider providing an English version of the document, but we are not too sure when it will be completed.

**Comment by overtrue** [comment]
@Heinirich The English README is ready: https://github.com/overtrue/laravel-wechat/blob/7.x/README_EN.md
