### ISSUE TITLE
ServiceProvider有点疑惑

### ISSUE THREAD

**Issue by Aroad233** [overtrue/laravel-wechat#452]
超哥你好，对于ServiceProvider有点疑惑
`$this->app->alias("easywechat.{$name}.default", 'easywechat.'.$name);
            $this->app->alias("easywechat.{$name}.default", 'easywechat.'.$name);

            $this->app->alias('easywechat.'.$name, $class);
            $this->app->alias('easywechat.'.$name, $class);`
这里关联是不是写重复了

**Comment by overtrue** [comment]
@Aroad233 从旧版替换改过来的，没注意重复哈哈哈哈，已经修复，感谢反馈！
