### ISSUE TITLE
Failed to decode request contents.

### ISSUE THREAD

**Issue by huanhuashengling** [overtrue/laravel-wechat#457]
First, thanks for the author's hard work, and do these replies! Thanks a lot! 
version: overtrue/laravel-wechat 7.x
Php version:8.1

I followed the readme file WeChatController->serve but i occur this problem
EasyWeChat\Kernel\Message line 62 throw exception "Failed to decode request contents"

I stuck at this for several days, and can’t find any answers.

I finally work it out
1. Downgrade the PHP version from 8.1 to 8.0
2. Downgrade overtrue/laravel-wechat version from 7.x to 6.x
3. Then i get the right result from $app->server->serve() 

I guess maybe overtrue/laravel-wechat 7.x and php 8.1 is not work well.
(package structure has changed most)

Maybe we need to update to the latest version later.

You can close this issue if you want, thanks.

**Comment by overtrue** [comment]
你从哪里看到 `Failed to decode request contents` 内容的？

**Comment by androiddisk** [comment]
> 你从哪里看到 `Failed to decode request contents` 内容的？
你好 直接在浏览器打开api的链接就会  "Failed to decode request contents"

**Comment by androiddisk** [comment]
> 你从哪里看到 `Failed to decode request contents` 内容的？

你好 直接在浏览器打开api的链接就会 "Failed to decode request contents"

https://github.com/overtrue/laravel-wechat/issues/449

**Comment by overtrue** [comment]
为啥要在浏览器打开？
