### ISSUE TITLE
生成小程序码url多了个&quot

### ISSUE THREAD

**Issue by kingdle** [overtrue/laravel-wechat#458]
Symfony\Component\HttpClient\Exception\JsonException: Malformed UTF-8 characters, possibly incorrectly encoded for &quot;https://api.weixin.qq.com/wxa/getwxacodeunlimit?access_token=59__RqruGNNBVz2rBDLMgAwto6mwTLXVFL3O2b6gq4H6N5d5d8zyWdEgqf4vwFfsirMdYH5E-5mACzKw8CPYNKGKsmhspvzlvyNaptho3-ySo-te44IvW-ffqbN1c1C32aQr7KoCPiQzLnjOybnUGQjACAPBL&quot;. in file /Users/maxdata/Sites/jlsign/vendor/symfony/http-client/Response/CommonResponseTrait.php on line 94

**Comment by overtrue** [comment]
没明白问题是啥？它返回值本身就不是 JSON

**Comment by kingdle** [comment]
我粗心弄错了，抱歉
