### ISSUE TITLE
微信公众号动态配置无效

### ISSUE THREAD

**Issue by ligl** [overtrue/laravel-wechat#46]
微信公众号动态配置无效....
//
$wechatConfig = DB::table('wx_config')->first();
//...
//
$wechat = app('wechat', $wechatConfig);

$wechat['config']的值仍是config/wechat.php配置文件中的值，并不是传过去的$wechatConfig

**Comment by JeffreyChu** [comment]
这样的使用场景应该采用如下方式:
$wechat = new \EasyWeChat\Foundation\Application($wechatConfig);
