### ISSUE TITLE
laravel-wechat 如何根据 [w7corp/easywechat] 进行API 调用

### ISSUE THREAD

**Issue by GitHub-Ahai** [overtrue/laravel-wechat#464]
laravel-wechat 如何根据 [w7corp/easywechat]  https://easywechat.com/6.x/client.html 进行API 调用？

**Comment by GitHub-Ahai** [comment]
https://easywechat.com/6.x/client.html

**Comment by puzzle9** [comment]
你解决了吗 我也遇到这个问题了
