### ISSUE TITLE
/tmp/easywechat/easywechat.log

### ISSUE THREAD

**Issue by Lny-nice** [overtrue/laravel-wechat#465]
UnexpectedValueException: The stream or file "/tmp/easywechat/easywechat.log" could not be opened in append mode: failed to open stream: Permission denied
The exception occurred while attempting to log: Unable to create configured logger. Using emergency logger.

**Comment by yangrongzhou** [comment]
你的日志存储路径是 /tmp/easywechat/easywechat.log ，如果你用 root 账户执行php脚本首次调用了 easywechat 的接口，日志文件 /tmp/easywechat/easywechat.log 被创建，它的写权限就是 root 。但一般 php-fpm 模式下执行的权限是 www 或 www-data ，所以追加日志的时候提示没有权限。

解决办法：
方式1：手动更改日志文件的所有者权限 `chown www:www /tmp/easywechat/easywechat.log`。
方式2：使用 `su www -s /bin/bash -c 'php artisan xxx' ` 这种方式指定执行php脚本时的用户。
