### ISSUE TITLE
php8.2有问题

### ISSUE THREAD

**Issue by adiudiuu** [overtrue/laravel-wechat#468]
php artisan vendor:publish --provider="Overtrue\LaravelWeChat\ServiceProvider"

![image](https://user-images.githubusercontent.com/31238774/221397626-054536f3-a0d1-4efe-8a21-2c37902907dd.png)

**Comment by overtrue** [comment]
试试这个？ 

```bash
php artisan vendor:publish --provider="Overtrue\\LaravelWeChat\\ServiceProvider"
```

**Comment by MaZhaolin** [comment]
我也遇到了同样的问题 ，请问怎么解决的 @overtrue @diudiudiuu 
<img width="642" alt="image" src="https://user-images.githubusercontent.com/13713662/222062781-5bdab8f6-a22f-4ee4-9ed7-4c45e3a051af.png">

**Comment by adiudiuu** [comment]
> 我也遇到了同样的问题 ，请问怎么解决的 @overtrue @diudiudiuu <img alt="image" width="642" src="https://user-images.githubusercontent.com/13713662/222062781-5bdab8f6-a22f-4ee4-9ed7-4c45e3a051af.png">

我没有用这个包了,感觉有点扯.文档写的稀碎

**Comment by puzzle9** [comment]
这是整体迁移到 https://github.com/w7corp/easywechat 这个了吗
