### ISSUE TITLE
OAuthAuthenticate逻辑问题isNewSession永远为false

### ISSUE THREAD

**Issue by boywangxj** [overtrue/laravel-wechat#47]
isNewSession等于true时，直接return 走了，Event::fire(new WeChatUserAuthorized(session('wechat.oauth_user'), $isNewSession));这里的isNewSesssion 永远不可能为true

**Comment by overtrue** [comment]
@boywangxj 嗯，这块确实不正确，我需要修改一下。

**Comment by ddingchen** [comment]
其实单从这个事件定义的名称WeChatUserAuthorized来看，直接在用户通过授权后的处理代码中触发这个事件就可以了，也不需要$isNewSession这个变量，代码也更清晰简单，不知道我这样理解对不对，或者有我没有考虑到的使用情景。
if ($request->has('state') && $request->has('code')) {
    session(['wechat.oauth_user' => $this->wechat->oauth->user()]);
    Event::fire(new WeChatUserAuthorized(session('wechat.oauth_user')));
    return redirect()->to($this->getTargetUrl($request));
}

**Comment by overtrue** [comment]
isNewSession 表示是第一次授权， session 没过期之前的后续所有授权都不是第一次
