### ISSUE TITLE
Laravel 10 安装发布资源报错

### ISSUE THREAD

**Issue by keacefull** [overtrue/laravel-wechat#470]
php artisan vendor:publish --provider="Overtrue\\LaravelWeChat\\ServiceProvider"

   INFO  No publishable resources for tag [].
 PHP 8.1 和 8.2 都有这个错

**Comment by hongkaiwang365** [comment]
Laravel 9 也是

**Comment by chen900804** [comment]
我的也是

**Comment by overtrue** [comment]
试了一下看起来不知道是 composer 问题还是 packagist 导致安装到了 2.1.2 版本，但其实最新已经是 7.2.0 了，各位可以这样指定版本范围安装：

```bash
composer require overtrue/laravel-wechat:^7.2
```

**Comment by QiuYiBin** [comment]
如果是 windows，这样执行就可以了，去除双引号
php artisan vendor:publish --provider=Overtrue\LaravelWeChat\ServiceProvider

**Comment by xujinhui2015** [comment]
> 如果是 windows，这样执行就可以了，去除双引号 php artisan vendor:publish --provider=Overtrue\LaravelWeChat\ServiceProvider

感谢，你这个可以解决
