### ISSUE TITLE
为什么验证会报这个错误？laravel 9， php8.1

### ISSUE THREAD

**Issue by hongkaiwang365** [overtrue/laravel-wechat#472]
![1681365936008](https://user-images.githubusercontent.com/128784135/231668167-e67c3266-ebd5-4e4b-94af-0876fde14dd7.png)
![image](https://user-images.githubusercontent.com/128784135/231668359-553af4ba-b511-423f-9391-84188cc3cf01.png)

**Comment by overtrue** [comment]
为什么你要用浏览器去访问这个本就不是给浏览器准备的地址？
