### ISSUE TITLE
laravel10安装报错

### ISSUE THREAD

**Issue by www295686243** [overtrue/laravel-wechat#473]
PHP环境是8.1.4
laravel是10.9
安装laravel-wechat:^7.2报这个错
![image](https://github.com/overtrue/laravel-wechat/assets/10710116/8b9682d5-b912-4238-8dfa-faac506fc674)
我也想用laravel-wechat:^6.0版本的但报这个错
![image](https://github.com/overtrue/laravel-wechat/assets/10710116/854af9f1-0e48-4b22-b37e-2ed4dbc82503)

**Comment by overtrue** [comment]
安装的时候加上 -W
