### ISSUE TITLE
Laravel 8.75 安装失败

### ISSUE THREAD

**Issue by ChunkitL** [overtrue/laravel-wechat#476]
Problem 1
    - Root composer.json requires overtrue/laravel-wechat 7.2 -> satisfiable by overtrue/laravel-wechat[7.2.0].
    - overtrue/laravel-wechat 7.2.0 requires illuminate/container ^9.0|^10.0 -> found illuminate/container[v9.0.0-beta.1, v9.0.0-beta.2, v9.0.0-beta.3, v9.0.0-beta.4, v9.0.0-beta.5, v9.0.0, v9.0.1, v9.0.2, v9.1.0, v9.2.0, v9.3.0, v9.3.1, v9.4.0, v9.4.1, v9.5.0, v9.5.1, v9.6.0, v9.7.0, v9.8.0, v9.8.1, v9.9.0, v9.10.0, v9.10.1, v9.11.0, v9.12.0, v9.12.1, v9.12.2, v9.13.0, v9.14.0, v9.14.1, v9.15.0, v9.16.0, v9.17.0, v9.18.0, v9.19.0, v9.20.0, v9.21.0, v9.21.1, v9.21.2, v9.21.3, v9.21.4, v9.21.5, v9.21.6, v9.22.0, v9.22.1, v9.23.0, v9.24.0, v9.25.0, v9.25.1, v9.26.0, v9.26.1, v9.27.0, v9.28.0, v9.29.0, v9.30.0, v9.30.1, v9.31.0, v9.32.0, v9.33.0, v9.34.0, v9.35.0, v9.35.1, v9.36.0, v9.36.1, v9.36.2, v9.36.3, v9.36.4, v9.37.0, v9.38.0, v9.39.0, v9.40.0, v9.40.1, v9.41.0, v9.42.0, v9.42.1, v9.42.2, v9.43.0, v9.44.0, v9.45.0, v9.45.1, v9.46.0, v9.47.0, v9.48.0, v9.49.0, v9.50.0, v9.50.1, v9.50.2, v9.51.0, v9.52.0, v9.52.1, v9.52.2, v9.52.3, v9.52.4, v9.52.5, v9.52.6, v9.52.7, v9.52.8, v9.52.9, v9.52.10, 9.x-dev, v10.0.0, v10.0.1, v10.0.2, v10.0.3, v10.1.0, v10.1.1, v10.1.2, v10.1.3, v10.1.4, v10.1.5, v10.2.0, v10.3.0, v10.3.1, v10.3.2, v10.3.3, v10.4.0, v10.4.1, v10.5.0, v10.5.1, v10.6.0, v10.6.1, v10.6.2, v10.7.0, v10.7.1, v10.8.0, v10.9.0, v10.10.0, v10.10.1, v10.11.0, v10.12.0, v10.13.0, v10.13.1, v10.13.2, v10.13.3, v10.13.5, v10.14.0, v10.14.1, v10.15.0, 10.x-dev] but these were not loaded, likely because it conflicts with another require.

按照说明来安装，第一步就卡住了

**Comment by overtrue** [comment]
Laravel 8 装不了 7.x，请安装 6.x:

```bash
composer  require overtrue/laravel-wechat:^6.1.1
```

**Comment by szwss** [comment]
@overtrue 6.x 公众号不能发布草稿上线

我用以下的方法测试
```
        $httpClient = $app['http_client']; // 使用 EasyWeChat 的 Guzzle 客户端
            //dd($httpClient);

            // 发布草稿
            $sendResult = $httpClient->post('/cgi-bin/freepublish/submit', [
                'json' => ['media_id' => $mediaId],
            ])->getBody()->getContents();
            $sendResult = json_decode($sendResult, true);
            if (isset($sendResult['errcode']) && $sendResult['errcode'] !== 0) {
                Log::error('Failed to publish draft for content ID ' . $content->id, [
                    'error' => $sendResult['errmsg'],
                    'errcode' => $sendResult['errcode'],
                ]);
                return;
            }
            $msgDataId = $sendResult['msg_data_id'];
            Log::info('Draft published for content ID ' . $content->id, $sendResult);
```

也是会报错
```
[2025-09-06T18:52:51.052242+08:00] local.ERROR: Failed to publish draft for content ID 2 {"error":"access_token missing rid: 68bc1283-2b9f1fa3-0caf8618","errcode":41001} []

```

有别的方法可以在 laravel8 和 php7 下使用吗
