### ISSUE TITLE
octane 服务下接收不到支付回调

### ISSUE THREAD

**Issue by m-finder** [overtrue/laravel-wechat#477]
![image](https://github.com/overtrue/laravel-wechat/assets/27805032/35a1f967-5e57-4ad9-8e12-306cad45967d)
看到有个 issue 说非 fpm 模式要自己实现，尝试了把 Illuminate\Http\Request 替换成 Psr\Http\Message\ServerRequestInterface，数据能打印出来，但是获取 message 始终报错： Invalid request body

大佬能不能帮忙看看是什么情况🙏

**Comment by oknixus** [comment]
https://github.com/w7corp/easywechat/discussions/2416
这个issue或许可以帮到你

**Comment by m-finder** [comment]
> [w7corp/easywechat#2416](https://github.com/w7corp/easywechat/discussions/2416) 这个issue或许可以帮到你

感谢
