### ISSUE TITLE
与laravel 10 冲突，主要是monolog的版本冲突

### ISSUE THREAD

**Issue by brianping7** [overtrue/laravel-wechat#478]
laravel 要求3.0以上的monolog版本， laravel-chat要求2.0版本

**Comment by overtrue** [comment]
抱歉，你说的哪个版本，新版没有依赖 monolog

**Comment by shuiguolinju** [comment]
- Root composer.json requires w7corp/easywechat ^6.8 -> satisfiable by w7corp/easywechat[6.8.0].
    - w7corp/easywechat 6.8.0 requires monolog/monolog ^2.2 -> found monolog/monolog[2.2.0, ..., 2.9.2] but these were not loaded, likely because it conflicts with another require.

**Comment by overtrue** [comment]
最新的是6.15.1
