### ISSUE TITLE
给公众号发消息，一直没有响应，没返回任何内容

### ISSUE THREAD

**Issue by amw0918** [overtrue/laravel-wechat#483]
![image](https://github.com/overtrue/laravel-wechat/assets/8489829/864bb4e1-8bf6-4a83-868f-9899de71d42e)
Laravel v9.52.16 (PHP v8.1.17)
"overtrue/laravel-wechat": "^7.2"

**Comment by overtrue** [comment]
因为你装了 debugbar

**Comment by amw0918** [comment]
> 因为你装了 debugbar

![image](https://github.com/overtrue/laravel-wechat/assets/8489829/7d5d55c7-2de1-4513-b80d-f7d11e0e425f)
麻烦看下是哪里的问题

**Comment by overtrue** [comment]
公众号后台的服务端验证通过了？

**Comment by amw0918** [comment]
> 公众号后台的服务端验证通过了？

嗯，验证过了，我后台laravel.log也能打印出来$message的内容， 就是 公众号没有响应

**Comment by overtrue** [comment]
服务器 URL 贴一下

**Comment by overtrue** [comment]
用官方调试工具测一下咯

**Comment by amw0918** [comment]
> 服务器 URL 贴一下

![image](https://github.com/overtrue/laravel-wechat/assets/8489829/806a7541-6796-4f5b-9bcf-485b3235a546)

**Comment by overtrue** [comment]
https://mp.weixin.qq.com/debug/

**Comment by amw0918** [comment]
> https://mp.weixin.qq.com/debug/

不会用这个，，应该选哪个 怎么测试哈。 在提问之前试了试  搞不懂

**Comment by overtrue** [comment]
SDK 目前版本没有问题，自己再查一下其他地方吧

**Comment by amw0918** [comment]
> https://mp.weixin.qq.com/debug/

![image](https://github.com/overtrue/laravel-wechat/assets/8489829/59e36762-2c60-4881-b113-41ec46187dd4)
![image](https://github.com/overtrue/laravel-wechat/assets/8489829/cba3e9b1-8726-4807-b9fb-feb020e26e02)

**Comment by amw0918** [comment]
> SDK 目前版本没有问题，自己再查一下其他地方吧

是这样测试吗

**Comment by fengbingji** [comment]
请问解决了吗?我也是一样的情况
