### ISSUE TITLE
overtrue/laravel-wechat 和包w7corp/easywechat依赖？

### ISSUE THREAD

**Issue by xianlinzhang** [overtrue/laravel-wechat#485]
![image](https://github.com/overtrue/laravel-wechat/assets/30235909/e51a58b0-7e73-4039-84aa-813797020dc0)
![image](https://github.com/overtrue/laravel-wechat/assets/30235909/c409ec2d-b2d0-4e93-879a-a305b4aa1bc8)
![image](https://github.com/overtrue/laravel-wechat/assets/30235909/8d4a7e1f-7c9d-4ff2-a98b-02bfa754ca26)
overtrue/laravel-wechat 包关联的 w7corp/easywechat都是5.0 ；怎么能让overtrue/laravel-wechat 包关联w7corp/easywechat 到5.35.1？

**Comment by overtrue** [comment]
https://semver.org/

`^5.0` 代表 大于等于 5.0.0 && 小于 6.0.0, 所以，这个写法当然可以装到 5.35.1

**Comment by xianlinzhang** [comment]
> https://semver.org/
> 
> `^5.0` 代表 大于等于 5.0.0 && 小于 6.0.0, 所以，这个写法当然可以装到 5.35.1

好的，谢谢解答
