### ISSUE TITLE
使用enable_mock后仍然提示需要微信打开

### ISSUE THREAD

**Issue by xlkit456852** [overtrue/laravel-wechat#49]
已经按文档设置好了enable_mock和mock_user，并使用了wechat.oauth中间件，访问的时候还是提示需要在微信打开？

**Comment by xlkit456852** [comment]
原来是因为composer下来的代码不是github的最新版？这个应该怎么更新成最新？

**Comment by overtrue** [comment]
@xlkit456852 使用 packagist 官方源即可。
