### ISSUE TITLE
使用composer连接不上去

### ISSUE THREAD

**Issue by mahavira** [overtrue/laravel-wechat#5]
以下是我们运行的结果

Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package overtrue/laravel-wechat could not be found in any version, there may be a typo in the package name.
  Problem 2
    - laravel/framework v5.0.28 requires ext-mcrypt * -> the requested PHP extension mcrypt is missing from your system.
    - laravel/framework v5.0.28 requires ext-mcrypt * -> the requested PHP extension mcrypt is missing from your system.
    - Installation request for laravel/framework == 5.0.28.0 -> satisfiable by laravel/framework[v5.0.28].

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion> for more details.

Read <http://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

Installation failed, reverting ./composer.json to its original content.

**Comment by overtrue** [comment]
请使用以下命令试试:

`composer require "overtrue/laravel-wechat:2.0.*` 

友情提醒，最近在开发2.0， 所以如果你是用3天前的版本的话，可能有不少地方需要修改一下。
