### ISSUE TITLE
有适合类似ionic这些前后端完全分离的前端框架的网页授权方法吗？

### ISSUE THREAD

**Issue by xlkit456852** [overtrue/laravel-wechat#55]
像这种前后端完全分离的前端框架，原本网页授权的连续性被打破了，有没有好的方法去完成网页授权？

**Comment by overtrue** [comment]
抱歉不是太有经验，这个你得问问其它朋友，个人觉得你可以在授权部分不需要前后分离啊。

**Comment by xlkit456852** [comment]
由于目前前端和后端非同一个域名，目前在尝试的方案是，前端-》跳转到后端的授权页面-》微信服务器跳转回前端域名并带上token参数，前端存下token参数，调用后端提供的根据token获取微信用户信息的接口来完成获取用户信息

**Comment by overtrue** [comment]
应该可以
