### ISSUE TITLE
可以用postman模拟微信支付成功的回调吗?

### ISSUE THREAD

**Issue by AndyxingY** [overtrue/laravel-wechat#59]
我用postman模拟微信支付成功之后的回调信息，post过来。
然后报错了。
<img width="529" alt="qq20161217-0 2x" src="https://cloud.githubusercontent.com/assets/21179164/21285829/9206a05a-c47e-11e6-8629-3913dbad1998.png">

**Comment by overtrue** [comment]
你要模拟，你就得先知道它请求你的时候传的是啥啊，光请求一个 URL ？

**Comment by AndyxingY** [comment]
您好，我是直接抓取了支付回调的XML，然后原模原样的数据post请求，然后就出现这样的错误。
<img width="592" alt="qq20161218-0 2x" src="https://cloud.githubusercontent.com/assets/21179164/21288333/24cf1e3a-c4bb-11e6-888f-f611d2d83688.png">   是不是我的操作有问题了?

**Comment by overtrue** [comment]
微信请求的时候，会在 URL 里带签名。。。

**Comment by AndyxingY** [comment]
好的，谢谢。
