### ISSUE TITLE
Your requirements could not be resolved to an installable set of packages.

### ISSUE THREAD

**Issue by renyang9876** [overtrue/laravel-wechat#6]
Problem 1
    - The requested package overtrue/laravel-wechat 2.0.* could not be found.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion> for more details.

Read <http://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

**Comment by overtrue** [comment]
2.0 还没有正式release,所以请在你的项目composer.json 加下面一行就可以了：

```json
"minimum-stability" : "dev",
```

**Comment by renyang9876** [comment]
嗯嗯，出现的第二个问题就是，在使用App::make时，出现"Class wechat.server does not exist"

**Comment by overtrue** [comment]
@renyang9876 请再次更新 SDK，这个问题昨天已经修复了。
