### ISSUE TITLE
Illegal offset type in unset with Laravel 5.4

### ISSUE THREAD

**Issue by ac1982** [overtrue/laravel-wechat#62]
Laravel->5.4 fresh installed.
Laravel->wechat 3.2.4.
Project crashed if add Overtrue\LaravelWechat\ServiceProvider::class to providers array.
```
    [ErrorException]
    Illegal offset type in unset
```

**Comment by ac1982** [comment]
I fount that because new Laravel 5.4 binding classes into the container with leading slashes is no longer supported. If with updated code it works fine.
 ```
 $this->app->singleton(('EasyWeChat\Foundation\Application'), function ($app) {
            $app = new Application(config('wechat'));

            if (config('wechat.use_laravel_cache')) {
                $app->cache = new CacheBridge();
            }

            return $app;
        });
```
But how to keep compatibility with Laravel<5.4?

**Comment by overtrue** [comment]
#63
