### ISSUE TITLE
使用授权中间件的时候，回调时又会触发一次授权，这个怎么解决？

### ISSUE THREAD

**Issue by xzjs** [overtrue/laravel-wechat#67]

**Comment by overtrue** [comment]
回调时网页带 code 参数，应该不会再授权一次啊

**Comment by overtrue** [comment]
@xzjs 麻烦使用 dev-master 版本试一下

**Comment by xzjs** [comment]
@overtrue 不好意思，是我这边搞错了，是获取授权的时候提示我跨域了，然后在network里会显示两次请求
![2017-02-08 10 29 41](https://cloud.githubusercontent.com/assets/2542160/22721066/89032502-ede9-11e6-904d-bdb90ff741c1.png)
![2017-02-08 10 30 50](https://cloud.githubusercontent.com/assets/2542160/22721093/af9b994c-ede9-11e6-9062-53fd00e707ce.png)
