### ISSUE TITLE
下载素材的出错

### ISSUE THREAD

**Issue by lazyou** [overtrue/laravel-wechat#7]
$media->download($value,  $filename);
下载素材时出现下面问题。

[2015-04-30 18:52:31] local.ERROR: exception 'Overtrue\Wechat\Exception' with message '[Wechat][43002] 43002 需要POST请求' in /var/www/meishenghuo/web/vendor/overtrue/wechat/src/Wechat/Http.php:91
Stack trace:
#0 /var/www/meishenghuo/web/vendor/overtrue/wechat/src/Wechat/Utils/Http.php(65): Overtrue\Wechat\Http->request('http://file.api...', 'GET', Array, Array)
#1 /var/www/meishenghuo/web/vendor/overtrue/wechat/src/Wechat/Media.php(251): Overtrue\Wechat\Utils\Http->get('http://file.api...', Array)
#2 /var/www/meishenghuo/web/app/Http/Controllers/RepairsController.php(104): Overtrue\Wechat\Media->download('Gr31ecyJCdFhQK2...', '/var/www/meishe...')

**Comment by overtrue** [comment]
@lazyou 是临时素材还是永久素材？

**Comment by lazyou** [comment]
临时素材，很有可能是api的url不对。

**Comment by overtrue** [comment]
@lazyou 确实是复制错了URL，已经fix: https://github.com/overtrue/wechat/commit/e198e52efad5e4747d19c7793a6961c798be2217
