### ISSUE TITLE
5.4 似乎不可用

### ISSUE THREAD

**Issue by cmzz** [overtrue/laravel-wechat#71]
local.ERROR: Overtrue\Socialite\AuthorizeFailedException: Authorize Failed: {"errcode":40013,"errmsg":"invalid appid, hints: [ req_id: tQPTEa0975s109 ]"} in /mnt/sdc/dindon_front/vendor/overtrue/socialite/src/Providers/AbstractProvider.php:409   

Oauth 中间件， 网页授权的一直报这个错误。
如果直接使用 overtrue/wechat, 则会提示 secret 无效

**Comment by mingyoung** [comment]
在 config.php 注释 openplatform 即可。如 pr #72

**Comment by cmzz** [comment]
能用，谢谢
