### ISSUE TITLE
中间件授权 40001

### ISSUE THREAD

**Issue by cmzz** [overtrue/laravel-wechat#76]
使用中间件授权的方式。 

某些手机授权不成功，拿不到openid.

user对象：

    {
      "id": null,
      "name": null,
      "nickname": null,
      "avatar": null,
      "email": null,
      "original": {
        "errcode": 40001,
        "errmsg": "invalid credential, access_token is invalid or not latest, hints: [ req_id: aGWfma0000ns83 ]"
      },
      "token": {
        "access_token": "p5rApFmJHpEzw37UIlwQNMnTMCxzksyrnp1fQGbcAxhCfrH5wGqFHI84SF6dDHhPCMs6J9DITF2br6gOxEEY2Hkzuw5qPjSnnuoK5uiw1zo",
        "expires_in": 7200,
        "refresh_token": "W9OZ31vZK0r5gCeMWiEOgXac-d23-CQZ3dBteZ93XWiqUAxgei9R9swNUKtYqdc9B9Zr98olV35LDsyaHoOwPxsHm61a-S7xW1WfIE8-NX0",
        "openid": "oN-UTxF1XDoe-cs2MxUfedxUdX2Q",
        "scope": "snsapi_userinfo"
      }
    }

**Comment by PetersonLian** [comment]
一行的问题。什么原因啊？求个思路

**Comment by terranc** [comment]
也遇到这样的问题，token里有值，id为null
