### ISSUE TITLE
Laravel5.4无法使用Facade方式调用~

### ISSUE THREAD

**Issue by bbzz7** [overtrue/laravel-wechat#77]
Laravel5.4无法使用facade调用~

**Comment by overtrue** [comment]
就这一句话？上下文呢？

**Comment by bbzz7** [comment]
抱歉，我补充一下，就是readme文档的最简单的例子，
在config/app.php 中的 aliases 部分中配置了：
'EasyWeChat' => Overtrue\LaravelWechat\Facade::class,
但是在WechatController中无法使用Facade方式，即EasyWeChat::server();等
需要use Overtrue\LaravelWechat\Facade
然后才可以使用 Facade::server(),好像是5.4的实时自动化Facade特性

**Comment by overtrue** [comment]
你是否试过  `use EasyWeChat`; 然后用呢？

**Comment by bbzz7** [comment]
确实如此，是忘记用use了，这里有个小小的疑问就是，为什么Laravel自带的Facade比如Log，不用use也可以直接使用呢

**Comment by overtrue** [comment]
@bbzz7 不可能，这是 PHP 语法，不 use 肯定用不了

**Comment by bbzz7** [comment]
我是在路由中(web.php)直接使用的Log类，但并没有看到文件中有使用use，好像也可以

**Comment by overtrue** [comment]
你需要学会什么是命名空间，谢谢，routes 下的文件与 Log 在同一根空间，当然不需要  use
