### ISSUE TITLE
不生成log文件，是我配置有错吗？

### ISSUE THREAD

**Issue by rockleeyuetian** [overtrue/laravel-wechat#78]
wechat.php中是这么写的：   
'debug'  => true,
 .......
 'log' => [
        'level' => env('WECHAT_LOG_LEVEL', 'debug'),
        'file'  => env('WECHAT_LOG_FILE', storage_path('logs/wechat.log')),
    ],（env中这两个参数都是空的）

测试支付的时候返回false，想查log文件，没找到，是在laravel的 storage/logs/目录下吧？

请帮看看是什么原因呢？ 谢谢！

**Comment by overtrue** [comment]
目录是否可以

**Comment by rockleeyuetian** [comment]
目录的权限修改为777了，paycontroller.php中也加use Log了，还是木有生成log文件
    public function call_pay(Request $request){
        $options = config('wechat');

        $app = new Application($options);
        $payment = $app->payment;

        $attributes = [
            'trade_type'       => 'JSAPI', // JSAPI，NATIVE，APP...
            'body'             => 'test body',
            'detail'           => 'test detail',
            'out_trade_no'     => '1217752501201407033233368018',
            'total_fee'        => 1,
            'notify_url'       => 'http://system.xxx.com/pay_notify', 
            // ...
        ];
// 创建订单
        $order = new Order($attributes);
        $result = $payment->prepare($order);
        var_dump($result);
        return $result;
}
浏览器中返回：{"return_code":"FAIL","return_msg":"JSAPI\u652f\u4ed8\u5fc5\u987b\u4f20openid"}

**Comment by rockleeyuetian** [comment]
日志文件还是没有生成，不过翻译出错误了，是“JSAPI支付必须传openid”  ~~~

**Comment by overtrue** [comment]
@rockleeyuetian 错误代码与错误消息来自微信，我不做处理

**Comment by overtrue** [comment]
@rockleeyuetian 日志目录下有 laravel.log 么？

**Comment by rockleeyuetian** [comment]
@overtrue 嗯，谢谢！
