### ISSUE TITLE
请求API时总是超时

### ISSUE THREAD

**Issue by barretzheng** [overtrue/laravel-wechat#79]
例如获取access_token，user信息等未能正确获取
报错如下：
GuzzleHttp\Exception\ConnectException: cURL error 28: Connection timed out after 5001 milliseconds (see http://curl.haxx.se/libcurl/c/libcurl-errors.html) in /var/www/sub/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php:186
Stack trace:
laravel5.4版本，新new的项目，添加了laravel-wechat，路由写在api下

**Comment by overtrue** [comment]
超时请检查你自己服务器网络问题，这个与 SDK 无关
