### ISSUE TITLE
公众号支付回调函数问题求助

### ISSUE THREAD

**Issue by rockleeyuetian** [overtrue/laravel-wechat#81]
请问回调函数这样写有什么错误呢？ 函数中第一行写数据库是会执行的，但后面的代码就不执行了，我是在laravel5.2中，手机端支付已经成功，俺是摸着石头过河，请大神指点，谢谢！
<pre><code>
public function pay_notify(Request $request){
        $wechatuser =DB::table('pay_lists')->where('orderid','2533993fb611ed7d78b06e4cac13c55f')->update(['paid_at' => date("Y-m-d H:i:s", time())]);
        $app = new Application(config('wechat'));
        $response = $app->payment->handleNotify(function($notify, $successful){
            // 使用通知里的 "微信支付订单号" 或者 "商户订单号" 去自己的数据库找到订单
            $order = Pay_list::where('orderid',$notify->transaction_id)->first();
            if (!$order) { // 如果订单不存在
                return 'Order not exist.'; // 告诉微信，我已经处理完了，订单没找到，别再通知我了
            }
            // 如果订单存在
            // 检查订单是否已经更新过支付状态
            if ($order->status=='paid' && $order->paid_at!=null) { // 假设订单字段“支付时间”不为空代表已经支付
                return true; // 已经支付成功了就不再更新了
            }
            // 用户是否支付成功
            if ($successful) {
                // 不是已经支付状态则修改为已经支付状态
                $order->paid_at = date("Y-m-d H:i:s", time()); // 更新支付时间为当前时间
                $order->status = 'paid';
                $echo =DB::table('pay_lists')->where('orderid',$order->orderid)
                    ->update(['paid_at' => date("Y-m-d H:i:s", time()),'status' => $order->status]);
            } else { // 用户支付失败
                $order->status = 'paid_fail';
                $echo =DB::table('pay_lists')->where('orderid',$order->orderid)
                    ->update(['status' => $order->status]);
            }
            $order->save(); // 保存订单
            return true; // 返回处理完成
        });
        return $response;
    }
</code></pre>

**Comment by rockleeyuetian** [comment]
头一次用传说中的markdown 。。。

**Comment by rockleeyuetian** [comment]
已解决了，查了微信文档原来 transaction_id是 微信支付订单号，创建订单的时候是没有这个数据的，所以用这个返回的id去数据库查是没有记录的，应该用  out_trade_no商户订单号， 这个就是创建订单时的orderID。 不知道我理解的对不对，如果真是这样的话，说明文档里的伪代码应该改为out_trade_no而不是transaction_id

**Comment by overtrue** [comment]
@rockleeyuetian 文档已更新
