### ISSUE TITLE
微信支付统一下单接口返回 [false] 

### ISSUE THREAD

**Issue by supgeek-rod** [overtrue/laravel-wechat#82]
在 Laravel 5.1 
```
overtrue/laravel-wechat               3.1.7   微信 SDK for Laravel
overtrue/wechat                       3.2.5   微信SDK
```

使用微信统一下单接口

```
$result = $wechat->payment->prepare($order);
var_dump($result);
```

返回如下

```
object(EasyWeChat\Support\Collection)#269 (1) {
  ["items":protected]=>
  array(1) {
    [0]=>
    bool(false)
  }
}
```

查看 log 也找不到问题所在，猜测可能是支付结果通知步骤出现了问题

**Comment by yanggg1133** [comment]
发自我的 iPhone

**Comment by yanggg1133** [comment]
你日志在哪里看的


发自我的 iPhone

**Comment by yanggg1133** [comment]
配置看下 另外日志那里看 laravel的日志吗

发自我的 iPhone

**Comment by supgeek-rod** [comment]
日志在 `storage/logs/wechat.log`

**Comment by supgeek-rod** [comment]
猜测可以是因为项目运行在 docker container 中，通过宿主机的 nginx 代理了，导致来自微信的结果通知失败，现在正在尝试在宿主机中部署项目

**Comment by yanggg1133** [comment]
Csrf 过滤例外加了吗


发自我的 iPhone

**Comment by yanggg1133** [comment]
噢 我这里没 但是我支付是好的 你看下 opptions有没有配置对

发自我的 iPhone

**Comment by yanggg1133** [comment]
看看options有没有写对


发自我的 iPhone

**Comment by supgeek-rod** [comment]
没搞清楚是什么原因，折腾了大半天是解决问题了。
@yanggg1133 感谢

**Comment by One2r** [comment]
能不能跟我说说怎么解决啊

**Comment by ManiuLtd** [comment]
创建订单返回null，请各位帮帮忙：https://github.com/overtrue/laravel-wechat/issues/321
