### ISSUE TITLE
现在laravel-wechat是不是不支持最新版本overtrue/wechat

### ISSUE THREAD

**Issue by cnvcanson** [overtrue/laravel-wechat#88]
- Installation request for overtrue/laravel-wechat (locked at 3.1.8, required as ~3.0) -> satisfiable by overtrue/laravel-wechat[3.1.8].

现在laravel-wechat是不是不支持最新版本overtrue/wechat？

**Comment by ac1982** [comment]
`composer require "overtrue/laravel-wechat:~3.1"`
