### ISSUE TITLE
这个用于lumen应该也差不多吧

### ISSUE THREAD

**Issue by nosun** [overtrue/laravel-wechat#9]
如题

**Comment by overtrue** [comment]
@nosun 应该是这样，可以试试

**Comment by viko16** [comment]
@overtrue 在 lumen 中使用会导致一个问题，

[这里](https://github.com/overtrue/laravel-wechat/blob/master/src/ServiceProvider.php#L59) 使用的辅助函数 `config_path ` 在 lumen 中被去掉了，直接使用会导致一个 `Fatal error`，希望能适配一下 :smiley:

**Comment by overtrue** [comment]
@viko16 好的，我看一下

**Comment by viko16** [comment]
@overtrue 其实用在 lumen 上有挺多问题的，

比如[这里](https://github.com/overtrue/laravel-wechat/blob/master/src/ServiceProvider.php#L75)，config() 拿不到数据，后来发现要自己在 `bootstrap/app.php` 里加入 ` $app->configure('wechat');` 才行。

不过这些都是 [lumen 的坑](http://lumen.laravel.com/docs/installation#custom-configuration-files)，如果能在 README 略作说明就更好了 :smiley:

**Comment by overtrue** [comment]
@viko16 这是我的错，我看laravel 作者说兼容laravel,我就没在lumen上实验，正在处理。

**Comment by viko16** [comment]
@overtrue 辛苦了:+1: ，我也正在摸索中

**Comment by overtrue** [comment]
@viko16 @nosun 已经支持了，请查看README
