### ISSUE TITLE
src/ServiceProvider.php 延迟加载的情况下，路由注册应该是无效的吧。

### ISSUE THREAD

**Issue by waney** [overtrue/laravel-wechat#92]
protected $defer = true;
public function boot()
 {
  $this->setupConfig();
    if ($this->isEnableOpenPlatform()) {
      _[**$this->app->register(RouteServiceProvider::class);**](https://github.com/overtrue/laravel-wechat/blob/master/src/ServiceProvider.php)_
    }
}

**Comment by overtrue** [comment]
为啥要用 “应该” 呢？试了么？

**Comment by waney** [comment]
@overtrue 试了。

> Laravel 编译并保存了一份清单，包括由延缓服务提供者所提供的所有服务，以及其服务提供者类的类名。因此，只有在当您在试图解析其中的服务时，Laravel 才会加载该服务提供者。

若要推迟提供者的加载，请将 defer 属性设置为 true ，并定义 provides 方法。

**Comment by overtrue** [comment]
@mingyoung 你测试一下看看

**Comment by waney** [comment]
延迟加载不适合注册路由。发生在路由之后。

**Comment by mingyoung** [comment]
好😄

**Comment by waney** [comment]
然后呢？我也不知道我认为的对不对，请教。 @mingyoung

**Comment by mingyoung** [comment]
#98
