### ISSUE TITLE
Socialite Access Token 不共享问题

### ISSUE THREAD

**Issue by jessynt** [overtrue/laravel-wechat#93]
## 环境

PHP 版本：v7.1.1
overtrue/laravel-wechat 版本：3.2.7

## 问题及现象

OAuth 模块使用了 `overtrue/socialite` ，Access Token 和  `overtrue/wechat` 不共享，每次授权时都需要从微信获取新的 Token ,而该 Token 重复获取会导致`overtrue/wechat`失效，虽然有 retry 机制，但是在并发的情况下可能导致获取用户信息失败的情况

微信错误返回：
```
{"errcode":40001,"errmsg":"invalid credential, access_token is invalid or not latest, hints: [ req_id: xxxxxxxxx ]"}
```

在存入`session`时 [L59](https://github.com/overtrue/laravel-wechat/blob/master/src/Middleware/OAuthAuthenticate.php#L59)，也没有对结果进行判断，导致无法获取用户信息，程序出错

**Comment by jessynt** [comment]
抱歉，对微信授权不太熟悉，我继续跟进下这个错误原因吧

**Comment by PetersonLian** [comment]
有结果了吗
