### ISSUE TITLE
微信网页授权登陆一直无限循环

### ISSUE THREAD

**Issue by liqunx** [overtrue/laravel-wechat#94]
你好，请问有没有人遇到过用laravel中间件的方式做网页授权，然后授权之后本来应该进入业务页，但是一直显示“您最近已经授权过，自动登陆中”，然后一直重复刷新页面；

**Comment by overtrue** [comment]
@liqunx 在授权完成后你应该是 “跳到” 业务页，这里请确认你的中间件是正确的，然后确认 session 正确写入

**Comment by liqunx** [comment]
```
Route::group([
        'middleware' =>  'wechat.oauth'
    ], function () {
        //Route::get('/weixin/test', 'AgentController@test')->name('test');
        Route::get('/weixin/test', function(){
            die('dfadfe');
        });
    });
```
请问这样使用对不对？

**Comment by overtrue** [comment]
die 了怎么写入 session ???????????????????

**Comment by liqunx** [comment]
我找到原因了，是不是一定要web中间件才能写入session？

**Comment by overtrue** [comment]
@liqunx 学习 Laravel 文档吧，session 只在业务流程 “正常运行结束时” 写入，die 并非正常运行结束，谢谢。
