### ISSUE TITLE
OAuthAuthenticate Middleware：Authorize Failed: errcode 40163, code been used

### ISSUE THREAD

**Issue by jeffxu** [overtrue/laravel-wechat#96]
使用\Overtrue\LaravelWechat\Middleware\OAuthAuthenticate这个middleware只针对首页路由做微信授权，有些用户授权之后没有报错，有些用户同意授权后跳回首页会有如下错误，配置文件只在.env内覆盖了WECHAT_APPID和WECHAT_SECRET，其余配置未改过

`[2017-04-17 21:00:05] local.ERROR: exception 'Overtrue\Socialite\AuthorizeFailedException' with message 'Authorize Failed: {"errcode":40163,"errmsg":"code been used, hints: [ req_id: y2uBqA0005th14 ]"}' in /var/www/wel/vendor/overtrue/socialite/src/Providers/AbstractProvider.php:399
Stack trace:
#0 /var/www/wel/vendor/overtrue/socialite/src/Providers/WeChatProvider.php(81): Overtrue\Socialite\Providers\AbstractProvider->parseAccessToken(Object(GuzzleHttp\Psr7\Stream))
#1 /var/www/wel/vendor/overtrue/socialite/src/Providers/AbstractProvider.php(173): Overtrue\Socialite\Providers\WeChatProvider->getAccessToken('041dtY3b2LZjeQ0...')
#2 /var/www/wel/vendor/overtrue/laravel-wechat/src/Middleware/OAuthAuthenticate.php(59): Overtrue\Socialite\Providers\AbstractProvider->user()
#3 [internal function]: Overtrue\LaravelWechat\Middleware\OAuthAuthenticate->handle(Object(Illuminate\Http\Request), Object(Closure))
#4 /var/www/wel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(136): call_user_func_array(Array, Array)
#5 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#6 /var/www/wel/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#7 [internal function]: Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#8 /var/www/wel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#9 /var/www/wel/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(96): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#10 /var/www/wel/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(54): Illuminate\Routing\ControllerDispatcher->callWithinStack(Object(App\Http\Controllers\HomeController), Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'index')
#11 /var/www/wel/vendor/laravel/framework/src/Illuminate/Routing/Route.php(174): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'App\\Http\\Contro...', 'index')
#12 /var/www/wel/vendor/laravel/framework/src/Illuminate/Routing/Route.php(140): Illuminate\Routing\Route->runController(Object(Illuminate\Http\Request))
#13 /var/www/wel/vendor/laravel/framework/src/Illuminate/Routing/Router.php(724): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#14 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))`

完整报错日志：[err.txt](https://github.com/overtrue/laravel-wechat/files/927507/err.txt)

**Comment by Frewen** [comment]
我也遇到了同样的问题

> exception 'Overtrue\Socialite\AuthorizeFailedException' with message 'Authorize Failed: {"errcode":40029,"errmsg":"invalid code, hints: [ req_id: L8rpda0560th14 ]"}' in /deploy/eh/eh_wechat/vendor/overtrue/socialite/src/Providers/AbstractProvider.php:399

针对 [这个回答](https://github.com/overtrue/laravel-wechat/issues/71) 同样的设置，还是出现问题。

环境 
  Laravel Framework 5.4.25
"overtrue/laravel-wechat": "~3.0"

**Comment by RDCynthia** [comment]
我也碰到这个问题，好像知道是什么原因了。

问题描述：在获取code后，服务器会调转到带有code和state的网址，然后框架通过token去获取用户信息。但是，如果在跳转带有code和state的网址去获取用户信息之后，在跳转到目标页面之前，出现语句错误、使用dd中断语句、获取网络出现问题，将导致code been used。

原因：微信浏览器会在你，语句错误、中断、网络等因素导致无法跳转面目标页面，会重新进行一次带有code和state的网址请求，就像pc浏览器一样会重新尝试连接的，而之前那个code我们已经代码请求过了，但由于不成功的原因，浏览器又重新请求一次，这样就导致code已经用过了。

测试环境：我是个小白，也没有域名，所以用的服务器公网IP。微信浏览器在IP访问时候，会进行网址显示并提示是否访问。正因为如此，我发现明明已经正常访问，但是如果中断dd测试，他会一闪而过我的中断测试（一瞬间可以看到），然后提示我是否访问带有code和state的网址。如果继续，则提示code不可用。

由此猜测，应该浏览器重新发起请求原因造成的。我也不太确定，但把dd换成Log打印日志，让他能顺利访问到目标页面，就不报错了。

**Comment by One2r** [comment]
同样也遇到这个问题
